#!/bin/bash
# Regenerate linux/toolchain_wrapper/ -- a thin, self-contained wrapper around the
# AMD/Xilinx prebuilt rv32 glibc toolchain. Buildroot points BR2_TOOLCHAIN_EXTERNAL_PATH
# at the wrapper, never at the vendor dir. Nothing under the vendor install is written.
#
# WHY (both reasons are measured, not stylistic -- see README.md):
#
#  1. The vendor gcc's BUILT-IN DEFAULT is -march=rv32imafdc -mabi=ilp32d (hard float).
#     That default cannot even compile hello-world against the vendor's OWN sysroot
#     (which is soft-float ilp32 rv32imac_zicbom_zba_zbb_zbs), and hard float is wrong
#     for this core anyway (C_USE_FPU=0). Buildroot probes the compiler with NO abi
#     flags in several places (toolchain/helpers.mk check_toolchain_ssp, called from
#     pkg-toolchain-external.mk:607), so those probes hit the broken default and the
#     build dies with a misleading "SSP support not available in this toolchain".
#     Fixing the DEFAULT fixes every such probe.
#
#  2. We call the vendor's REAL compilers directly
#     (x86_64-amdedfsdk-linux/usr/bin/riscv32-amd-linux/riscv32-amd-linux-*), replicating
#     what the vendor's own bin/ driver scripts do (--sysroot=<glibc sysroot>), rather
#     than chaining through bin/riscv32-amd-linux-gnu-*.
set -euo pipefail

# The vendor toolchain: MBV_LINUX_TOOLCHAIN (environment, else the same key in
# the repo-root tools.env -- see tools.env.example), else derived from
# XILINX_VIVADO (set by Vivado 2026.1's settings64.sh). No site default.
_here="$(cd "$(dirname "$0")" && pwd)"
_repo="$(git -C "$_here" rev-parse --show-toplevel 2>/dev/null || true)"
_tools_env() { [ -n "$_repo" ] && sed -n "s/^[[:space:]]*$1[[:space:]]*[:?]\{0,1\}=[[:space:]]*//p" "$_repo/tools.env" 2>/dev/null | tail -n 1; }
TC=${MBV_LINUX_TOOLCHAIN:-$(_tools_env MBV_LINUX_TOOLCHAIN || true)}
if [ -z "$TC" ] && [ -n "${XILINX_VIVADO:-}" ]; then
    TC=$XILINX_VIVADO/gnu/riscv/linux_toolchain/lin32
fi
[ -n "$TC" ] && [ -d "$TC" ] || {
    echo "mk_toolchain_wrapper.sh: the AMD rv32 glibc toolchain was not found (TC='$TC')." >&2
    echo "  Set MBV_LINUX_TOOLCHAIN=<Vivado 2026.1>/gnu/riscv/linux_toolchain/lin32 in tools.env" >&2
    echo "  or the environment, or source Vivado 2026.1's settings64.sh (XILINX_VIVADO)." >&2
    exit 1; }
REAL=$TC/x86_64-amdedfsdk-linux/usr/bin/riscv32-amd-linux
SYSROOT=$TC/riscv32imac_zicbom_zba_zbb_zbs-amd-linux
W="$(cd "$(dirname "$0")" && pwd)/toolchain_wrapper"

# The ONE ISA/ABI that is correct here: matches the shipped glibc exactly, and is a
# strict subset of the core (which also has Zba/Zbb/Zbs), so binaries also run on qemu-virt.
ISA="-march=rv32imac_zicsr_zifencei -mabi=ilp32"

rm -rf "$W"; mkdir -p "$W/bin"

# EVERY tool is a generated absolute-path script -- NOT a symlink to the vendor's.
#
# Reason (a real failure, not tidiness): the vendor's bin/ scripts locate their payload
# with `dirname $0`, and $0 is the *invocation* path, which a symlink does not change.
# Buildroot symlinks output/host/bin/<tool> -> <this dir>/<tool>, so a vendor script
# reached that way computes .../output/host/bin/../x86_64-amdedfsdk-linux/... which does
# not exist -> "gcc-ar: No such file or directory" -> busybox dies with Error 127.
# Absolute paths make the wrappers position-independent, so Buildroot can copy or
# symlink them anywhere.
#
# NOTE: write regular files only. Never redirect onto a symlink that points into
# the vendor install -- the redirect follows it and writes THROUGH into the read-only tree.
for f in "$TC"/bin/riscv32-amd-linux-gnu-*; do
    tool=$(basename "$f")
    tool=${tool#riscv32-amd-linux-gnu-}            # e.g. "ar", "gcc-ar", "objdump"
    real="$REAL/riscv32-amd-linux-$tool"
    [ -e "$real" ] || { echo "warn: no vendor tool for '$tool' -- skipped"; continue; }
    t="$W/bin/riscv32-amd-linux-gnu-$tool"
    rm -f "$t"
    case "$tool" in
        gcc|g++|cpp)   # compiler drivers: add the sysroot AND fix the broken default ISA
            printf '#!/bin/bash\n# generated by mk_toolchain_wrapper.sh -- do not edit\nexec "%s" --sysroot="%s" %s "$@"\n' \
                   "$real" "$SYSROOT" "$ISA" > "$t" ;;
        *)             # binutils/gdb/gcov: straight passthrough, absolute path
            printf '#!/bin/bash\n# generated by mk_toolchain_wrapper.sh -- do not edit\nexec "%s" "$@"\n' \
                   "$real" > "$t" ;;
    esac
    chmod +x "$t"
done

# Assert the wrapper is correct with NO flags -- that is the case Buildroot probes.
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
echo 'int main(void){return 0;}' > "$tmp/t.c"
"$W/bin/riscv32-amd-linux-gnu-gcc" "$tmp/t.c" -o "$tmp/t"
readelf -h "$tmp/t" | grep -q 'soft-float' \
    || { echo "FATAL: wrapper is not producing soft-float ilp32 binaries"; exit 1; }
echo 'int main(){}' | "$W/bin/riscv32-amd-linux-gnu-gcc" -Werror -fstack-protector -x c - -o "$tmp/s" \
    || { echo "FATAL: flag-less SSP probe fails (Buildroot will reject the toolchain)"; exit 1; }
echo "toolchain_wrapper OK: $W  (soft-float ilp32 rv32imac by default)"
