// GENERATED by gen_shadow.py from signals_selftest.yaml -- DO NOT EDIT
//
// Shadow IICE for IICE_SELFTEST. Portless, testbench-only; uses absolute
// hierarchical references, so it needs no wiring at all:
//
//     iice_shadow_IICE_SELFTEST u_iice_shadow();
//
// Runtime plusargs:
//     +iice_shadow        enable FSDB dumping. DEFAULT OFF, so adding this
//                         module to a bench cannot slow an existing gate.
//     +iice_fsdb=<path>   output file (default sim_iice.fsdb).
//
// Contract: tests/identify_iice/INTERFACES.md sections 0, 1 and 3.2.
// Edit signals_selftest.yaml and re-run `make -C tests/identify_iice gen` instead.

module iice_shadow_IICE_SELFTEST;

  // Manifest depth, recorded for downstream readers. NOTHING here
  // consumes it: the sim does not buffer (INTERFACES.md section 0) -- the
  // offline cropper uses depth + trigger_time to cut the window.
  localparam int IICE_DEPTH = 64;

  // The IICE sample clock, tapped from the design. Same net, same edge as
  // the hardware IICE samples on (manifest iice.clock).
  logic sample_clk;
  assign sample_clk = tb.u_dut.clk;

  // ---------------------------------------------------------------------
  // Registered mirrors -- clocked on the manifest edge (posedge). THIS is
  // what makes the trace IICE-faithful: exactly one value per sample edge,
  // no combinational glitches. Names are the manifest names verbatim, so
  // the FSDB leaf names match the hardware side by construction
  // (INTERFACES.md section 1).
  // ---------------------------------------------------------------------
  logic [31:0] haddr;
  logic [1:0]  htrans;
  logic        hwrite;
  logic [31:0] hrdata;
  logic        hready;
  logic [2:0]  state;
  logic        lockup;

  always_ff @(posedge sample_clk) begin
    haddr  <= tb.u_dut.haddr;
    htrans <= tb.u_dut.htrans;
    hwrite <= tb.u_dut.hwrite;
    hrdata <= tb.u_dut.hrdata;
    hready <= tb.u_dut.hready;
    state  <= tb.u_dut.state;
    lockup <= tb.u_dut.lockup;
  end

  // ---------------------------------------------------------------------
  // Trigger marker. Registered off the ALREADY-REGISTERED mirrors above, so
  // it is ONE sample edge later than the raw condition:
  //
  //     trigger_marker high at sample N  <=>  the trigger condition held
  //                                           at sample N-1
  //
  // That offset is INTENTIONAL and the offline cropper owns it
  // (INTERFACES.md section 3.2). Do NOT 'fix' it here or in the generator --
  // doing so silently shifts every cropped window by one sample.
  //
  // The expression is the manifest's trigger.expr, emitted verbatim over the
  // mirror registers (never over raw design paths).
  // ---------------------------------------------------------------------
  logic trigger_marker;
  always_ff @(posedge sample_clk)
    trigger_marker <= (htrans == 2'b10 && haddr == 32'h0000_0040);

  // ---------------------------------------------------------------------
  // FSDB dump, gated on +iice_shadow (see the header). Dumping the whole
  // scope of this module yields exactly the manifest signals plus
  // sample_clk and trigger_marker -- the flat probe set the compare
  // pipeline expects, and nothing else.
  // ---------------------------------------------------------------------
  initial begin
    string f;
    if ($test$plusargs("iice_shadow")) begin
      if (!$value$plusargs("iice_fsdb=%s", f)) f = "sim_iice.fsdb";
      $fsdbDumpfile(f);
      $fsdbDumpvars(0, iice_shadow_IICE_SELFTEST);
      $display("[iice_shadow] IICE_SELFTEST ARMED: depth=%0d edge=posedge -> %s",
               IICE_DEPTH, f);
    end
    else begin
      $display("[iice_shadow] IICE_SELFTEST IDLE: no FSDB written.");
      $display("[iice_shadow] pass +iice_shadow to enable it, +iice_fsdb=<path> to relocate.");
    end
  end

endmodule
