#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# build_bootrom.sh — build the reworked stage-0 bootloader and regenerate the
# synthesizable boot ROM (bootrom.sv) for the true-flash-boot co-sim, WITHOUT
# mutating the shared SoC tree.
#
# The sim's BOOTROM is a case-statement ROM generated by bootrom_gen.py from
# stage0.hex. To run the reworked stage-0 (copy HOT image from flash -> IMEM)
# in simulation, we must recompile the shared source
#   nanosoc_m0_soc/firmware/bootloader/stage0/stage0_bootloader.c
# and regenerate bootrom.sv. We deposit the artifacts in THIS bench's build/
# dir (OUT) and leave imp/fpga/firmware/stage0/bootrom.sv untouched; the bench
# Makefile swaps our local bootrom.sv into the generated filelist.
#
# This mirrors the CMake recipe (imp/fpga/firmware/stage0) EXACTLY:
#   flags/defines/includes/linker from CMakeFiles/stage0.dir/{flags,link}.make,
#   plus -DNANOSOC_QSPI_CTRL_BASE=0x74000000UL (the QSPI APB cfg base): the
#   on-disk imp/fpga/fw_config memmap was regenerated with QSPI DISABLED and no
#   longer defines it, but the RTL fits qspi_ctrl @ 0x7400_0000 (build_soc
#   memmap / tests/qspi_xip), so the ROM must be built against that address.
#
#   ADDRESS_WIDTH 9 => 512 words => 2 KB ROM window (HADDR[10:2]); the build
#   fails loudly if stage0 overflows it.
#
# Copyright (C) 2026, SoC Labs (www.soclabs.org)
# -----------------------------------------------------------------------------
set -euo pipefail

SOC=${SOCLABS_NANOSOC_SOC_DIR:?set SOCLABS_NANOSOC_SOC_DIR to the nanosoc_m0_soc checkout (see tools.env.example)}
AT=$SOC/nanosoc_arch_tech/firmware/software
TOOLCHAIN_BIN=${TOOLCHAIN_BIN:-${ARM_GCC_BIN:-}}   # empty => arm-none-eabi-* from PATH
OUT=${1:?usage: build_bootrom.sh <output-dir>}
PY=${PYTHON:-python3}

mkdir -p "$OUT"
[ -n "$TOOLCHAIN_BIN" ] && export PATH="$TOOLCHAIN_BIN:$PATH"

CFLAGS="-g -O1 -Os -flto -mthumb-interwork -mcpu=cortex-m0 -mthumb"
DEFS="-DCORTEX_M0 -D__HEAP_SIZE=0x1000 -D__STACK_SIZE=0x200 -DNANOSOC_QSPI_CTRL_BASE=0x74000000UL"
INCS="-I$SOC/firmware/bootloader/stage0/.. \
      -I$AT/cmsis/Device/ARM/CMSDK_CM0/Include \
      -I$AT/cmsis/CMSIS/Include \
      -I$SOC/imp/fpga/fw_config \
      -I$AT/drivers"

echo "[build_bootrom] compiling reworked stage-0 -> $OUT"
arm-none-eabi-gcc $CFLAGS $DEFS $INCS -c \
    "$AT/cmsis/Device/ARM/CMSDK_CM0/Source/GCC/startup_CMSDK_CM0.s" -o "$OUT/startup.o"
arm-none-eabi-gcc $CFLAGS $DEFS $INCS -c \
    "$SOC/firmware/bootloader/stage0/stage0_bootloader.c" -o "$OUT/stage0_bootloader.o"
arm-none-eabi-gcc $CFLAGS $DEFS $INCS -c \
    "$AT/cmsis/Device/ARM/CMSDK_CM0/Source/system_CMSDK_CM0.c" -o "$OUT/system.o"

arm-none-eabi-gcc -g -T"$AT/common/scripts/cmsdk_bootloader.ld" \
    -L"$AT/common/scripts" -L"$SOC/imp/fpga/fw_config" \
    -mcpu=cortex-m0 -mthumb --specs=nano.specs -Wl,--gc-sections \
    "$OUT/startup.o" "$OUT/stage0_bootloader.o" "$OUT/system.o" -o "$OUT/stage0.elf"

arm-none-eabi-objcopy -S "$OUT/stage0.elf" -O binary "$OUT/stage0.bin"
arm-none-eabi-objcopy -S "$OUT/stage0.elf" -O verilog "$OUT/stage0.hex"

sz=$(wc -c < "$OUT/stage0.bin")
echo "[build_bootrom] stage0.bin = $sz bytes (ROM window = 2048)"
if [ "$sz" -gt 2048 ]; then
    echo "[build_bootrom] ERROR: stage0 overflows the 2 KB boot ROM ($sz > 2048)" >&2
    exit 1
fi

echo "[build_bootrom] regenerating bootrom.sv (module 'bootrom', -a 9)"
$PY "$SOC/nanosoc_arch_tech/firmware/testcodes/bootloader/bootrom_gen.py" \
    -a 9 -i "$OUT/stage0.hex" -t gcc -m bootrom \
    -v "$OUT/bootrom.sv" -b "$OUT/bootrom.bintxt" \
    -R nanosoc_region_bootrom -r "$OUT/nanosoc_region_bootrom.v"

echo "[build_bootrom] done: $OUT/bootrom.sv"
