/* mps3_shell_static_id.c -- GENERATED by `make -C fpga/dfx overlays`; do not edit.
 *
 * Strong override for the weak mps3_shell_static_id() seam
 * (firmware/coordinator/coordinator.c). A3: compile+link this file into
 * the shell firmware image so the running shell reports the static_id of
 * the exact locked static (static_routed_locked.dcp) these overlay
 * triples were generated against -- the pusher refuses on mismatch
 * (overlay-manifest.md; net-protocol.md ping.shell_id).
 *
 * static_id = CRC-32 (zlib) of static_routed_locked.dcp -- see
 * fpga/dfx/README.md "static_id scheme". Value below matches every
 * overlay/<rm>/manifest.json generated in the same run.
 */
#include <stdint.h>

uint32_t mps3_shell_static_id(void)
{
    return 0x72BB0A36UL;
}
