#!/usr/bin/env python3
"""gen_shadow.py — manifest -> `<out>/iice_shadow_<iice_name>.sv`.

Emits the portless SystemVerilog shadow-IICE module described by INTERFACES.md
§3.2 (FROZEN format).

    python3 gen_shadow.py --manifest signals_selftest.yaml --out build

Design rationale (INTERFACES.md §0 — read that first): this is NOT a ring
buffer. A hardware IICE buffers because it must; a simulation does not. The
module mirrors the probe set into REGISTERED copies clocked on the same edge as
the real IICE's sample clock, dumps them to FSDB continuously, and the window is
cropped offline in Python from the recorded trigger time plus the manifest's
`depth`/`trigger_time`. Registering is what makes the trace faithful — the IICE
only ever sees values at the sample edge, never the combinational glitches
between edges that a raw sim dump is full of.

Two details in the generated file that look like bugs and are not:

1. `trigger_marker` is registered off the ALREADY-REGISTERED mirrors, so it is
   one sample edge later than the raw condition. INTERFACES.md §3.2: "trigger_marker
   high at sample N means the trigger condition held at sample N-1. The cropper
   owns this offset; do not 'fix' it in the generator." The generated file says
   so too, because this is exactly the kind of thing a future reader helpfully
   corrects.

2. FSDB dumping is gated on `+iice_shadow`. §3.2 requires the plusarg to be the
   enable AND requires that the TB not dump by default, and a module instance
   cannot be created conditionally at run time — so the gate has to live in the
   module's `initial` block. Consequence for Stream B: `make sim-fsdb` MUST pass
   `+iice_shadow` on the simv command line. The `else` branch prints a loud
   "idle" line so a forgotten plusarg is one grep away, never a silent empty
   FSDB.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import manifest as mf  # noqa: E402

DEFAULT_FSDB = "sim_iice.fsdb"


def render(m):
    """Return the full shadow-module SystemVerilog text for manifest `m`."""
    mod = m.shadow_module
    edge = m.iice.clock.sv_edge
    src = m.source_name

    ranges = [s.sv_decl() for s in m.signals]
    rw = max(len(r) for r in ranges)
    nw = max(len(s.name) for s in m.signals)

    L = []
    a = L.append

    # --- provenance header (§3.2 requires a GENERATED ... DO NOT EDIT line
    #     naming the source manifest) ----------------------------------------
    a("// GENERATED by gen_shadow.py from %s -- DO NOT EDIT" % src)
    a("//")
    a("// Shadow IICE for %s. Portless, testbench-only; uses absolute" % m.iice.name)
    a("// hierarchical references, so it needs no wiring at all:")
    a("//")
    a("//     %s u_iice_shadow();" % mod)
    a("//")
    a("// Runtime plusargs:")
    a("//     +iice_shadow        enable FSDB dumping. DEFAULT OFF, so adding this")
    a("//                         module to a bench cannot slow an existing gate.")
    a("//     +iice_fsdb=<path>   output file (default %s)." % DEFAULT_FSDB)
    a("//")
    a("// Contract: tests/identify_iice/INTERFACES.md sections 0, 1 and 3.2.")
    a("// Edit %s and re-run `make -C tests/identify_iice gen` instead." % src)
    a("")
    a("module %s;" % mod)
    a("")

    # --- depth ---------------------------------------------------------------
    a("  // Manifest depth, recorded for downstream readers. NOTHING here")
    a("  // consumes it: the sim does not buffer (INTERFACES.md section 0) -- the")
    a("  // offline cropper uses depth + trigger_time to cut the window.")
    a("  localparam int IICE_DEPTH = %d;" % m.iice.depth)
    a("")

    # --- sample clock --------------------------------------------------------
    a("  // The IICE sample clock, tapped from the design. Same net, same edge as")
    a("  // the hardware IICE samples on (manifest iice.clock).")
    a("  logic sample_clk;")
    a("  assign sample_clk = %s;" % m.iice.clock.sim)
    a("")

    # --- registered mirrors --------------------------------------------------
    a("  // ---------------------------------------------------------------------")
    a("  // Registered mirrors -- clocked on the manifest edge (%s). THIS is" % edge)
    a("  // what makes the trace IICE-faithful: exactly one value per sample edge,")
    a("  // no combinational glitches. Names are the manifest names verbatim, so")
    a("  // the FSDB leaf names match the hardware side by construction")
    a("  // (INTERFACES.md section 1).")
    a("  // ---------------------------------------------------------------------")
    for s, r in zip(m.signals, ranges):
        a("  logic %-*s %s;" % (rw, r, s.name))
    a("")
    a("  always_ff @(%s sample_clk) begin" % edge)
    for s in m.signals:
        a("    %-*s <= %s;" % (nw, s.name, s.sim))
    a("  end")
    a("")

    # --- trigger marker ------------------------------------------------------
    a("  // ---------------------------------------------------------------------")
    a("  // Trigger marker. Registered off the ALREADY-REGISTERED mirrors above, so")
    a("  // it is ONE sample edge later than the raw condition:")
    a("  //")
    a("  //     trigger_marker high at sample N  <=>  the trigger condition held")
    a("  //                                           at sample N-1")
    a("  //")
    a("  // That offset is INTENTIONAL and the offline cropper owns it")
    a("  // (INTERFACES.md section 3.2). Do NOT 'fix' it here or in the generator --")
    a("  // doing so silently shifts every cropped window by one sample.")
    a("  //")
    a("  // The expression is the manifest's trigger.expr, emitted verbatim over the")
    a("  // mirror registers (never over raw design paths).")
    a("  // ---------------------------------------------------------------------")
    a("  logic trigger_marker;")
    a("  always_ff @(%s sample_clk)" % edge)
    a("    trigger_marker <= (%s);" % m.trigger_expr)
    a("")

    # --- FSDB dump -----------------------------------------------------------
    a("  // ---------------------------------------------------------------------")
    a("  // FSDB dump, gated on +iice_shadow (see the header). Dumping the whole")
    a("  // scope of this module yields exactly the manifest signals plus")
    a("  // sample_clk and trigger_marker -- the flat probe set the compare")
    a("  // pipeline expects, and nothing else.")
    a("  // ---------------------------------------------------------------------")
    a("  initial begin")
    a("    string f;")
    a("    if ($test$plusargs(\"iice_shadow\")) begin")
    a("      if (!$value$plusargs(\"iice_fsdb=%%s\", f)) f = \"%s\";" % DEFAULT_FSDB)
    a("      $fsdbDumpfile(f);")
    a("      $fsdbDumpvars(0, %s);" % mod)
    a("      $display(\"[iice_shadow] %s ARMED: depth=%%0d edge=%s -> %%s\","
      % (m.iice.name, edge))
    a("               IICE_DEPTH, f);")
    a("    end")
    a("    else begin")
    a("      $display(\"[iice_shadow] %s IDLE: no FSDB written.\");" % m.iice.name)
    a("      $display(\"[iice_shadow] pass +iice_shadow to enable it, "
      "+iice_fsdb=<path> to relocate.\");")
    a("    end")
    a("  end")
    a("")
    a("endmodule")
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--manifest", required=True, help="path to signals*.yaml")
    ap.add_argument("--out", required=True,
                    help="output DIRECTORY; the file is <out>/iice_shadow_<iice_name>.sv")
    args = ap.parse_args(argv)

    try:
        m = mf.load(args.manifest)
    except mf.ManifestError as exc:
        sys.stderr.write("gen_shadow.py: %s\n" % exc)
        return 2

    os.makedirs(args.out, exist_ok=True)
    out_path = os.path.join(args.out, "%s.sv" % m.shadow_module)
    with open(out_path, "w") as fh:
        fh.write(render(m))
    print("gen_shadow.py: wrote %s (%d mirrors)" % (out_path, len(m.signals)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
