##############################################################################
# mps3_harness_timing.xdc -- IMPLEMENTATION-ONLY harness timing constraints
#
# Loaded with USED_IN_SYNTHESIS=false by fpga/shell/build_shell.tcl (the
# clock objects referenced below are generated by the shell BD's clk_wiz
# cells and only exist once those IP have elaborated). NOTE: Vivado also
# applies this file when a post-SYNTH design is opened for analysis
# (open_run synth_1 loads implementation constraints) -- so post-synth
# timing reports already reflect these constraints; that is how the earlier
# unmeetable SMC I/O-delay version of this file was caught (WNS -29.3 ns on
# SMBF_DATA input paths, 2026-07-06 first full build pass).
#
# I/O timing philosophy (this revision): every board interface on this
# harness is either asynchronous or quasi-static at the pad --
#   * LAN9220 SMC bus: asynchronous SRAM-style protocol; the AC budget
#     (address/CE -> data valid, pulse widths, cycle floors) is enforced by
#     axi_emc_0's programmed bank timing (shell_bd.tcl SECTION 4, values
#     derived in fpga/ethernet/lan9220_if/README.md), counted in shell-clock
#     cycles inside the core -- NOT by pad-level setup/hold to a clock edge.
#     Single-cycle set_input_delay/set_output_delay against the 100 MHz
#     shell clock is unmeetable by construction (40 ns budget vs 10 ns
#     period) and models the wrong thing; the bus members are held stable
#     across many cycles per transaction.
#   * UART, LEDs, push-button, DIP switches, ETH_INT: async /
#     human-speed / firmware-paced; 2-FF synchronizers (or the IP's own
#     16x oversampling, for UART RX) own the metastability budget.
# Hence: false-path exceptions at the pads, full constraint coverage for
# everything clock-domain-internal (BD-generated clocks + the async group
# below). If a future interface is genuinely source-synchronous (e.g. a
# real RMII PHY pad), give it real I/O delays -- do not extend these
# false paths to it.
#
# The external QSPI flash IS such an interface. Its model (the 2026-07-16
# QSPI timing pass) is constraints/qspi/mps3_qspi_pad_timing.xdc and is DORMANT
# -- see the QSPI section below. The pad groups that DO carry real I/O delays
# here are the CLCD 8080 bus and the user microSD (skew windows / a multicycle
# input, each argued in its section).
#
# NO TCL CONTROL FLOW IN THIS FILE (2026-09-24). An XDC is not a Tcl script:
# Vivado supports only a subset (set, expr, get_*, the constraint commands),
# and a command outside it -- `if`, `catch`, `puts`, `foreach` -- is dropped
# WITH ITS WHOLE BODY under a CRITICAL WARNING [Designutils 20-1307]. The QSPI,
# CLCD and USD blocks all sat inside `if`s and so none of them ever applied,
# on any shell. build_shell.tcl now refuses an XDC with such a command before
# synth (fpga/shell/tools/xdc_gate.tcl) and fails the build if the run logs
# report 20-1307 anyway; tests/shell_cpu_seam/test_xdc_subset.py checks the
# same board-free.
#
# Target: Vivado 2024.1, part xcku115-flvb1760-1-c
##############################################################################

##############################################################################
# Real shell-clock objects (clk_wiz cells in shell_bd.tcl SECTION 1):
#   clk_wiz_shell/clk_out1 : fixed ~100 MHz shell/AXI/MicroBlaze/ICAP clock
#   clk_wiz_shell/clk_out2 : fixed 50 MHz RMII reference (same MMCM ->
#                            synchronous with clk_out1; no group split)
#   clk_wiz_dut/clk_out1   : DRP-reconfigurable DUT clock (async domain)
##############################################################################
set clk_shell [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ "*/clk_wiz_shell/clk_out1"}]]
set clk_dut   [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ "*/clk_wiz_dut/clk_out1"}]]

##############################################################################
# Async clock groups: the shell's fixed domain vs the DUT-clock MMCM output.
# Every crossing between the two is CDC-structured on the static side
# (uart_bridge's gray-pointer async FIFOs, the per-block 2-FF synchronizers
# -- spec §5 "CDC everywhere the static and DUT domains meet"), so declare
# them asynchronous rather than leaving false inter-MMCM paths timed.
##############################################################################
set_clock_groups -name async_shell_dutclk -asynchronous \
    -group $clk_shell \
    -group $clk_dut

##############################################################################
# LAN9220 SMC bus -- asynchronous SRAM-style bus, paced by axi_emc_0's bank
# timing (see header). ETH_INT is an async interrupt line (firmware
# additionally reconfigures its polarity via IRQ_CFG before unmasking).
##############################################################################
set_false_path -to   [get_ports {SMBF_ADDR[*] SMBF_DATA[*] SMBF_FIFOSEL SMBF_nOE SMBF_nWE SMBF_nRST ETH_nCS ETH_nOE}]
set_false_path -from [get_ports {SMBF_DATA[*]}]
set_false_path -from [get_ports ETH_INT]

##############################################################################
# Board-level static control / status: LEDs, push-button reset, DIP
# switches (quasi-static human inputs; board_gpio's own 2-FF input
# synchronizers own the metastability budget).
##############################################################################
set_false_path -to   [get_ports {USER_nLED[*]}]
set_false_path -from [get_ports USER_nPB0]
set_false_path -from [get_ports {USER_SW[*]}]

##############################################################################
# External QSPI flash (SST26VF064B) -- RP-owned XiP path. NOT CONSTRAINED HERE.
#
# Its source-synchronous model (generated SCLK at the pad, DS20005119G setup/
# hold, the half-period read budget) is constraints/qspi/mps3_qspi_pad_timing.xdc,
# and it is DORMANT: it sat in this file inside a Tcl `if`, which XDC does not
# support ([Designutils 20-1307]), so Vivado dropped it on every build -- no
# shell has ever had QSPI pad timing. It needs one DFX run with a qspi RM
# before it can be switched on (that file's header). Until then these six pads
# are unconstrained, as they always were, and check_timing says so.
##############################################################################

##############################################################################
# CLCD 8080 panel bus (Himax HX8347-D, 14 pads, bank 66, LVCMOS18)
# ---------------------------------------------------------------------------
# FIRST-PASS, BOARD-SIGNOFF-PENDING. The panel is LIT and WORKING on silicon
# with the shipped TIMING values below (docs/CLCD_PANEL_FACTS.md), so this
# block's job is to STOP the pads being unconstrained -- not to discover a
# frequency. Read the caveats at the bottom before trusting the numbers.
#
# WHY THIS IS NOT THE QSPI MODEL (do not copy that block down here):
#   The QSPI flash returns data against a clock WE forward (SCLK), so it is a
#   genuine source-synchronous interface and gets a generated clock + input/
#   output delays referenced to it. The CLCD 8080 bus has NO forwarded clock:
#   CLCD_WR_SCL is a STROBE the shell's FSM generates, and the panel latches
#   PD/RS on the WR RISING edge. There is no clock to reference, and nothing
#   is captured back. So the real requirement is not "meet a clock" -- it is
#   "PD/RS must be stable around the WR edge AT THE PANEL", i.e. a bound on
#   the pad-to-pad SKEW of a group that all launches from one clock domain.
#
# THE ACTUAL MARGIN COMES FROM THE FSM, NOT FROM THIS CONSTRAINT:
#   clcd_core.sv's 3-phase strobe FSM holds CS/RS/PD stable for cs_setup, then
#   drives WR low for wr_lo, then high for wr_hi -- all in s_axi_aclk cycles,
#   runtime-programmable via the TIMING register. The SHIPPED, BOARD-PROVEN
#   values are cs_setup=2, wr_lo=4, wr_hi=4 at the 100 MHz shell clock:
#       CS/RS/PD stable -> WR falls : 20 ns
#       WR low                      : 40 ns   <- PD/RS stable this whole time
#       WR high                     : 40 ns   <- ...and this whole time
#   so PD/RS are stable ~40 ns EITHER SIDE of the WR rising edge that latches
#   them. The panel needs single-digit-ns setup/hold (see caveat 1). The FSM
#   therefore carries ~4x margin in CYCLES. The ONLY thing that can erode it
#   is clock-to-pad SKEW between the data/control pads and the WR pad.
#
# WHAT THIS CONSTRAINT DOES:
#   Bound every strobed CLCD pad's clock-to-pad delay into one window relative
#   to the shell clock, so the tool cannot skew WR away from PD/RS. With the
#   window below ([0, 10] ns after the launching clk_shell edge) worst-case
#   pairwise skew is <= 10 ns, leaving >= 30 ns of the FSM's 40 ns intact --
#   still 3x the panel's need. This is deliberately a SKEW BUDGET expressed as
#   output delays, not a fabricated setup/hold against an imaginary clock.
##############################################################################

set clcd_strobed [get_ports {CLCD_PD[*] CLCD_RS CLCD_CS CLCD_WR_SCL}]

# THE WINDOW, CORRECTED 2026-09-24. For an output port Vivado checks
#     setup:  arrival_max <= T - od_max        hold:  arrival_min >= -od_min
# so the previous -max 8.0 / -min -2.0 was the window [2, 2] ns -- ZERO wide,
# unmeetable by any fabric-launched pad (clock insertion alone is ~3 ns). D13
# measured the identical pair at -5.6 ns on the USD pads (its I-SHELL report)
# and fixed it there; this block never failed only because it never APPLIED:
# it sat in a Tcl `if`, which XDC drops ([Designutils 20-1307]), on every shell
# including the fielded ones. -max 0.0 / -min 0.0 is the window [0, 10] ns the
# header maths above always meant: every strobed pad lands within ONE clk_shell
# period of the launching edge, so pairwise skew <= 10 ns and >= 30 ns of the
# FSM's 40 ns survives. (No `if` around it: these 11 ports exist in every shell
# variant, and a port that did not would be a CRITICAL WARNING, not a skip.)
set_output_delay -clock $clk_shell -max 0.0 $clcd_strobed
set_output_delay -clock $clk_shell -min 0.0 $clcd_strobed

# --- Explicitly-argued exceptions (NOT laziness -- these have no edge to meet) --
#
# CLCD_BL / CLCD_RST are quasi-static LEVELS, not part of any strobed transfer:
# firmware writes CTRL and the level sits there for milliseconds (backlight on,
# panel reset asserted for >= 2 ms at init -- firmware/clcd/clcd.c). There is no
# capture edge anywhere in the system that samples them, so a setup/hold number
# would be fiction. Constraining them would only distort placement.
set_false_path -to [get_ports -quiet {CLCD_BL CLCD_RST}]

# CLCD_RD: the shipped shell builds clcd with READ_PATH=0 (docs/CLCD_PANEL_FACTS.md
# -- read-back is NOT built), so RD is held deasserted, constant. Nothing toggles.
set_false_path -to [get_ports -quiet CLCD_RD]

# CLCD_PD INPUT path: with READ_PATH=0 the IOBUFs' O pins feed nothing (pd_oe is
# tied 1, the block is write-only). The input path is structurally dead. If a
# future build sets READ_PATH=1, DELETE this and give the read-back a real
# input-delay -- it would then be a genuine (slow, strobed) input.
set_false_path -from [get_ports -quiet {CLCD_PD[*]}]

##############################################################################
# CLCD caveats -- what a timing engineer must close at signoff
#  1. The HX8347-D datasheet 8080 write numbers (tDST setup / tDHT hold / tWRLW
#     pulse width) were NOT obtained for this pass. The "single-digit ns" claim
#     above is a CONSERVATIVE ESTIMATE typical of the family, NOT a datasheet
#     citation. It is used only to argue that the FSM's 40 ns dwarfs it -- which
#     the LIT PANEL corroborates far better than any number would. Replace the
#     estimate with the real tDST/tDHT and re-check the 30 ns residual.
#  2. Board trace delay is an ESTIMATE (~0.5 ns, short bank-66 traces to the
#     on-board panel). Not length-matched, not measured.
#  3. Actual slack needs report_timing on the CLCD pads post-implementation.
#     Expect large positive slack -- that is the point: a pass against a real
#     budget is evidence; the previous silence (no constraint at all) was not.
#  4. If firmware ever programs TIMING BELOW the shipped cs_setup=2/wr_lo=4/
#     wr_hi=4, the FSM margin shrinks and this skew budget may no longer be
#     dwarfed by it. The DUT-side accelerator's contract makes TIMING plain RW
#     (fpga/rp/nanosoc_exp/README.md sec.7), so this is reachable from software.
#     Treat the shipped values as the signoff assumption.
##############################################################################

##############################################################################
# USER microSD, SPI mode (usd_spi_0, D13) -- USD_CLK / USD_CMD / USD_DAT / USD_NCD
# ---------------------------------------------------------------------------
# FIRST-PASS, BOARD-SIGNOFF-PENDING, in the CLCD block's style above: the margin
# comes from the RTL, counted in shell_clk cycles, and these constraints stop the
# tool from eroding it. Read the caveats before trusting the numbers.
#
# WHAT THE RTL GUARANTEES (fpga/shell/ip/usd_spi/usd_spi.sv header):
#   SCK is a REGISTERED fabric signal (sck_q), not a clock: SCK = shell_clk /
#   (2*(DIV+1)), DIV runtime-programmable. The fastest setting firmware uses is
#   DIV=1: 25 MHz, 20 ns per half period. MOSI (USD_CMD) and CS# (USD_DAT[3])
#   change only on the shell_clk edge that launches SCK's FALLING edge; the
#   card samples MOSI on the RISING edge 20 ns later, and MOSI then holds 20 ns
#   more. CS# moves only between shifts, many SCK periods from any edge.
#   There is no clock to reference at the card, so -- as for the CLCD 8080 bus
#   -- the real requirement is a bound on pad-to-pad SKEW within the group.
#
# OUTPUTS: bound every driven USD pad's clock-to-pad delay into ONE 10 ns window,
# [0, 10] ns after the launching shell_clk edge. For an output port Vivado checks
#     setup:  arrival_max <= T - od_max        hold:  arrival_min >= -od_min
# so -max 0 / -min 0 is exactly that window, and pairwise SCK-to-MOSI/CS skew
# <= 10 ns leaves >= 10 ns of setup and of hold at the card at DIV=1, against
# the SD default-speed tISU = tIH = 5 ns. (The window covers the OBUFT T paths
# too: usd_spi's pad gate is a registered oe.)
#   NOT the -max 8 / -min -2 pair the CLCD block used until 2026-09-24: by the
#   two inequalities above that is the window [2, 2] ns -- zero wide, and
#   unmeetable by any fabric-launched pad (clock insertion alone is ~3 ns). The
#   D13 pad test measured it at -5.6 ns on all three USD outputs (report in the
#   D13 I-SHELL lane report); the CLCD block now uses this window too.
##############################################################################
# (Unconditional: D13 put these USD pads in every shell. The `if` they sat in
# until 2026-09-24 is not XDC -- [Designutils 20-1307] -- so they never applied.)
set usd_out [get_ports {USD_CLK USD_CMD {USD_DAT[3]}}]
set_output_delay -clock $clk_shell -max 0.0 $usd_out
set_output_delay -clock $clk_shell -min 0.0 $usd_out

# INPUT (MISO, USD_DAT[0]): a real, multicycle input path.
#   The card drives its next bit tODLY after SCK falls; usd_spi samples it LATE,
#   from the IOB register miso_q, on the shell_clk edge that launches the NEXT
#   falling edge -- 2*(DIV+1)-1 shell_clk after the launch. At DIV=1 that is 3
#   cycles (30 ns). So: reference the input to the shell_clk edge that launched
#   SCK's falling edge, fold the SCK round trip into the delay, and move the
#   setup check out to that third edge.
#     -max 24.0 = SCK clock-to-pad incl. clock insertion (<= 8.5; the D13 pad
#                 test measured 7.6) + trace (~0.5) + tODLY (14.0, SD default
#                 speed max) + trace (~0.5) + ~0.5 margin
#     -min  0.0 = the card may move MISO as soon as SCK falls (tOH, and SCK's own
#                 clock-to-pad, not relied on)
#   HOLD: the bit this launch replaces was captured ONE shell_clk BEFORE it (the
#   RTL samples on the cycle before the edge that launches the next SCK fall, at
#   every DIV). So the hold check belongs at launch - 1T: `-hold 3` (3 periods
#   earlier than the default hold edge of a 3-cycle setup, i.e. -1T). The usual
#   N-1 (`-hold 2`, edge 0) would demand the pad path outrun the capture clock's
#   insertion delay with a 0.0 min input delay -- a failure (-2.4 ns in the pad
#   test) of a race the RTL does not run.
#   The setup multiplier is DIV=1's; any larger DIV samples later and only gains.
#   DIV=0 (aclk/2) is outside SD SPI timing and is NOT covered -- firmware never
#   uses it.
set usd_miso [get_ports {USD_DAT[0]}]
set_input_delay -clock $clk_shell -max 24.0 $usd_miso
set_input_delay -clock $clk_shell -min  0.0 $usd_miso
set_multicycle_path 3 -setup -from $usd_miso
set_multicycle_path 3 -hold  -from $usd_miso
# ...and the -max 24.0 above assumes the sample register sits IN the IOB (a fixed
# pad->ILOGIC delay, no fabric route). usd_spi.sv asks for it with
# (* IOB = "TRUE" *) on miso_q, but the BD synthesises the block out of context,
# where there is no I/O buffer to pack into; this re-asserts it on the LINKED
# netlist (this file is implementation-only). Verify after place: report_io /
# get_property IOB on the cell. Not found => set_property's own CRITICAL WARNING.
set_property IOB TRUE [get_cells -hierarchical -filter {NAME =~ "*usd_spi_0*/miso_q_reg"}]

# --- Explicitly-argued exceptions (no edge to meet) --
# USD_NCD: a mechanical card-detect switch. usd_spi 2-FF synchronises it
# (ASYNC_REG) and debounces it for 10 ms -- the same class as USER_SW above.
set_false_path -from [get_ports -quiet USD_NCD]
# USD_DAT[1]/USD_DAT[2]: unused in SPI mode. shell_top ties their IOBUFs to
# T=1 (never driven) and reads nothing from them: structurally dead. A native
# 4-bit SD controller would DELETE these and give them real delays.
set_false_path -from [get_ports -quiet {USD_DAT[1] USD_DAT[2]}]
set_false_path -to   [get_ports -quiet {USD_DAT[1] USD_DAT[2]}]

##############################################################################
# USD caveats -- what a timing engineer must close at signoff
#  1. The SCK clock-to-pad (7.6 ns) is from a pad test (same RTL, pad glue and
#     XDC; an MMCM clock, not the shell's clk_wiz); the traces (~0.5 ns each
#     way) are ESTIMATES; tODLY 14 ns and tISU/tIH 5 ns are the SD Physical
#     Layer default-speed limits, not a particular card's. The slot traces are
#     short and not length-matched.
#  2. The pad test (routed) gave ~+2 ns on the outputs' [0,10] window and
#     several ns on MISO at the 3-cycle multiplier. If MISO fails in the static,
#     the fix is to keep firmware at DIV>=3 (12.5 MHz; a 7-cycle budget) and
#     raise the multiplier -- NOT a false path.
#  3. The highest SCK the board traces really support is unverified (handover
#     §7): board step B2 tries DIV=1 with a read-back.
##############################################################################

##############################################################################
# MicroBlaze console UART -- 115200 baud, fully asynchronous at the pad
# (axi_uartlite's 16x oversampling owns RX alignment). The earlier
# set_input_delay/set_output_delay pair copied from the legacy
# fpga_timing.xdc was budgeted against OSCCLK[1]'s 20 ns period; against
# this design's 10 ns shell clock it was unmeetable and modeled nothing
# real.
##############################################################################
set_false_path -from [get_ports MB_UART_RXD]
set_false_path -to   [get_ports MB_UART_TXD]
