"""tests/usd_spi/test_usd_spi.py

Verifies `fpga/shell/ip/usd_spi/usd_spi.sv` — USD @ 0x44A4_0000, the SPI-mode
master for the MPS3 USER microSD slot (docs/planning/HANDOVER_USD_OVERLAY_STORE.md
§4.1, §4.7; lane D13-L1).

What this proves, all from the AXI4-Lite side and the pads:
  1. Registers: ID, reset values, byte lanes, W1C, and that unmapped offsets
     read 0 and do not alias — AT THE WIDTH THE BD INSTANTIATES (CFG=bd:
     C_S_AXI_ADDR_WIDTH=32, driven as 0x44A4_0000 + offset) as well as at the
     RTL default (CFG=w12). See the Makefile.
  2. SCK = aclk / (2*(DIV+1)), measured on the pad, at the reset divider (124)
     and at DIV = 3 (plus 1 and 0).
  3. SPI mode 0, MSB first, 8- and 32-bit shifts; MOSI never moves while SCK is
     high; MISO sampled late enough for tODLY + board round trip at 25 MHz.
  4. CS on USD_DAT[3], active low.
  5. THE PAD GATE: every output-enable is 0 when EN=0, when no card is present,
     and CD_IGNORE overrides the card-detect term. (`make control-cd-gate-ignored`
     shows test_pads_hiz_without_card failing on a gate that ignores CD.)
  6. Card detect: 2-FF sync, debounce (a glitch of DEBOUNCE_CYCLES-1 is ignored,
     DEBOUNCE_CYCLES is accepted), CD_CHANGED sticky/W1C, CD_POL, CD_RAW.
  7. ABORT on a mid-transfer card removal (and EN clear); OVR on a DATA write
     while BUSY.
  8. End to end against sd_card_model.SdCardModel, driven ONLY through AXI:
     power-up clocks, CMD0/CMD8/ACMD41/CMD58 init, CMD9, CMD17 read,
     CMD24 write, read-back; CMD18/CMD12 and CMD25 multi-block; the card's
     CRC7 checks on CMD0/CMD8; an SDSC card reporting CCS=0.

The register offsets below are the lane contract, written out here on purpose,
and held equal to tests/common/regmap.py -- GENERATED by tools/gen_regmap.py from
shell_bd.tcl's `;# USD` line and this RTL's IDX_* lines -- at import, so the
bench, the RTL decode and every generated view (platform_regs.h, pyverify,
shell-regmap.md) cannot drift apart. The elaborated address width and debounce
are read back from the DUT, not restated.
"""
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "common"))
sys.path.insert(0, os.path.dirname(__file__))

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import (ClockCycles, FallingEdge, First, RisingEdge, Timer,
                             ValueChange)
from cocotb.utils import get_sim_time

from dut_presence import rtl_ready
from random_stim import RandomAxiMaster, random_axi_burst, seeded_rng
import regmap as _generated_regmap
from regmap import AxiLiteMaster
from sd_card_model import (BLOCK, DATA_RESP_ACCEPTED, R1_CRC_ERR, R1_IDLE,
                           SdCardModel, cmd_crc, crc16, default_block)

_RTL_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "fpga", "shell", "ip", "usd_spi")
NO_RTL = not rtl_ready(_RTL_DIR, ["usd_spi.sv"])

CLK_NS = 10                      # shell_clk: 100 MHz
USD_BASE = 0x44A4_0000           # the page the BD assigns (shell_bd.tcl ;# USD)

# --- the lane contract ----------------------------------------------------- #
USD_ID, USD_CTRL, USD_CLKDIV, USD_DATA, USD_STATUS = 0x00, 0x04, 0x08, 0x0C, 0x10
CTRL_EN, CTRL_CS, CTRL_WIDE, CTRL_CD_POL, CTRL_CD_IGNORE = 1, 2, 4, 8, 16
ST_BUSY, ST_CD_PRESENT, ST_CD_RAW = 1, 2, 4
ST_CD_CHANGED, ST_OVR, ST_ABORT = 8, 16, 32
ST_STICKY = ST_CD_CHANGED | ST_OVR | ST_ABORT
ID_VALUE = 0x5553_4431           # "USD1"
CLKDIV_RESET = 124               # 400 kHz at 100 MHz

# D13 landed in the BD: the generated map must say exactly what this bench drives.
_GEN = {n: getattr(_generated_regmap, "USD_" + n, None)
        for n in ("BASE", "ID", "CTRL", "CLKDIV", "DATA", "STATUS")}
assert _GEN == {"BASE": USD_BASE, "ID": USD_ID, "CTRL": USD_CTRL, "CLKDIV": USD_CLKDIV,
                "DATA": USD_DATA, "STATUS": USD_STATUS}, (
    f"tests/common/regmap.py (generated) disagrees with this bench's USD map: {_GEN}")


# =========================================================================== #
# Bench plumbing
# =========================================================================== #
def _param(dut, name):
    """An elaborated parameter, read back from the simulator."""
    try:
        return int(getattr(dut, name).value)
    except Exception as exc:     # pragma: no cover - simulator-dependent
        raise AssertionError(
            f"cannot read parameter {name} from the DUT ({exc}); this bench "
            "reads the elaborated value instead of restating it") from exc


class Bench:
    def __init__(self, dut):
        self.dut = dut
        self.clk = dut.s_axi_aclk
        self.aw = len(dut.s_axi_awaddr)
        assert self.aw in (12, 32), f"unexpected C_S_AXI_ADDR_WIDTH {self.aw}"
        # At 32 bits the interconnect hands the slave the FULL system address;
        # drive it exactly so (the width-32 decode escape, tests/csr_decode_width).
        self.base = USD_BASE if self.aw == 32 else 0
        self.deb = _param(dut, "DEBOUNCE_CYCLES")
        assert _param(dut, "C_S_AXI_ADDR_WIDTH") == self.aw
        self.axi = AxiLiteMaster.from_dut(dut)
        self.ctrl = 0
        self.div = CLKDIV_RESET
        self.cd_pol = 0
        dut._log.info(f"usd_spi elaborated at C_S_AXI_ADDR_WIDTH={self.aw} "
                      f"(base 0x{self.base:08X}), DEBOUNCE_CYCLES={self.deb}")

    # -- register access ------------------------------------------------- #
    async def wr(self, off, val, strb=0xF):
        resp = await self.axi.write(self.base + off, val, strb)
        assert resp == 0, f"BRESP {resp} writing 0x{off:02X}"

    async def rd(self, off):
        data, resp = await self.axi.read(self.base + off)
        assert resp == 0, f"RRESP {resp} reading 0x{off:02X}"
        return data

    async def set_ctrl(self, en=None, cs=None, wide=None, cd_pol=None, cd_ignore=None):
        bits = {CTRL_EN: en, CTRL_CS: cs, CTRL_WIDE: wide,
                CTRL_CD_POL: cd_pol, CTRL_CD_IGNORE: cd_ignore}
        for bit, val in bits.items():
            if val is not None:
                self.ctrl = (self.ctrl | bit) if val else (self.ctrl & ~bit)
        if cd_pol is not None:
            self.cd_pol = 1 if cd_pol else 0
        await self.wr(USD_CTRL, self.ctrl)

    async def set_div(self, div):
        self.div = div
        await self.wr(USD_CLKDIV, div)

    async def status(self):
        return await self.rd(USD_STATUS)

    async def clear_sticky(self):
        await self.wr(USD_STATUS, ST_STICKY)

    async def cycles(self, n):
        """Wait n aclk cycles without a Python trigger per cycle."""
        await Timer(n * CLK_NS, unit="ns")

    # -- card detect ------------------------------------------------------- #
    def ncd_level(self, present):
        """USD_NCD pin level that means `present` under the current CD_POL."""
        return (1 if present else 0) if self.cd_pol else (0 if present else 1)

    async def insert_card(self):
        self.dut.usd_ncd_i.value = self.ncd_level(True)
        await self.cycles(self.deb + 6)
        assert await self.status() & ST_CD_PRESENT, "card inserted but CD_PRESENT=0"

    async def remove_card(self):
        self.dut.usd_ncd_i.value = self.ncd_level(False)

    # -- shifting --------------------------------------------------------- #
    def xfer_cycles(self, bits):
        return bits * 2 * (self.div + 1)

    async def wait_idle(self, bits):
        await self.cycles(self.xfer_cycles(bits))
        for _ in range(64):
            st = await self.status()
            if not st & ST_BUSY:
                return st
        raise AssertionError("BUSY never cleared")

    async def xfer(self, value, wide=False):
        """One shift through DATA, exactly as firmware does it. Assumes CTRL.WIDE
        already matches `wide`."""
        await self.wr(USD_DATA, value)
        st = await self.wait_idle(32 if wide else 8)
        assert not st & (ST_OVR | ST_ABORT), f"transfer flagged STATUS=0x{st:02X}"
        return await self.rd(USD_DATA)


async def bring_up(dut, card_present=False):
    # impl="gpi": the clock toggles inside the simulator's GPI layer, not in a
    # Python coroutine. cocotb only picks it by itself for simulators that set
    # COCOTB_TRUST_INERTIAL_WRITES; under VCS the Python clock costs ~100 us per
    # aclk, and the shipped 10 ms debounce is 1e6 of them. Nothing in this bench
    # writes a signal in the same timestep as the clock edge it depends on (the
    # BFM and the card-detect pulses write after an edge or mid-cycle), so the
    # ordering caveat behind that default does not apply.
    cocotb.start_soon(Clock(dut.s_axi_aclk, CLK_NS, unit="ns", impl="gpi").start())
    for name in ("awaddr", "awprot", "awvalid", "wdata", "wstrb", "wvalid",
                 "bready", "araddr", "arprot", "arvalid", "rready"):
        getattr(dut, f"s_axi_{name}").value = 0
    dut.usd_dat0_i.value = 1                         # pulled up, nothing driving
    dut.usd_ncd_i.value = 0 if card_present else 1   # reset polarity: low = card
    dut.s_axi_aresetn.value = 0
    await ClockCycles(dut.s_axi_aclk, 5)
    dut.s_axi_aresetn.value = 1
    await RisingEdge(dut.s_axi_aclk)
    return Bench(dut)


def oes(dut):
    return (int(dut.usd_clk_oe.value), int(dut.usd_cmd_oe.value),
            int(dut.usd_dat3_oe.value))


class PadWatch:
    """Background monitor: records every moment ANY output-enable is 1, and
    every SCK edge (driven or not). Event-driven (value changes, not a per-cycle
    poll), so it costs nothing over a 10 ms debounce window and still sees a
    one-cycle glitch. Runs concurrently with the AXI traffic, so the window
    includes the writes themselves."""

    def __init__(self, dut):
        self.dut = dut
        self.driven = []               # [(t_ns, (clk_oe, cmd_oe, dat3_oe))]
        self.sck_edges = 0
        self._tasks = []

    @property
    def first_driven(self):
        return self.driven[0] if self.driven else None

    def start(self):
        self._note()
        self._tasks = [cocotb.start_soon(self._oe()), cocotb.start_soon(self._sck())]
        return self

    def stop(self):
        for t in self._tasks:
            t.cancel()

    def _note(self):
        o = oes(self.dut)
        if any(o):
            self.driven.append((get_sim_time(unit="ns"), o))

    async def _oe(self):
        d = self.dut
        while True:
            await First(ValueChange(d.usd_clk_oe), ValueChange(d.usd_cmd_oe),
                        ValueChange(d.usd_dat3_oe))
            self._note()

    async def _sck(self):
        while True:
            await ValueChange(self.dut.usd_clk_o)
            self.sck_edges += 1


class RawSpiSlave:
    """A plain SPI mode-0 slave at the pads (no SD protocol): records MOSI and
    the time of every SCK edge, and shifts `reply` out MSB first, moving MISO
    `tod_ns` after each falling edge. Ignores CS, so it sees every clock."""

    def __init__(self, dut, reply: int, nbits: int, tod_ns: float = 2.0):
        self.dut = dut
        self.bits = [(reply >> (nbits - 1 - i)) & 1 for i in range(nbits)]
        self.tod_ns = tod_ns
        self.mosi = []
        self.rise_t = []
        self.fall_t = []
        self.mosi_change_t = []
        self._i = 0
        dut.usd_dat0_i.value = self.bits[0]
        self._tasks = [cocotb.start_soon(self._rise()), cocotb.start_soon(self._fall()),
                       cocotb.start_soon(self._mosi_watch())]

    def stop(self):
        for t in self._tasks:
            t.cancel()
        self.dut.usd_dat0_i.value = 1

    async def _rise(self):
        while True:
            await RisingEdge(self.dut.usd_clk_o)
            self.rise_t.append(get_sim_time(unit="ns"))
            self.mosi.append(int(self.dut.usd_cmd_o.value))

    async def _fall(self):
        while True:
            await FallingEdge(self.dut.usd_clk_o)
            self.fall_t.append(get_sim_time(unit="ns"))
            self._i += 1
            if self._i < len(self.bits):
                bit = self.bits[self._i]
                if self.tod_ns:
                    await Timer(self.tod_ns, unit="ns")
                self.dut.usd_dat0_i.value = bit

    async def _mosi_watch(self):
        while True:
            await ValueChange(self.dut.usd_cmd_o)
            self.mosi_change_t.append(get_sim_time(unit="ns"))

    def mosi_word(self):
        v = 0
        for bit in self.mosi:
            v = (v << 1) | bit
        return v


# =========================================================================== #
# 1. Registers
# =========================================================================== #
@cocotb.test(skip=NO_RTL)
async def test_reset_values_and_id(dut):
    """ID, and every register's reset value. With no card (USD_NCD high) the
    status is exactly CD_RAW; every pad is high-Z from reset."""
    b = await bring_up(dut)
    assert await b.rd(USD_ID) == ID_VALUE
    assert await b.rd(USD_CTRL) == 0
    assert await b.rd(USD_CLKDIV) == CLKDIV_RESET
    assert await b.rd(USD_DATA) == 0
    assert await b.status() == ST_CD_RAW, "reset STATUS must be CD_RAW only (pin high, no card)"
    assert oes(dut) == (0, 0, 0), "pads must be high-Z out of reset"
    assert int(dut.usd_clk_o.value) == 0 and int(dut.usd_cmd_o.value) == 1


@cocotb.test(skip=NO_RTL)
async def test_id_and_ctrl_are_read_only_where_they_should_be(dut):
    """ID is RO; CTRL keeps only its five bits; CLKDIV only [15:0]; STATUS
    ignores writes to its RO bits."""
    b = await bring_up(dut)
    await b.wr(USD_ID, 0)
    assert await b.rd(USD_ID) == ID_VALUE
    await b.wr(USD_CTRL, 0xFFFF_FFE0)                   # no defined bit set
    assert await b.rd(USD_CTRL) == 0
    await b.wr(USD_CTRL, 0xFFFF_FFFF)
    assert await b.rd(USD_CTRL) == 0x1F
    await b.wr(USD_CTRL, 0)
    await b.clear_sticky()          # CD_IGNORE toggled CD_PRESENT twice
    await b.wr(USD_CLKDIV, 0xABCD_1234)
    assert await b.rd(USD_CLKDIV) == 0x1234
    await b.wr(USD_STATUS, ST_BUSY | ST_CD_PRESENT | ST_CD_RAW)
    assert await b.status() == ST_CD_RAW


@cocotb.test(skip=NO_RTL)
async def test_unmapped_offsets_read_zero_and_do_not_alias(dut):
    """Only 0x00..0x10 respond. A write anywhere else in the 64 KiB page must
    not land on a real register (the page-wide decode; BASE+0x1000 must not
    alias offset 0, and 0x14/0x2C must not alias CTRL/DATA). At CFG=bd this
    runs at C_S_AXI_ADDR_WIDTH=32 with the full 0x44A4_xxxx address."""
    b = await bring_up(dut)
    top = (1 << min(b.aw, 16)) - 4
    unmapped = [0x14, 0x18, 0x20, 0x24, 0x2C, 0x100, 0x1004, 0x100C, top]
    unmapped = [o for o in unmapped if o <= top]
    for off in unmapped:
        assert await b.rd(off) == 0, f"unmapped 0x{off:04X} read non-zero"
    for off in unmapped:
        await b.wr(off, 0xFFFF_FFFF)
    assert await b.rd(USD_CTRL) == 0, "an unmapped write aliased onto CTRL"
    assert await b.rd(USD_CLKDIV) == CLKDIV_RESET, "an unmapped write aliased onto CLKDIV"
    st = await b.status()
    assert not st & (ST_BUSY | ST_OVR | ST_ABORT), (
        f"an unmapped write aliased onto DATA (STATUS=0x{st:02X})")
    assert oes(dut) == (0, 0, 0)


@cocotb.test(skip=NO_RTL)
async def test_wstrb_byte_lanes(dut):
    """CLKDIV honours lanes 0/1 independently; a strobe-less CTRL write is inert."""
    b = await bring_up(dut)
    await b.wr(USD_CLKDIV, 0x0000_5A5A, strb=0b0001)
    assert await b.rd(USD_CLKDIV) == 0x005A
    await b.wr(USD_CLKDIV, 0x0000_A5FF, strb=0b0010)
    assert await b.rd(USD_CLKDIV) == 0xA55A
    await b.wr(USD_CLKDIV, 0xFFFF_FFFF, strb=0b1100)
    assert await b.rd(USD_CLKDIV) == 0xA55A
    await b.wr(USD_CTRL, 0x1F, strb=0b0000)
    assert await b.rd(USD_CTRL) == 0


@cocotb.test(skip=NO_RTL)
async def test_random_aw_en_corners(dut):
    """Constrained-random AXI4-Lite handshake corners (AW/W order, zero gap,
    read-during-write, random WSTRB) over CTRL/CLKDIV/STATUS; the bound
    protocol SVA checks every beat. The block must still read back sane."""
    b = await bring_up(dut)
    rng, _seed = seeded_rng(dut, "usd_spi")
    m = RandomAxiMaster.from_dut(dut)
    w = [b.base + o for o in (USD_CTRL, USD_CLKDIV, USD_STATUS)]
    r = [b.base + o for o in (USD_ID, USD_CTRL, USD_CLKDIV, USD_DATA, USD_STATUS)]
    tally = await random_axi_burst(m, rng, w, r, n=48)
    dut._log.info(f"[usd_spi random] {tally}")
    assert await b.rd(USD_ID) == ID_VALUE
    assert (await b.rd(USD_CTRL)) & ~0x1F == 0


# =========================================================================== #
# 2-4. Divider, shifter, CS
# =========================================================================== #
async def _measure_sck(b, div, nbits, reply=0):
    """Run one shift at `div` with the pads forced on (CD_IGNORE) and a raw
    slave on the pads; return the slave's recording."""
    await b.set_div(div)
    await b.set_ctrl(en=1, cd_ignore=1, wide=(nbits == 32))
    s = RawSpiSlave(b.dut, reply, nbits)
    await b.xfer(0xA5A5_A5A5, wide=(nbits == 32))
    s.stop()
    return s


def _check_period(s, div, nbits):
    half = (div + 1) * CLK_NS
    assert len(s.rise_t) == nbits and len(s.fall_t) == nbits, (
        f"expected {nbits} SCK rising/falling edges, saw {len(s.rise_t)}/{len(s.fall_t)}")
    periods = {round(t1 - t0, 3) for t0, t1 in zip(s.rise_t, s.rise_t[1:])}
    assert periods == {2 * half}, f"SCK period(s) {periods} ns, expected {2 * half} ns"
    highs = {round(f - r, 3) for r, f in zip(s.rise_t, s.fall_t)}
    assert highs == {half}, f"SCK high time(s) {highs} ns, expected {half} ns"
    lows = {round(r - f, 3) for f, r in zip(s.fall_t, s.rise_t[1:])}
    assert not lows or lows == {half}, f"SCK low time(s) {lows} ns, expected {half} ns"


@cocotb.test(skip=NO_RTL)
async def test_sck_period_at_reset_divider(dut):
    """SCK = aclk / (2*(124+1)) = 400 kHz: 2500 ns period, 50 % duty."""
    b = await bring_up(dut)
    s = await _measure_sck(b, CLKDIV_RESET, 8)
    _check_period(s, CLKDIV_RESET, 8)
    assert int(dut.usd_clk_o.value) == 0, "SCK must idle low"


@cocotb.test(skip=NO_RTL)
async def test_sck_period_at_div3_and_faster(dut):
    """DIV=3 -> 12.5 MHz (80 ns), the firmware's post-init speed; also DIV=1
    (25 MHz) and DIV=0 (aclk/2), over a 32-bit shift."""
    b = await bring_up(dut)
    for div in (3, 1, 0):
        s = await _measure_sck(b, div, 32)
        _check_period(s, div, 32)


@cocotb.test(skip=NO_RTL)
async def test_shift_8bit_mode0_msb_first(dut):
    """WIDE=0: only wdata[7:0] goes out, MSB first; MOSI changes only with SCK
    low (on the falling edge, never while SCK is high); RX is zero-extended;
    SCK idles low and MOSI idles high afterwards."""
    b = await bring_up(dut)
    await b.set_div(3)
    await b.set_ctrl(en=1, cd_ignore=1, wide=0)
    s = RawSpiSlave(dut, 0xC3, 8)
    rx = await b.xfer(0xABCD_EF5A)
    s.stop()
    assert s.mosi_word() == 0x5A and len(s.mosi) == 8, f"MOSI {s.mosi}"
    assert rx == 0x0000_00C3, f"RX 0x{rx:08X}"
    for r, f in zip(s.rise_t, s.fall_t):
        inside = [t for t in s.mosi_change_t if r <= t < f]
        assert not inside, f"MOSI moved at {inside} while SCK was high ({r}..{f} ns)"
    assert int(dut.usd_clk_o.value) == 0 and int(dut.usd_cmd_o.value) == 1


@cocotb.test(skip=NO_RTL)
async def test_shift_32bit_mode0_msb_first(dut):
    """WIDE=1: the whole word, MSB first, and the whole RX word back."""
    b = await bring_up(dut)
    await b.set_div(3)
    await b.set_ctrl(en=1, cd_ignore=1, wide=1)
    for tx, reply in ((0xDEAD_BEEF, 0x1357_9BDF), (0x0000_0001, 0x8000_0000)):
        s = RawSpiSlave(dut, reply, 32)
        rx = await b.xfer(tx, wide=True)
        s.stop()
        assert len(s.mosi) == 32 and s.mosi_word() == tx, f"MOSI 0x{s.mosi_word():08X}"
        assert rx == reply, f"RX 0x{rx:08X}, expected 0x{reply:08X}"


@cocotb.test(skip=NO_RTL)
async def test_data_read_holds_last_rx_while_busy(dut):
    """DATA reads the LAST COMPLETED word, including while the next shift runs."""
    b = await bring_up(dut)
    await b.set_div(7)
    await b.set_ctrl(en=1, cd_ignore=1)
    s = RawSpiSlave(dut, 0x96, 8)
    assert await b.xfer(0x00) == 0x96
    s.stop()
    s = RawSpiSlave(dut, 0x3C, 8)
    await b.wr(USD_DATA, 0xFF)
    assert await b.status() & ST_BUSY
    assert await b.rd(USD_DATA) == 0x96, "DATA changed before the shift completed"
    await b.wait_idle(8)
    assert await b.rd(USD_DATA) == 0x3C
    s.stop()


@cocotb.test(skip=NO_RTL)
async def test_busy_visible_on_first_status_read_after_write(dut):
    """Firmware contract (lane L2): the FIRST STATUS read issued after a DATA
    write's B-response already sees BUSY=1 -- there is no window in which a
    poll straight after the write reads BUSY=0 before the shift has started.
    (BUSY is set on the same aclk edge that accepts the write, and BVALID rises
    on that edge too.) Checked at the tightest case, DIV=0 with an 8-bit shift
    (16 aclk in all), and at the reset divider, in both widths."""
    b = await bring_up(dut)
    await b.set_ctrl(en=1, cd_ignore=1)
    for div in (0, CLKDIV_RESET):
        await b.set_div(div)
        for wide in (0, 1):
            await b.set_ctrl(wide=wide)
            await b.wr(USD_DATA, 0xA5A5_A5A5)
            st = await b.status()                    # the very next transaction
            assert st & ST_BUSY, (
                f"first STATUS read after the DATA write saw BUSY=0 "
                f"(DIV={div}, WIDE={wide}, STATUS=0x{st:02X})")
            st = await b.wait_idle(32 if wide else 8)
            assert not st & (ST_OVR | ST_ABORT), f"0x{st:02X}"


@cocotb.test(skip=NO_RTL)
async def test_miso_late_sample_margin(dut):
    """At DIV=1 (25 MHz, 20 ns half period) a card whose MISO moves 25 ns after
    each falling edge (tODLY 14 ns + ~11 ns of pads and traces) still reads
    back correctly: the block samples one aclk before the NEXT falling edge,
    not on the rising edge (see usd_spi.sv's header)."""
    b = await bring_up(dut)
    await b.set_div(1)
    await b.set_ctrl(en=1, cd_ignore=1, wide=1)
    rng = random.Random(0x5D)
    for _ in range(4):
        reply = rng.getrandbits(32)
        s = RawSpiSlave(dut, reply, 32, tod_ns=25.0)
        rx = await b.xfer(rng.getrandbits(32), wide=True)
        s.stop()
        assert rx == reply, f"RX 0x{rx:08X}, expected 0x{reply:08X} (tODLY 25 ns @ 25 MHz)"


@cocotb.test(skip=NO_RTL)
async def test_cs_drives_dat3_low(dut):
    """CTRL.CS=1 drives USD_DAT[3] low (active-low CS); CS=0 drives it high."""
    b = await bring_up(dut)
    await b.set_ctrl(en=1, cd_ignore=1, cs=1)
    await ClockCycles(dut.s_axi_aclk, 2)
    assert int(dut.usd_dat3_oe.value) == 1 and int(dut.usd_dat3_o.value) == 0
    await b.set_ctrl(cs=0)
    await ClockCycles(dut.s_axi_aclk, 2)
    assert int(dut.usd_dat3_oe.value) == 1 and int(dut.usd_dat3_o.value) == 1
    assert await b.rd(USD_CTRL) == CTRL_EN | CTRL_CD_IGNORE


# =========================================================================== #
# 5. The pad gate
# =========================================================================== #
@cocotb.test(skip=NO_RTL)
async def test_pads_hiz_when_en_clear(dut):
    """Card present, EN=0: every pad stays high-Z whatever else firmware writes
    (CS, CD_IGNORE, a DATA write). The DATA write starts nothing: no SCK edge,
    BUSY never set, and STATUS.ABORT records the refused transfer."""
    b = await bring_up(dut)
    await b.insert_card()
    w = PadWatch(dut).start()
    await b.set_ctrl(en=0, cs=1, cd_ignore=1)
    await b.wr(USD_DATA, 0x00)
    st = await b.status()
    await b.cycles(200)
    w.stop()
    assert not w.driven, f"a pad was driven with EN=0: {w.first_driven}"
    assert w.sck_edges == 0, "SCK toggled with EN=0"
    assert not st & ST_BUSY
    assert st & ST_ABORT, "a DATA write refused by the pad gate must set ABORT"


@cocotb.test(skip=NO_RTL)
async def test_pads_hiz_without_card(dut):
    """THE HARDWARE SAFETY TEST. No card (USD_NCD high), CD_IGNORE=0: EN=1, CS=1
    and a DATA write must still leave every pad — SCK included — high-Z, so a
    firmware bug cannot drive an empty socket. `make control-cd-gate-ignored`
    must turn this red."""
    b = await bring_up(dut, card_present=False)
    w = PadWatch(dut).start()
    await b.set_ctrl(en=1, cs=1, wide=1)
    await b.wr(USD_DATA, 0x0000_0000)
    await b.cycles(b.deb + 400)
    st = await b.status()
    w.stop()
    assert not w.driven, (
        f"a pad was driven with NO CARD present: first at {w.first_driven} "
        f"(t_ns, (clk_oe, cmd_oe, dat3_oe)), {len(w.driven)} OE change(s) in all")
    assert w.sck_edges == 0, f"SCK toggled {w.sck_edges} times with no card"
    assert not st & (ST_BUSY | ST_CD_PRESENT)
    assert st & ST_ABORT


@cocotb.test(skip=NO_RTL)
async def test_cd_ignore_forces_present_and_enables_pads(dut):
    """No card, CD_IGNORE=1: CD_PRESENT reads 1 (forced; a change, so CD_CHANGED
    sets), the pads drive and a shift runs. Clearing CD_IGNORE floats them."""
    b = await bring_up(dut, card_present=False)
    await b.set_ctrl(en=1, cd_ignore=1)
    await ClockCycles(dut.s_axi_aclk, 2)
    assert oes(dut) == (1, 1, 1)
    st = await b.status()
    assert st & ST_CD_PRESENT and st & ST_CD_CHANGED and st & ST_CD_RAW
    s = RawSpiSlave(dut, 0x81, 8)
    assert await b.xfer(0x42) == 0x81
    s.stop()
    await b.set_ctrl(cd_ignore=0)
    await ClockCycles(dut.s_axi_aclk, 2)
    assert oes(dut) == (0, 0, 0)
    assert not await b.status() & ST_CD_PRESENT


# =========================================================================== #
# 6. Card detect
# =========================================================================== #
async def _pulse_ncd(b, level, ncycles):
    """Drive USD_NCD to `level` for exactly `ncycles` aclk samples. The pin
    moves MID-cycle (half a period after an edge) so no edge can race the
    write and the sample count is exact."""
    await RisingEdge(b.clk)
    await Timer(CLK_NS // 2, unit="ns")
    b.dut.usd_ncd_i.value = level
    await Timer(ncycles * CLK_NS, unit="ns")
    b.dut.usd_ncd_i.value = 1 - level


@cocotb.test(skip=NO_RTL)
async def test_cd_debounce_glitch_ignored_then_accepted(dut):
    """A card-detect glitch of DEBOUNCE_CYCLES-1 aclk is invisible (CD_RAW sees
    it, CD_PRESENT and CD_CHANGED do not); a level held DEBOUNCE_CYCLES is a
    card. CD_CHANGED is sticky and W1C, and removal sets it again."""
    b = await bring_up(dut, card_present=False)
    # CD_RAW follows the pin (2-FF sync, no debounce): read it DURING the glitch.
    glitch = cocotb.start_soon(_pulse_ncd(b, 0, b.deb - 1))
    await b.cycles(6)
    st = await b.status()
    assert not st & ST_CD_RAW, f"CD_RAW did not follow the pin (STATUS=0x{st:02X})"
    assert not st & (ST_CD_PRESENT | ST_CD_CHANGED)
    await glitch
    await b.cycles(8)
    st = await b.status()
    assert not st & (ST_CD_PRESENT | ST_CD_CHANGED), (
        f"a {b.deb - 1}-cycle glitch got through the debounce (STATUS=0x{st:02X})")

    # Held: accepted.
    dut.usd_ncd_i.value = 0
    await b.cycles(b.deb + 4)
    st = await b.status()
    assert st & ST_CD_PRESENT and st & ST_CD_CHANGED and not st & ST_CD_RAW, f"0x{st:02X}"

    # W1C: writing 0 does nothing, writing another sticky bit does nothing.
    await b.wr(USD_STATUS, 0)
    await b.wr(USD_STATUS, ST_OVR | ST_ABORT)
    assert await b.status() & ST_CD_CHANGED
    await b.wr(USD_STATUS, ST_CD_CHANGED)
    st = await b.status()
    assert not st & ST_CD_CHANGED and st & ST_CD_PRESENT

    # A removal glitch is ignored too; a real removal sets CD_CHANGED again.
    await _pulse_ncd(b, 1, b.deb - 1)
    dut.usd_ncd_i.value = 0
    await b.cycles(8)
    st = await b.status()
    assert st & ST_CD_PRESENT and not st & ST_CD_CHANGED, f"0x{st:02X}"
    dut.usd_ncd_i.value = 1
    await b.cycles(b.deb + 4)
    st = await b.status()
    assert not st & ST_CD_PRESENT and st & ST_CD_CHANGED and st & ST_CD_RAW


@cocotb.test(skip=NO_RTL)
async def test_cd_boundary_is_exactly_debounce_cycles(dut):
    """The accept point is DEBOUNCE_CYCLES consecutive samples, not one fewer:
    DEBOUNCE_CYCLES-1 is rejected (above), DEBOUNCE_CYCLES is accepted even as a
    pulse that ends right after."""
    b = await bring_up(dut, card_present=False)
    await _pulse_ncd(b, 0, b.deb)
    await b.cycles(8)
    st = await b.status()
    assert st & ST_CD_CHANGED, f"a {b.deb}-cycle level was not accepted (0x{st:02X})"


@cocotb.test(skip=NO_RTL)
async def test_cd_pol_inverts_present_not_raw(dut):
    """CD_POL=1: USD_NCD HIGH means present. The polarity applies after the
    debounce (immediate) and is a change of CD_PRESENT; CD_RAW is the pin."""
    b = await bring_up(dut, card_present=False)          # pin high
    st = await b.status()
    assert st & ST_CD_RAW and not st & ST_CD_PRESENT
    await b.set_ctrl(cd_pol=1)
    st = await b.status()
    assert st & ST_CD_PRESENT and st & ST_CD_CHANGED and st & ST_CD_RAW, f"0x{st:02X}"
    await b.clear_sticky()
    # Pin low under CD_POL=1 = removed, after the debounce.
    await b.remove_card()
    await b.cycles(b.deb + 4)
    st = await b.status()
    assert not st & ST_CD_PRESENT and not st & ST_CD_RAW and st & ST_CD_CHANGED
    # ...and the pad gate follows the polarity-applied value.
    await b.set_ctrl(en=1)
    await ClockCycles(dut.s_axi_aclk, 2)
    assert oes(dut) == (0, 0, 0)
    await b.insert_card()                                   # pin high again
    await ClockCycles(dut.s_axi_aclk, 2)
    assert oes(dut) == (1, 1, 1)


# =========================================================================== #
# 7. ABORT and OVR
# =========================================================================== #
@cocotb.test(skip=NO_RTL)
async def test_abort_on_card_removal_mid_transfer(dut):
    """A card pulled mid-shift: once the removal is debounced the pads float,
    the shift stops dead (BUSY clears, no more SCK edges), ABORT and CD_CHANGED
    set, and DATA still holds the last COMPLETED word."""
    b = await bring_up(dut)
    await b.insert_card()
    await b.clear_sticky()
    # A 32-bit shift that lasts well over the debounce time.
    div = min(0xFFFF, max(3, -(-4 * b.deb // 64)))
    await b.set_div(div)
    await b.set_ctrl(en=1, cs=1, wide=1)
    s = RawSpiSlave(dut, 0xFFFF_FFFF, 32)
    await b.wr(USD_DATA, 0x1234_5678)
    await b.cycles(3 * 2 * (div + 1))                 # a few bits in
    assert await b.status() & ST_BUSY
    await b.remove_card()
    await b.cycles(b.deb + 8)
    st = await b.status()
    edges = len(s.rise_t)
    assert not st & ST_BUSY, "BUSY still set after the card was pulled"
    assert st & ST_ABORT and st & ST_CD_CHANGED and not st & ST_CD_PRESENT, f"0x{st:02X}"
    assert oes(dut) == (0, 0, 0)
    assert 0 < edges < 32, f"{edges} SCK edges: the shift was not interrupted"
    await b.cycles(4 * 2 * (div + 1))
    assert len(s.rise_t) == edges, "SCK kept running after ABORT"
    s.stop()
    assert await b.rd(USD_DATA) == 0, "a partial word reached DATA"
    await b.wr(USD_STATUS, ST_ABORT)
    assert not await b.status() & ST_ABORT


@cocotb.test(skip=NO_RTL)
async def test_abort_on_en_clear_mid_transfer(dut):
    """Clearing CTRL.EN mid-shift aborts it at once."""
    b = await bring_up(dut)
    await b.set_div(15)
    await b.set_ctrl(en=1, cd_ignore=1)
    await b.wr(USD_DATA, 0x00)
    await b.cycles(2 * 2 * 16)
    await b.set_ctrl(en=0)
    st = await b.status()
    assert not st & ST_BUSY and st & ST_ABORT, f"0x{st:02X}"
    await ClockCycles(dut.s_axi_aclk, 2)
    assert oes(dut) == (0, 0, 0)
    assert int(dut.usd_clk_o.value) == 0


@cocotb.test(skip=NO_RTL)
async def test_ovr_on_data_write_while_busy(dut):
    """A DATA write while BUSY is ignored (the running shift is untouched: the
    same 8 bits, 8 clocks) and sets OVR, which is sticky and W1C."""
    b = await bring_up(dut)
    await b.set_div(3)
    await b.set_ctrl(en=1, cd_ignore=1)
    s = RawSpiSlave(dut, 0x00, 8)
    await b.wr(USD_DATA, 0xA5)
    await b.wr(USD_DATA, 0x0F)                        # while busy
    st = await b.wait_idle(8)
    s.stop()
    assert st & ST_OVR and not st & ST_ABORT, f"0x{st:02X}"
    assert len(s.mosi) == 8 and s.mosi_word() == 0xA5, f"MOSI {s.mosi}"
    await b.wr(USD_STATUS, ST_OVR)
    assert not await b.status() & ST_OVR


# =========================================================================== #
# 8. End to end: an SD card, driven only through AXI
# =========================================================================== #
class SdHost:
    """What lane L2's firmware driver does, in Python, through the registers
    only: every byte is a DATA write, a STATUS poll and a DATA read."""

    def __init__(self, b: Bench):
        self.b = b

    async def byte(self, v=0xFF):
        return await self.b.xfer(v)

    async def bytes_wide(self, data: bytes = None, n: int = 0):
        """512-byte payloads in WIDE (32-bit) mode, MSB first = wire order."""
        await self.b.set_ctrl(wide=1)
        out = bytearray()
        words = (len(data) if data is not None else n) // 4
        for i in range(words):
            w = int.from_bytes(data[4 * i:4 * i + 4], "big") if data is not None else 0xFFFF_FFFF
            out += (await self.b.xfer(w, wide=True)).to_bytes(4, "big")
        await self.b.set_ctrl(wide=0)
        return bytes(out)

    async def send_cmd(self, index, arg, crc=None):
        await self.byte(0xFF)
        frame = [0x40 | index] + list(arg.to_bytes(4, "big"))
        frame.append(cmd_crc(index, arg) if crc is None else crc)
        for x in frame:
            await self.byte(x)

    async def r1(self, polls=9):
        r = 0xFF
        for _ in range(polls):
            r = await self.byte()
            if not r & 0x80:
                break
        return r

    async def cmd(self, index, arg, extra=0, crc=None):
        await self.send_cmd(index, arg, crc)
        r = await self.r1()
        tail = [await self.byte() for _ in range(extra)] if not r & 0x80 else []
        return r, tail

    async def token(self, polls=64):
        t = 0xFF
        for _ in range(polls):
            t = await self.byte()
            if t != 0xFF:
                break
        return t

    async def wait_not_busy(self):
        n = 0
        while await self.byte() != 0xFF:
            n += 1
            assert n < 200, "card busy forever"
        return n

    async def deselect(self):
        await self.b.set_ctrl(cs=0)
        await self.byte()

    async def power_up_clocks(self):
        await self.b.set_ctrl(en=1, cs=0, wide=0)
        for _ in range(10):                            # 80 clocks, CS high
            await self.byte()

    async def init(self):
        b = self.b
        await b.set_div(CLKDIV_RESET)                  # 400 kHz for init
        await self.power_up_clocks()
        await b.set_ctrl(cs=1)
        r, _ = await self.cmd(0, 0)
        assert r == R1_IDLE, f"CMD0 R1 0x{r:02X}"
        r, r7 = await self.cmd(8, 0x1AA, extra=4)
        assert r == R1_IDLE and r7 == [0x00, 0x00, 0x01, 0xAA], f"CMD8 {r:#x} {r7}"
        for _ in range(20):
            r, _ = await self.cmd(55, 0)
            assert r in (0x00, 0x01), f"CMD55 R1 0x{r:02X}"
            r, _ = await self.cmd(41, 0x4000_0000)     # HCS
            if r == 0x00:
                break
        else:
            raise AssertionError("ACMD41 never left idle")
        r, ocr = await self.cmd(58, 0, extra=4)
        assert r == 0x00, f"CMD58 R1 0x{r:02X}"
        await self.deselect()
        await b.set_div(3)                             # 12.5 MHz from here on
        return int.from_bytes(bytes(ocr), "big")

    async def read_block(self, lba):
        await self.b.set_ctrl(cs=1)
        r, _ = await self.cmd(17, lba)
        assert r == 0x00, f"CMD17 R1 0x{r:02X}"
        assert await self.token() == 0xFE, "no read data token"
        data = await self.bytes_wide(n=BLOCK)
        crc = (await self.byte() << 8) | await self.byte()
        await self.deselect()
        assert crc == crc16(data), f"read CRC16 0x{crc:04X} != 0x{crc16(data):04X}"
        return data

    async def write_block(self, lba, data):
        await self.b.set_ctrl(cs=1)
        r, _ = await self.cmd(24, lba)
        assert r == 0x00, f"CMD24 R1 0x{r:02X}"
        await self.byte(0xFF)                           # Nwr
        await self.byte(0xFE)
        await self.bytes_wide(data)
        await self.byte(0xFF)                           # CRC16: off in SPI mode
        await self.byte(0xFF)
        resp = await self.byte() & 0x1F
        assert resp == DATA_RESP_ACCEPTED, f"data response 0x{resp:02X}"
        busy = await self.wait_not_busy()
        await self.deselect()
        return busy


def _card(dut, **kw):
    return SdCardModel(dut, **kw).start()


async def _pads_on_for_protocol_test(b):
    """For the SD-protocol tests that are NOT about card detect: enable the pads
    through CD_IGNORE instead of a debounced insertion. test_sd_end_to_end does
    the physical insertion; the other four would each spend a 10 ms debounce
    (1e6 aclk) on it at CFG=bd and prove nothing more."""
    await b.set_ctrl(en=1, cd_ignore=1)


@cocotb.test(skip=NO_RTL)
async def test_sd_end_to_end(dut):
    """Insert a card, init it, read its CSD, read a block, write a block, read
    it back — every step through AXI only, against the SD SPI-mode model."""
    b = await bring_up(dut, card_present=False)
    card = _card(dut)
    lba_r, lba_w = 2048, 2048 + 9                  # partition start, and slot-ish
    seeded = bytes(random.Random(1).getrandbits(8) for _ in range(BLOCK))
    card.write_block(lba_r, seeded)

    await b.insert_card()
    await b.clear_sticky()
    host = SdHost(b)

    ocr = await host.init()
    assert ocr & (1 << 31) and ocr & (1 << 30), f"OCR 0x{ocr:08X}: not ready SDHC (CCS)"
    assert card.spi_mode and card.ready

    # CSD v2 -> capacity.
    await b.set_ctrl(cs=1)
    r, _ = await host.cmd(9, 0)
    assert r == 0x00
    assert await host.token() == 0xFE
    csd = bytes([await host.byte() for _ in range(16)])
    crc = (await host.byte() << 8) | await host.byte()
    await host.deselect()
    assert crc == crc16(csd) and csd[0] >> 6 == 1, f"CSD {csd.hex()}"
    c_size = ((csd[7] & 0x3F) << 16) | (csd[8] << 8) | csd[9]
    assert (c_size + 1) * 1024 == card.capacity_blocks

    got = await host.read_block(lba_r)
    assert got == seeded, "CMD17 returned the wrong data"

    payload = bytes(random.Random(2).getrandbits(8) for _ in range(BLOCK))
    busy = await host.write_block(lba_w, payload)
    assert busy > 0, "the card's write busy was never observed"
    assert card.writes == [lba_w] and bytes(card.blocks[lba_w]) == payload

    assert await host.read_block(lba_w) == payload, "read-back mismatch"
    assert await host.read_block(lba_r) == seeded, "a neighbouring block changed"

    st = await b.status()
    assert not st & (ST_OVR | ST_ABORT), f"STATUS 0x{st:02X}"
    assert card.errors == [], card.errors
    card.stop()


@cocotb.test(skip=NO_RTL)
async def test_sd_multiblock(dut):
    """CMD25 (0xFC tokens, 0xFD stop) writes three blocks; CMD18 reads them back
    and CMD12 stops the stream (stuff byte, R1, busy)."""
    b = await bring_up(dut)
    card = _card(dut)
    await _pads_on_for_protocol_test(b)
    host = SdHost(b)
    await host.init()
    base = 4096
    blocks = [bytes(random.Random(10 + i).getrandbits(8) for _ in range(BLOCK))
              for i in range(3)]

    await b.set_ctrl(cs=1)
    r, _ = await host.cmd(25, base)
    assert r == 0x00
    for blk in blocks:
        await host.byte(0xFF)
        await host.byte(0xFC)
        await host.bytes_wide(blk)
        await host.byte(0xFF)
        await host.byte(0xFF)
        assert await host.byte() & 0x1F == DATA_RESP_ACCEPTED
        assert await host.wait_not_busy() > 0
    await host.byte(0xFD)
    await host.byte()                                   # Nbr
    assert await host.wait_not_busy() > 0, "no busy after the stop token"
    await host.deselect()
    assert card.writes == [base, base + 1, base + 2]

    await b.set_ctrl(cs=1)
    r, _ = await host.cmd(18, base)
    assert r == 0x00
    for i, blk in enumerate(blocks):
        assert await host.token() == 0xFE, f"no token for block {i}"
        data = await host.bytes_wide(n=BLOCK)
        crc = (await host.byte() << 8) | await host.byte()
        assert data == blk and crc == crc16(data), f"CMD18 block {i}"
    await host.send_cmd(12, 0)
    await host.byte()                                   # stuff byte: discard
    r = await host.r1()
    assert r == 0x00, f"CMD12 R1 0x{r:02X}"
    await host.wait_not_busy()
    await host.deselect()
    assert card.errors == [], card.errors
    card.stop()


@cocotb.test(skip=NO_RTL)
async def test_sd_crc7_checked_on_cmd0_and_cmd8(dut):
    """The model checks CRC7 where real cards do: a CMD0 with a bad CRC gets no
    response at all (the card stays in SD mode), a CMD8 with a bad CRC gets R1
    with COM_CRC_ERROR. The right CRCs then work."""
    b = await bring_up(dut)
    card = _card(dut)
    await _pads_on_for_protocol_test(b)
    host = SdHost(b)
    await host.power_up_clocks()
    await b.set_ctrl(cs=1)
    r, _ = await host.cmd(0, 0, crc=0x01)
    assert r == 0xFF and not card.spi_mode, f"bad-CRC CMD0 answered 0x{r:02X}"
    r, _ = await host.cmd(0, 0)
    assert r == R1_IDLE and card.spi_mode
    r, _ = await host.cmd(8, 0x1AA, crc=0x01)
    assert r == R1_IDLE | R1_CRC_ERR, f"bad-CRC CMD8 answered 0x{r:02X}"
    r, r7 = await host.cmd(8, 0x1AA, extra=4)
    assert r == R1_IDLE and r7 == [0, 0, 1, 0xAA]
    assert card.errors == ["CMD0 with a bad CRC7: ignored (SD mode)",
                           "CMD8: bad CRC7 0x01"], card.errors
    card.stop()


@cocotb.test(skip=NO_RTL)
async def test_sd_sdsc_card_reports_ccs0(dut):
    """An SDSC (<= 2 GB) card completes init but reports CCS=0 in CMD58 — the
    firmware's cue for `USD : unsupported` (handover §1)."""
    b = await bring_up(dut)
    card = _card(dut, sdhc=False)
    await _pads_on_for_protocol_test(b)
    ocr = await SdHost(b).init()
    assert ocr & (1 << 31) and not ocr & (1 << 30), f"OCR 0x{ocr:08X}"
    assert card.errors == [], card.errors
    card.stop()


@cocotb.test(skip=NO_RTL)
async def test_sd_card_ignores_cmd0_without_power_up_clocks(dut):
    """The model enforces the >= 74 power-up clocks with CS high: a driver that
    skips them gets silence, like a real card."""
    b = await bring_up(dut)
    card = _card(dut)
    await _pads_on_for_protocol_test(b)
    host = SdHost(b)
    await b.set_ctrl(en=1, cs=1)
    r, _ = await host.cmd(0, 0)
    assert r == 0xFF and not card.spi_mode
    assert card.errors and "power-up clocks" in card.errors[0]
    card.stop()
