#!/usr/bin/env python3
"""gen_lint_stubs.py — emit blackbox stubs so the two IICE tops can be linted
standalone, without elaborating the whole 240-file nanosoc SoC.

Neither stub is ever synthesised. They exist so `verilator --lint-only` can
resolve the one child module each top instantiates, which is what makes the lint
meaningful (an unresolved child means verilator gives up before checking a
single connection).

Both stubs are DERIVED, never hand-written:

  rp_nanosoc_wrapper_stub.sv
      port list read out of fpga/rp/nanosoc/rp_nanosoc_wrapper.sv, so it cannot
      drift from the real wrapper.

  rp_nanosoc_iice_core_iice_stub.sv
      port list read out of rp_nanosoc_iice_core.sv PLUS the four ports the
      Identify instrumentor adds for `device jtagport soft`
      (identify_jtag_{tck,tms,tdi,tdo}). This models the POST-INSTRUMENTATION
      51-port EDIF boundary (47 contract + 4), which is the thing rp_nanosoc_iice_shim.sv actually
      instantiates. Linting the shim against it proves the instantiation is
      port-complete and correctly directed BEFORE a licence is spent on
      Synplify.

The parsing is done by fpga/dfx/pin_check.py's own parse_ports(), i.e. by the
same code that enforces the boundary contract in `make check`. If pin_check's
parser and this script ever disagreed, the gate would be worthless.

Usage:
    python3 lint/gen_lint_stubs.py <repo_root> <outdir>
"""
import sys
from pathlib import Path

# The four ports `device jtagport soft` adds to the SYNTHESIS TOP.
# Source: Identify 2022.09-SP2 hwg_comm_gen_c::PrintJTAGUserMessage() —
#   "The following external ports have been added to your design for
#    communication: identify_jtag_tck/tms/tdi/tdo"
# and identify_debugger_ug_synplify.pdf p.83 ("Using the Synopsys Debug Port").
IDENTIFY_SOFT_TAP = [
    ("identify_jtag_tck", "input", "1"),
    ("identify_jtag_tms", "input", "1"),
    ("identify_jtag_tdi", "input", "1"),
    ("identify_jtag_tdo", "output", "1"),
]

HEADER = """// GENERATED by lint/gen_lint_stubs.py -- DO NOT EDIT.
// Stub of `{mod}`{extra}, derived from
//   {src}
// so it cannot drift from the real port list. {use}
"""
USE_LINT = "Lint scaffolding only."
USE_BB = ("NOT just scaffolding: ooc_synth_synplify.tcl reads this file so "
          "synth_design\n// can elaborate the shim and link the Synplify EDIF "
          "into this empty cell.")


def decl(name, direction, width):
    rng = "" if width == "1" else (
        "[NGPIO-1:0] " if width == "NGPIO" else f"[{int(width) - 1}:0] ")
    return f"  {direction:<6s} logic {rng}{name}"


def emit(mod, src, ports, extra_note="", blackbox=False):
    lines = [HEADER.format(mod=mod, src=src, extra=extra_note,
                           use=(USE_BB if blackbox else USE_LINT))]
    if blackbox:
        lines.append(
            "// (* black_box *) is LOAD-BEARING, not decoration. It is what lets\n"
            "// `synth_design -top <shim>` elaborate the shim while leaving this cell\n"
            "// empty, so the EDIF read by `read_edif` can be linked into it. PROVEN\n"
            "// recipe (2026-07-29, xcku115-flvb1760-1-c, Vivado 2024.1):\n"
            "//     read_edif <core>.edf\n"
            "//     read_verilog -sv <this file>\n"
            "//     read_verilog -sv <shim>.sv\n"
            "//     synth_design -mode out_of_context -top <shim> -part ...\n"
            "// -> 1290 cells (the 1288 of the standalone-linked EDIF plus the shim's\n"
            "//    two), 35 ports / 136 bits at the time (47 / 148 since the 2026-10\n"
            "//    ILA mint's dbgbscan group), IS_BLACKBOX(u_core) == 0.\n"
            "// WITHOUT this stub synth_design dies with\n"
            "//     ERROR: [Synth 8-439] module '<core>' not found\n"
            "// and `link_design -top <shim>` is NOT an alternative: it dies with\n"
            "//     ERROR: [Project 1-68] No files found to match top module\n"
            "// because link_design needs a netlist for the top, and the shim is RTL.")
        lines.append("(* black_box *)")
    lines.append(f"module {mod} #(")
    lines.append("  parameter int NGPIO = 16")
    lines.append(") (")
    lines.append(",\n".join(decl(n, d, w) for n, (d, w) in ports.items()))
    lines.append(");")
    if not blackbox:
        lines.append("  // Tie every output so the lint of the PARENT is about the")
        lines.append("  // parent, not about undriven nets inside a stub.")
        for n, (d, w) in ports.items():
            if d == "output":
                # `{NGPIO{1'b0}}` not `NGPIO'b0` -- a parameterised sized literal
                # is not legal Verilog; '0 works for both the parameterised and
                # the fixed widths.
                lines.append(f"  assign {n} = '0;" if w != "1"
                             else f"  assign {n} = 1'b0;")
    else:
        lines.append("  // Deliberately EMPTY -- read_edif supplies the contents.")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    root, outdir = Path(sys.argv[1]).resolve(), Path(sys.argv[2]).resolve()
    sys.path.insert(0, str(root / "fpga" / "dfx"))
    import pin_check  # noqa: E402  (deliberately late; needs the path above)

    outdir.mkdir(parents=True, exist_ok=True)
    iice_dir = root / "fpga" / "rp" / "nanosoc_iice"

    # --- stub 1: the real RM wrapper, for linting rp_nanosoc_iice_core --------
    wsrc = root / "fpga" / "rp" / "nanosoc" / "rp_nanosoc_wrapper.sv"
    wname, wports, wngpio = pin_check.parse_ports(wsrc)
    if wname != "rp_nanosoc_wrapper":
        raise SystemExit(f"{wsrc}: module is {wname}, expected rp_nanosoc_wrapper")
    ncon = len(pin_check.CONTRACT)   # the generated boundary, not a literal
    if len(wports) != ncon:
        raise SystemExit(f"{wsrc}: {len(wports)} ports, expected {ncon}")
    (outdir / "rp_nanosoc_wrapper_stub.sv").write_text(
        emit(wname, wsrc, wports))

    # --- stub 2: the INSTRUMENTED core, for linting rp_nanosoc_iice_shim -----
    csrc = iice_dir / "rp_nanosoc_iice_core.sv"
    cname, cports, _ = pin_check.parse_ports(csrc)
    if cname != "rp_nanosoc_iice_core":
        raise SystemExit(f"{csrc}: module is {cname}, expected rp_nanosoc_iice_core")
    if len(cports) != ncon:
        raise SystemExit(f"{csrc}: {len(cports)} ports, expected {ncon} "
                         "(the contract; Identify adds the other four)")
    for n, d, w in IDENTIFY_SOFT_TAP:
        if n in cports:
            raise SystemExit(
                f"{csrc}: declares {n} itself. Do NOT pre-declare the soft-TAP "
                "ports -- the instrumentor ADDS them and would collide.")
        cports[n] = (d, w)
    (outdir / "rp_nanosoc_iice_core_iice_stub.sv").write_text(
        emit(cname, csrc,
             cports,
             extra_note=f" AS INSTRUMENTED ({ncon} contract ports + 4 soft-TAP)"))

    # --- stub 3: the SAME instrumented boundary, but a real Vivado BLACK BOX. ------
    # This one is not lint scaffolding: ooc_synth_synplify.tcl reads it so that
    # `synth_design -top rp_nanosoc_iice_shim` can elaborate the shim and then
    # link the Synplify EDIF into the empty cell. See emit()'s blackbox note.
    (outdir / "rp_nanosoc_iice_core_bb.sv").write_text(
        emit(cname, csrc, cports, blackbox=True,
             extra_note=" AS INSTRUMENTED, as a Vivado BLACK BOX "
                        f"({ncon} contract ports + 4 soft-TAP)"))

    print(f"stubs: rp_nanosoc_wrapper_stub.sv ({ncon} ports), "
          f"rp_nanosoc_iice_core_iice_stub.sv ({len(cports)} ports, lint), "
          f"rp_nanosoc_iice_core_bb.sv ({len(cports)} ports, black box) -> {outdir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
