// GENERATED by gen_shadow.py from signals_nanosoc.yaml -- DO NOT EDIT
//
// Shadow IICE for IICE_CPU. Portless, testbench-only; uses absolute
// hierarchical references, so it needs no wiring at all:
//
//     iice_shadow_IICE_CPU u_iice_shadow();
//
// Runtime plusargs:
//     +iice_shadow        enable FSDB dumping. DEFAULT OFF, so adding this
//                         module to a bench cannot slow an existing gate.
//     +iice_fsdb=<path>   output file (default sim_iice.fsdb).
//
// Contract: tests/identify_iice/INTERFACES.md sections 0, 1 and 3.2.
// Edit signals_nanosoc.yaml and re-run `make -C tests/identify_iice gen` instead.

module iice_shadow_IICE_CPU;

  // Manifest depth, recorded for downstream readers. NOTHING here
  // consumes it: the sim does not buffer (INTERFACES.md section 0) -- the
  // offline cropper uses depth + trigger_time to cut the window.
  localparam int IICE_DEPTH = 1024;

  // The IICE sample clock, tapped from the design. Same net, same edge as
  // the hardware IICE samples on (manifest iice.clock).
  logic sample_clk;
  assign sample_clk = micropython_flash_boot_tb.dut_clk;

  // ---------------------------------------------------------------------
  // Registered mirrors -- clocked on the manifest edge (posedge). THIS is
  // what makes the trace IICE-faithful: exactly one value per sample edge,
  // no combinational glitches. Names are the manifest names verbatim, so
  // the FSDB leaf names match the hardware side by construction
  // (INTERFACES.md section 1).
  // ---------------------------------------------------------------------
  logic [31:0] haddr;
  logic [1:0]  htrans;
  logic [3:0]  hprot;
  logic        hready;
  logic        hwrite;
  logic        hresp;
  logic [31:0] hrdata;
  logic [31:0] hwdata;
  logic        lockup;
  logic        sleeping;
  logic        sysresetreq;
  logic        hresetn;
  logic [3:0]  remap_ctrl;

  always_ff @(posedge sample_clk) begin
    haddr       <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HADDR;
    htrans      <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HTRANS;
    hprot       <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HPROT;
    hready      <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HREADY;
    hwrite      <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HWRITE;
    hresp       <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HRESP;
    hrdata      <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HRDATA;
    hwdata      <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.HWDATA;
    lockup      <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.CORE_LOCKUP;
    sleeping    <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.CORE_SLEEPING;
    sysresetreq <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.CORE_SYSRESETREQ;
    hresetn     <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.u_cpu_0.SYS_HRESETn;
    remap_ctrl  <= micropython_flash_boot_tb.u_nanosoc.u_ss_cpu.sys_remap_ctrl;
  end

  // ---------------------------------------------------------------------
  // Trigger marker. Registered off the ALREADY-REGISTERED mirrors above, so
  // it is ONE sample edge later than the raw condition:
  //
  //     trigger_marker high at sample N  <=>  the trigger condition held
  //                                           at sample N-1
  //
  // That offset is INTENTIONAL and the offline cropper owns it
  // (INTERFACES.md section 3.2). Do NOT 'fix' it here or in the generator --
  // doing so silently shifts every cropped window by one sample.
  //
  // The expression is the manifest's trigger.expr, emitted verbatim over the
  // mirror registers (never over raw design paths).
  // ---------------------------------------------------------------------
  logic trigger_marker;
  always_ff @(posedge sample_clk)
    trigger_marker <= (htrans[1] == 1'b1);

  // ---------------------------------------------------------------------
  // FSDB dump, gated on +iice_shadow (see the header). Dumping the whole
  // scope of this module yields exactly the manifest signals plus
  // sample_clk and trigger_marker -- the flat probe set the compare
  // pipeline expects, and nothing else.
  // ---------------------------------------------------------------------
  initial begin
    string f;
    if ($test$plusargs("iice_shadow")) begin
      if (!$value$plusargs("iice_fsdb=%s", f)) f = "sim_iice.fsdb";
      $fsdbDumpfile(f);
      $fsdbDumpvars(0, iice_shadow_IICE_CPU);
      $display("[iice_shadow] IICE_CPU ARMED: depth=%0d edge=posedge -> %s",
               IICE_DEPTH, f);
    end
    else begin
      $display("[iice_shadow] IICE_CPU IDLE: no FSDB written.");
      $display("[iice_shadow] pass +iice_shadow to enable it, +iice_fsdb=<path> to relocate.");
    end
  end

endmodule
