# DEPRECATED 2026-09-23 (LINUX_HARNESS_PLAN_2026-09-23.md DL2): the July Linux
# fork is superseded by the ONE shell BD's CPU seam -- fpga/shell/bd/shell_bd.tcl +
# cpu_mbv.tcl (SHELL_CPU=mbv), fpga/shell/build_shell.tcl and validate_bd.tcl,
# fpga/shell/shell_top.sv (`ifdef MPS3_SHELL_CPU_MBV), fpga/shell/constraints/mbv/.
# Do not edit or build this file; it is deleted at landing (lead).
##############################################################################
# mps3_harness_timing.xdc -- IMPLEMENTATION-ONLY harness timing constraints
#
# Loaded with USED_IN_SYNTHESIS=false by fpga/shell/build_shell.tcl (the
# clock objects referenced below are generated by the shell BD's clk_wiz
# cells and only exist once those IP have elaborated). NOTE: Vivado also
# applies this file when a post-SYNTH design is opened for analysis
# (open_run synth_1 loads implementation constraints) -- so post-synth
# timing reports already reflect these constraints; that is how the earlier
# unmeetable SMC I/O-delay version of this file was caught (WNS -29.3 ns on
# SMBF_DATA input paths, 2026-07-06 first full build pass).
#
# I/O timing philosophy (this revision): every board interface on this
# harness is either asynchronous or quasi-static at the pad --
#   * LAN9220 SMC bus: asynchronous SRAM-style protocol; the AC budget
#     (address/CE -> data valid, pulse widths, cycle floors) is enforced by
#     axi_emc_0's programmed bank timing (shell_bd.tcl SECTION 4, values
#     derived in fpga/ethernet/lan9220_if/README.md), counted in shell-clock
#     cycles inside the core -- NOT by pad-level setup/hold to a clock edge.
#     Single-cycle set_input_delay/set_output_delay against the 100 MHz
#     shell clock is unmeetable by construction (40 ns budget vs 10 ns
#     period) and models the wrong thing; the bus members are held stable
#     across many cycles per transaction.
#   * UART, LEDs, push-button, DIP switches, ETH_INT: async /
#     human-speed / firmware-paced; 2-FF synchronizers (or the IP's own
#     16x oversampling, for UART RX) own the metastability budget.
# Hence: false-path exceptions at the pads, full constraint coverage for
# everything clock-domain-internal (BD-generated clocks + the async group
# below). If a future interface is genuinely source-synchronous (e.g. a
# real RMII PHY pad), give it real I/O delays -- do not extend these
# false paths to it.
#
# The external QSPI flash IS such an interface, and as of the QSPI timing
# pass (2026-07-16) it is the one pad group here carrying REAL I/O delays:
# see the SST26VF064B section below. It is deliberately NOT false-pathed.
#
# Target: Vivado 2024.1, part xcku115-flvb1760-1-c
##############################################################################

##############################################################################
# Real shell-clock objects (clk_wiz cells in shell_bd.tcl SECTION 1):
#   clk_wiz_shell/clk_out1 : fixed ~100 MHz shell/AXI/MicroBlaze/ICAP clock
#   clk_wiz_shell/clk_out2 : fixed 50 MHz RMII reference (same MMCM ->
#                            synchronous with clk_out1; no group split)
#   clk_wiz_dut/clk_out1   : DRP-reconfigurable DUT clock (async domain)
##############################################################################
set clk_shell [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ "*/clk_wiz_shell/clk_out1"}]]
set clk_dut   [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ "*/clk_wiz_dut/clk_out1"}]]

##############################################################################
# Async clock groups: the shell's fixed domain vs the DUT-clock MMCM output.
# Every crossing between the two is CDC-structured on the static side
# (uart_bridge's gray-pointer async FIFOs, the per-block 2-FF synchronizers
# -- spec §5 "CDC everywhere the static and DUT domains meet"), so declare
# them asynchronous rather than leaving false inter-MMCM paths timed.
##############################################################################
set_clock_groups -name async_shell_dutclk -asynchronous \
    -group $clk_shell \
    -group $clk_dut

##############################################################################
# LAN9220 SMC bus -- asynchronous SRAM-style bus, paced by axi_emc_0's bank
# timing (see header). ETH_INT is an async interrupt line (firmware
# additionally reconfigures its polarity via IRQ_CFG before unmasking).
##############################################################################
set_false_path -to   [get_ports {SMBF_ADDR[*] SMBF_DATA[*] SMBF_FIFOSEL SMBF_nOE SMBF_nWE SMBF_nRST ETH_nCS ETH_nOE}]
set_false_path -from [get_ports {SMBF_DATA[*]}]
set_false_path -from [get_ports ETH_INT]

##############################################################################
# Board-level static control / status: LEDs, push-button reset, DIP
# switches (quasi-static human inputs; board_gpio's own 2-FF input
# synchronizers own the metastability budget).
##############################################################################
set_false_path -to   [get_ports {USER_nLED[*]}]
set_false_path -from [get_ports USER_nPB0]
set_false_path -from [get_ports {USER_SW[*]}]

##############################################################################
# External QSPI flash (SST26VF064B) -- RP-owned XiP path. SOURCE-SYNCHRONOUS.
#
#   *** FIRST-PASS TIMING MODEL -- BOARD SIGNOFF PENDING. ***
#   Datasheet numbers below are real and cited; the BOARD TRACE numbers are
#   engineering estimates (no MPS3 layout/length data was available). A timing
#   engineer must re-check the trace section against the real MPS3 flash
#   routing before this is called signed off. Everything is parameterised at
#   the top of the block so that is a one-line-per-value edit.
#
# Supersedes the previous `set_false_path` placeholder on these six pads
# (which was zero I/O timing). Closes the deferred-timing TODO in
# docs/contracts/partition-pins.md (QSPI crossing, v0.2) and the matching TODO
# in mps3_harness.xdc / shell_top.sv. This group is the documented NON-CDC
# exception in that contract: a matched-depth, source-synchronous passthrough
# (RP drives -> combinational DFX decoupler clamp -> shell IOBUFs -> pads;
# shell_top.sv u_qspi_*_iobuf). Because it is a passthrough and NOT a CDC, it
# must be timed, not false-pathed.
#
# ---------------------------------------------------------------------------
# TOPOLOGY (what the constraints model)
# ---------------------------------------------------------------------------
#   RP `qspi_flash_ahb` -> `top_ahb_qspi` -> `qspi_controller` + `qspi_clock_div`
#     QSPI_SCLK_i = HCLK/(2*CLK_DIV)   (CLK_DIV = APB reg13[4:0], byte 0x34)
#     Pin SCLK is QSPI_SCLK_i gated by QSPI_SCLK_e (held at CPOL=0 when idle).
#     SPI MODE 0, hardwired (QSPI_SPI_MODE tied 2'b00 in top_ahb_qspi.v):
#        master DRIVES QSPI_IO_o on the NEGEDGE of SCLK;
#        master SAMPLES QSPI_IO_i on the POSEDGE of SCLK.
#     The flash mirrors it (Mode 0): it samples SI on SCK rising and launches
#     SO on SCK falling. So both directions are half-SCLK-period, centre
#     aligned. The RTL has NO rx-sample-phase compensation -- that half period
#     is the entire budget, which is why `-clock_fall` on the input delay
#     below is load-bearing, not cosmetic.
#   HCLK here is the DUT clock (clk_wiz_dut/clk_out1, 50 MHz default, but
#   DRP-reconfigurable -- see shell_bd.tcl SECTION 1).
#
# ---------------------------------------------------------------------------
# THE ->8 RATIO
# ---------------------------------------------------------------------------
# partition-pins.md v0.2 makes SCLK <= HCLK/8 a hard requirement for XiP read
# closure, i.e. CLK_DIV >= 4. The generated clock below is therefore declared
# -divide_by 8 (the fastest legal SCLK). At the 50 MHz default that is
# 6.25 MHz / 160 ns -- ~17x slower than the part's 104 MHz limit, so these
# constraints are expected to pass with very large margin. That is the point:
# a passing report against REAL numbers is evidence; a false_path was not.
#
# NOTE -- no set_multicycle_path is needed or wanted here. The ->8 is already
# expressed in the generated clock, so every pad path is analysed edge-to-edge
# against qspi_sclk itself (160 ns period, 80 ns launch-to-capture half cycle).
# An MCP on top would double-count the ratio and silently inflate the budget.
#
# ---------------------------------------------------------------------------
# DATASHEET VALUES -- Microchip SST26VF064B/BA, DS20005119G, Table 8-1
# "AC Operating Characteristics", page 48. 104 MHz column (VDD 2.7-3.6V;
# these pads are LVCMOS33, mps3_harness.xdc). Cross-checked against the
# vendor's own behavioural model in-tree at
# ahb_qspi/verif/VIP/SST26VF064B.v (specify block, lines 106-163) -- every
# value agrees.
#   TDS  Data In Setup Time ............ 3 ns min   (flash setup requirement)
#   TDH  Data In Hold Time ............. 4 ns min   (flash hold requirement)
#   TV   Output Valid from SCK ......... 8 ns max @ 30 pF  (5 ns @ 10 pF)
#   TOH  Output Hold from SCK Change ... 0 ns min
#   TCES CE# Active Setup Time ......... 5 ns min
#   TCEH CE# Active Hold Time .......... 5 ns min   (TCHS/TCHH also 5 ns)
# We take TV = 8 ns, the 30 pF column -- the conservative one. The in-tree VIP
# uses Tv=5 (the 10 pF number); do not "correct" the 8 down to match the VIP.
# Read path is Fast-Read 0Bh + 8 dummy cycles (firmware/micropython
# port/xip_bringup.c, AHB_SPI_SETUP=0x800B). Per DS20005119G page 14 note 4,
# 0Bh runs at the full 104 MHz -- the 40 MHz limit is the 03h Read only, so
# the 104 MHz column is the right one. Dummy cycles shift WHICH bit is
# sampled, never the sample PHASE, so they do not enter this model.
#
# ---------------------------------------------------------------------------
# BOARD TRACE -- *** ESTIMATE, NOT MEASURED. SIGNOFF ITEM. ***
# ---------------------------------------------------------------------------
# No MPS3 flash trace-length data was available. Assumed: FR4 microstrip at
# ~170 ps/inch, flash within ~4 inches of the FPGA => ~0.2..0.8 ns one way,
# and SCLK/data NOT length-matched (so clock-vs-data skew is allowed to take
# the full +/-0.6 ns range rather than a matched-pair number). If the real
# layout matches SCLK to the data lanes, the skew term shrinks and these get
# looser still. Replace with measured lengths at signoff.
##############################################################################

# -- Datasheet (DS20005119G Table 8-1, 104 MHz column) ------------------------
set qspi_tds       3.0    ;# TDS  data-in setup  (flash requires)
set qspi_tdh       4.0    ;# TDH  data-in hold   (flash requires)
set qspi_tv        8.0    ;# TV   output valid from SCK, 30 pF
set qspi_toh       0.0    ;# TOH  output hold from SCK change
set qspi_tces      5.0    ;# TCES CE# active setup (= TCHS)
set qspi_tceh      5.0    ;# TCEH CE# active hold  (= TCHH)
# -- Board trace, ESTIMATED (see header) --------------------------------------
set qspi_trc_max   0.80   ;# longest  pad->flash one-way PCB delay, ns
set qspi_trc_min   0.20   ;# shortest pad->flash one-way PCB delay, ns
# Worst-case clock-vs-data trace skew either way (unmatched-trace assumption).
set qspi_skew      [expr {$qspi_trc_max - $qspi_trc_min}]

set qspi_dut_clk_pin [get_pins -quiet -hierarchical -filter {NAME =~ "*/clk_wiz_dut/clk_out1"}]
set qspi_sclk_port   [get_ports -quiet QSPI_SCLK]

if {[llength $qspi_dut_clk_pin] == 0 || [llength $qspi_sclk_port] == 0} {
    puts "WARNING: \[qspi-timing\] clk_wiz_dut/clk_out1 pin or QSPI_SCLK port not found -- QSPI I/O timing SKIPPED (these pads are then UNCONSTRAINED, not false-pathed)."
} elseif {[catch {
    # The reference clock is declared AT THE PAD, sourced from the DUT-clock
    # MMCM: RM-agnostic (no RM-internal hierarchy is named, so this survives
    # any RM that carries the qspi group) and it is the clock the flash
    # actually sees. Source latency to the pad is therefore modelled by
    # Vivado, and the PCB clock-trace delay is carried in the delay numbers
    # below (which are all referenced to the FPGA pad, not to the flash).
    create_generated_clock -name qspi_sclk -source $qspi_dut_clk_pin \
        -divide_by 8 $qspi_sclk_port
} qspi_err]} {
    puts "WARNING: \[qspi-timing\] could not create the qspi_sclk generated clock -- QSPI I/O timing SKIPPED. Expected ONLY when the RP is a black box (static-only synthesis), because the DUT-clock -> QSPI_SCLK path lives inside the RM. If you see this during implementation with an RM linked in, the QSPI pads are UNCONSTRAINED and this build is not signed off. Vivado said: $qspi_err"
} else {

    ##########################################################################
    # OUTPUT: FPGA -> flash (data lanes + nCS), referenced to qspi_sclk.
    # Master launches on SCLK negedge, flash captures on SCK posedge.
    #   -max = TDS + skew   (setup: data trace long, clock trace short)
    #   -min = -TDH - skew  (hold : data trace short, clock trace long)
    # Vivado picks the negedge launch from the RM netlist itself; do not add
    # -clock_fall here (that would move the REFERENCE edge, not the launch).
    ##########################################################################
    set_output_delay -clock qspi_sclk -max [expr {$qspi_tds + $qspi_skew}] \
        [get_ports {QSPI_D0 QSPI_D1 QSPI_D2 QSPI_D3}]
    set_output_delay -clock qspi_sclk -min [expr {-$qspi_tdh - $qspi_skew}] \
        [get_ports {QSPI_D0 QSPI_D1 QSPI_D2 QSPI_D3}]

    # nCS is not a per-cycle signal but it IS specified relative to SCK
    # (TCES/TCEH/TCHS/TCHH), so it is timed to the same reference clock.
    # The cycle-level rules the FSM owns (TCPH CE# high time = 12 ns min,
    # TCHZ = 12 ns) are protocol/sequencing, not pad setup/hold, and are not
    # expressible here -- they are the RM FSM's responsibility.
    set_output_delay -clock qspi_sclk -max [expr {$qspi_tces + $qspi_skew}] \
        [get_ports QSPI_nCS]
    set_output_delay -clock qspi_sclk -min [expr {-$qspi_tceh - $qspi_skew}] \
        [get_ports QSPI_nCS]

    ##########################################################################
    # INPUT: flash -> FPGA (read data), referenced to qspi_sclk.
    # -clock_fall is LOAD-BEARING: the flash launches SO on the SCK FALLING
    # edge (Mode 0) and the RP samples on the RISING edge. Without it Vivado
    # would reference the rising edge and model a full-period path that does
    # not exist, hiding the real half-period budget.
    #   -max = clk_trace_max + TV  + data_trace_max
    #   -min = clk_trace_min + TOH + data_trace_min
    # (Both trace terms are present because the round trip is pad -> flash on
    # SCLK, then flash -> pad on the data lane.)
    ##########################################################################
    set_input_delay -clock qspi_sclk -clock_fall \
        -max [expr {$qspi_trc_max + $qspi_tv + $qspi_trc_max}] \
        [get_ports {QSPI_D0 QSPI_D1 QSPI_D2 QSPI_D3}]
    set_input_delay -clock qspi_sclk -clock_fall \
        -min [expr {$qspi_trc_min + $qspi_toh + $qspi_trc_min}] \
        [get_ports {QSPI_D0 QSPI_D1 QSPI_D2 QSPI_D3}]

    ##########################################################################
    # qspi_sclk is derived from the DUT-clock MMCM, so it inherits the
    # shell-vs-DUT asynchrony declared at the top of this file. It needs its
    # own group because the async_shell_dutclk group above was evaluated
    # before this clock existed. This is not academic: the DFX decoupler's
    # clamp-enable is a SHELL-domain signal feeding the (combinational) clamp
    # in the qspi pad path, so shell->qspi_sclk paths do exist and would
    # otherwise be timed against unrelated clocks.
    ##########################################################################
    set_clock_groups -name async_shell_qspisclk -asynchronous \
        -group $clk_shell \
        -group [get_clocks qspi_sclk]
}

##############################################################################
# QSPI SIGNOFF CAVEATS -- read before calling this closed.
#
# 1. TRACE NUMBERS ARE ESTIMATES (see the header). Datasheet values are real
#    and cited; the PCB numbers are not measured. This is the main open item.
#
# 2. CLK_DIV=0 IS NOT FORBIDDEN BY THE RTL -- partition-pins.md v0.2 says
#    "the RTL already forbids CLK_DIV=0"; that claim is WRONG. qspi_clock_div.v
#    line 10 reads:
#        assign QSPI_SCLK_i = (QSPI_CLK_DIV==5'h00) ? HCLK : QSPI_SCLK_reg;
#    i.e. CLK_DIV=0 is an explicit, deliberate HCLK bypass (a combinational
#    mux putting raw HCLK on the pad), and the RDL documents it as such. There
#    is no RTL guard. CLK_DIV also RESETS TO 1 (HCLK/2), not to a ->8 value.
#    So the -divide_by 8 above is a constraint on FIRMWARE as much as on
#    silicon: firmware MUST program CLK_DIV >= 4 before any XiP fetch, or this
#    model is simply not describing the hardware. (Independent corroboration
#    that fast dividers do not work: ahb_qspi/docs/cocotb-silicon-findings.md
#    reports CLK_DIV=1 garbles RDID on real silicon.) Recommend the RM or
#    firmware pin this down; a set_case_analysis on CLK_DIV[4:0] would let a
#    future revision prove the bypass mux is unreachable, but it needs
#    RM-internal hierarchy and so cannot live in this (shell-owned) file.
#
# 3. THE RM MUST DEFINE ITS OWN INTERNAL SCLK CLOCK. The whole qspi_controller
#    is clocked by the internal QSPI_SCLK_i, not by HCLK. This file constrains
#    the PADS; it cannot reach RM-internal objects. If the RM does not declare
#    a generated clock on QSPI_SCLK_i, the controller's internal paths get
#    timed via the CLK_DIV=0 bypass mux at full HCLK rate (pessimistic but
#    safe) rather than at the real SCLK rate. Verify with report_clock_networks
#    on a linked implementation run.
#
# 4. NOT YET RUN THROUGH PLACE-AND-ROUTE. Syntax and port/pin targets are
#    checked; the actual slack is not. Confirm with report_timing on the
#    qspi_sclk clock after implementation.
##############################################################################

##############################################################################
# CLCD 8080 panel bus (Himax HX8347-D, 14 pads, bank 66, LVCMOS18)
# ---------------------------------------------------------------------------
# FIRST-PASS, BOARD-SIGNOFF-PENDING. The panel is LIT and WORKING on silicon
# with the shipped TIMING values below (docs/CLCD_PANEL_FACTS.md), so this
# block's job is to STOP the pads being unconstrained -- not to discover a
# frequency. Read the caveats at the bottom before trusting the numbers.
#
# WHY THIS IS NOT THE QSPI MODEL (do not copy that block down here):
#   The QSPI flash returns data against a clock WE forward (SCLK), so it is a
#   genuine source-synchronous interface and gets a generated clock + input/
#   output delays referenced to it. The CLCD 8080 bus has NO forwarded clock:
#   CLCD_WR_SCL is a STROBE the shell's FSM generates, and the panel latches
#   PD/RS on the WR RISING edge. There is no clock to reference, and nothing
#   is captured back. So the real requirement is not "meet a clock" -- it is
#   "PD/RS must be stable around the WR edge AT THE PANEL", i.e. a bound on
#   the pad-to-pad SKEW of a group that all launches from one clock domain.
#
# THE ACTUAL MARGIN COMES FROM THE FSM, NOT FROM THIS CONSTRAINT:
#   clcd_core.sv's 3-phase strobe FSM holds CS/RS/PD stable for cs_setup, then
#   drives WR low for wr_lo, then high for wr_hi -- all in s_axi_aclk cycles,
#   runtime-programmable via the TIMING register. The SHIPPED, BOARD-PROVEN
#   values are cs_setup=2, wr_lo=4, wr_hi=4 at the 100 MHz shell clock:
#       CS/RS/PD stable -> WR falls : 20 ns
#       WR low                      : 40 ns   <- PD/RS stable this whole time
#       WR high                     : 40 ns   <- ...and this whole time
#   so PD/RS are stable ~40 ns EITHER SIDE of the WR rising edge that latches
#   them. The panel needs single-digit-ns setup/hold (see caveat 1). The FSM
#   therefore carries ~4x margin in CYCLES. The ONLY thing that can erode it
#   is clock-to-pad SKEW between the data/control pads and the WR pad.
#
# WHAT THIS CONSTRAINT DOES:
#   Bound every strobed CLCD pad's clock-to-pad delay into one window relative
#   to the shell clock, so the tool cannot skew WR away from PD/RS. With the
#   window below (-2 .. +8 ns against a 10 ns clk_shell period) worst-case
#   pairwise skew is <= 10 ns, leaving >= 30 ns of the FSM's 40 ns intact --
#   still 3x the panel's need. This is deliberately a SKEW BUDGET expressed as
#   output delays, not a fabricated setup/hold against an imaginary clock.
##############################################################################

set clcd_strobed [get_ports -quiet {CLCD_PD[*] CLCD_RS CLCD_CS CLCD_WR_SCL}]

if {[llength $clcd_strobed] == 0} {
    puts "WARNING: \[clcd-timing\] no CLCD_PD/RS/CS/WR_SCL ports found -- CLCD I/O timing SKIPPED (these pads are then UNCONSTRAINED, not false-pathed)."
} else {
    # -max  8.0 : latest a pad may reach the panel, referenced to clk_shell.
    # -min -2.0 : earliest. Window = 10 ns == one clk_shell period, so the
    #             tool must land all four groups within one period of each
    #             other => pairwise skew <= 10 ns (see the header maths).
    #             Includes the ~0.5 ns board-trace estimate (caveat 2).
    set_output_delay -clock $clk_shell -max  8.0 $clcd_strobed
    set_output_delay -clock $clk_shell -min -2.0 $clcd_strobed
}

# --- Explicitly-argued exceptions (NOT laziness -- these have no edge to meet) --
#
# CLCD_BL / CLCD_RST are quasi-static LEVELS, not part of any strobed transfer:
# firmware writes CTRL and the level sits there for milliseconds (backlight on,
# panel reset asserted for >= 2 ms at init -- firmware/clcd/clcd.c). There is no
# capture edge anywhere in the system that samples them, so a setup/hold number
# would be fiction. Constraining them would only distort placement.
set_false_path -to [get_ports -quiet {CLCD_BL CLCD_RST}]

# CLCD_RD: the shipped shell builds clcd with READ_PATH=0 (docs/CLCD_PANEL_FACTS.md
# -- read-back is NOT built), so RD is held deasserted, constant. Nothing toggles.
set_false_path -to [get_ports -quiet CLCD_RD]

# CLCD_PD INPUT path: with READ_PATH=0 the IOBUFs' O pins feed nothing (pd_oe is
# tied 1, the block is write-only). The input path is structurally dead. If a
# future build sets READ_PATH=1, DELETE this and give the read-back a real
# input-delay -- it would then be a genuine (slow, strobed) input.
set_false_path -from [get_ports -quiet {CLCD_PD[*]}]

##############################################################################
# CLCD caveats -- what a timing engineer must close at signoff
#  1. The HX8347-D datasheet 8080 write numbers (tDST setup / tDHT hold / tWRLW
#     pulse width) were NOT obtained for this pass. The "single-digit ns" claim
#     above is a CONSERVATIVE ESTIMATE typical of the family, NOT a datasheet
#     citation. It is used only to argue that the FSM's 40 ns dwarfs it -- which
#     the LIT PANEL corroborates far better than any number would. Replace the
#     estimate with the real tDST/tDHT and re-check the 30 ns residual.
#  2. Board trace delay is an ESTIMATE (~0.5 ns, short bank-66 traces to the
#     on-board panel). Not length-matched, not measured.
#  3. Actual slack needs report_timing on the CLCD pads post-implementation.
#     Expect large positive slack -- that is the point: a pass against a real
#     budget is evidence; the previous silence (no constraint at all) was not.
#  4. If firmware ever programs TIMING BELOW the shipped cs_setup=2/wr_lo=4/
#     wr_hi=4, the FSM margin shrinks and this skew budget may no longer be
#     dwarfed by it. The DUT-side accelerator's contract makes TIMING plain RW
#     (fpga/rp/nanosoc_exp/README.md sec.7), so this is reachable from software.
#     Treat the shipped values as the signoff assumption.
##############################################################################

##############################################################################
# MicroBlaze console UART -- 115200 baud, fully asynchronous at the pad
# (axi_uartlite's 16x oversampling owns RX alignment). The earlier
# set_input_delay/set_output_delay pair copied from the legacy
# fpga_timing.xdc was budgeted against OSCCLK[1]'s 20 ns period; against
# this design's 10 ns shell clock it was unmeetable and modeled nothing
# real.
##############################################################################
# [LINUX-DEV-1] port names follow mps3_harness_linux.xdc's console re-pin.
set_false_path -from [get_ports LINUX_UART_RXD]
set_false_path -to   [get_ports LINUX_UART_TXD]
