# =============================================================================
# fallback_iice.idc — a MINIMAL, SELF-CONTAINED Identify instrumentation file.
#
# THIS IS NOT THE PRODUCT MANIFEST. The real .idc is generated by
# tests/identify_iice/gen_idc.py from signals_nanosoc.yaml (Stream A owns both).
# Point `make synth IDC=<path>` at that file for anything real.
#
# This one exists for exactly one purpose: proving the TOOLCHAIN leg (Synplify
# accepts the project -> the identify impl runs -> `device jtagport soft`
# inserts a soft TAP -> the EDIF contains IICE logic and NO BSCANE2) WITHOUT a
# dependency on any other workstream and without needing the DUT's internal
# hierarchy to be correct. Every probe below is a TOP-LEVEL PORT of the
# synthesis top, so `device stop_on_signal_not_found 1` cannot fail for a reason
# that is not a real toolchain problem.
#
# PATH CONVENTION — the thing to get right
# ---------------------------------------
# Identify's "/" IS the synthesis top's own scope. The top MODULE NAME is never
# part of the path. Authority:
#   identify_debug_env_reference.pdf p.14, "Design Hierarchy References":
#     "Absolute path names begin with a path separator character. The top-level
#      design unit is represented by the initial '/'. Thus, a port on the
#      top-level design unit would be represented: /port_name"
# Corroborated empirically by the working reference build
# HAPS-work/HAPS-SX/examples/hello_ident, whose .idc probes `/clk` and `/count`
# -- both declared directly inside `haps_sx_hello` -- with
# stop_on_signal_not_found 1 set and exit status 0.
#
# The synthesis top here is `rp_nanosoc_iice_core`, which instantiates the real
# RM as `u_rm`. So:
#
#   /dut_clk                             <- a port of the synthesis top
#   /u_rm/<anything in rp_nanosoc_wrapper>
#   /u_rm/u_nanosoc/u_ss_cpu/u_cpu_0/HADDR   <- the M0's AHB address bus
#
# `u_rm` is FROZEN in rp_nanosoc_iice_core.sv for this reason.
# Verilog names are CASE SENSITIVE (HADDR, not haddr).
# =============================================================================

# --- device settings: all four lines are MANDATORY on this target ------------
# jtagport soft: `builtin` emits a BSCANE2, which is HDPR-16 "Illegal logic
#   inside reconfigurable cell", and the RP pblock has ZERO BSCAN sites anyway.
# xilinxinsertbufg 0: the instrumentor otherwise inserts `BUFG clkbuf(.I(tck))`
#   and the RP pblock has ZERO BUFG sites.
# skewfree 1: builds master/slave flops on the JTAG chain instead of relying on
#   a global buffer for a net that drives >1000 flip-flops. (Per the docs this
#   also suppresses the BUFG on its own -- the two settings agree, belt and
#   braces.)
# stop_on_signal_not_found 1: default is 0, i.e. a typo'd probe path becomes a
#   WARNING and you get a silently under-instrumented bitstream.
device jtagport soft
device xilinxinsertbufg 0
device skewfree 1
device stop_on_signal_not_found 1

# --- one regular IICE on the DUT system clock --------------------------------
iice new {IICE_TOOLCHAIN_PROOF} -type regular
iice clock   -iice {IICE_TOOLCHAIN_PROOF} -edge positive {/dut_clk}
iice sampler -iice {IICE_TOOLCHAIN_PROOF} -depth 1024
iice controller -iice {IICE_TOOLCHAIN_PROOF} statemachine
iice controller -iice {IICE_TOOLCHAIN_PROOF} -triggerconditions 2 -triggerstates 2

# --- probes: the console byte stream, at the partition boundary --------------
# Chosen because they are real traffic (so a capture is worth looking at), they
# are top-level ports (so they cannot fail to resolve), and there are few enough
# of them that the IICE stays small. hello_ident measured 336 LUT / 589 FF /
# 1.5 BRAM for a depth-1024 sampler; the RP has ~32,750 free LUTs and 123.5 free
# BRAM tiles, so this is noise.
signals add -iice {IICE_TOOLCHAIN_PROOF} -sample -trigger {/uart_tx_tdata}
signals add -iice {IICE_TOOLCHAIN_PROOF} -sample -trigger {/uart_tx_tvalid}
signals add -iice {IICE_TOOLCHAIN_PROOF} -sample          {/uart_rx_tdata}
signals add -iice {IICE_TOOLCHAIN_PROOF} -sample -trigger {/uart_rx_tvalid}
signals add -iice {IICE_TOOLCHAIN_PROOF} -sample -trigger {/dut_resetn}

# --- what the REAL manifest should look like (do not enable here) ------------
# The M0 AHB-Lite bus at the CPU boundary. Hierarchy verified by reading the
# RTL: rp_nanosoc_iice_core/u_rm (rp_nanosoc_wrapper) -> u_nanosoc (nanosoc)
# -> u_ss_cpu (nanosoc_ss_cpu) -> u_cpu_0 (slcorem0).
#
# signals add -iice {IICE_CPU} -sample -trigger {/u_rm/u_nanosoc/u_ss_cpu/u_cpu_0/HADDR}
# signals add -iice {IICE_CPU} -sample          {/u_rm/u_nanosoc/u_ss_cpu/u_cpu_0/HWDATA}
# signals add -iice {IICE_CPU} -sample          {/u_rm/u_nanosoc/u_ss_cpu/u_cpu_0/HRDATA}
# signals add -iice {IICE_CPU} -sample -trigger {/u_rm/u_nanosoc/u_ss_cpu/u_cpu_0/HTRANS}
# signals add -iice {IICE_CPU} -sample          {/u_rm/u_nanosoc/u_ss_cpu/u_cpu_0/HWRITE}
# signals add -iice {IICE_CPU} -sample -trigger {/u_rm/u_nanosoc/u_ss_cpu/u_cpu_0/LOCKUP}
