#!/usr/bin/env python3
"""probe_shim_gen.py — generate a throwaway 47-port shim over a 51-port
instrumented EDIF cell, for the `probe-dcp` Phase-1 gate.

WHY THIS EXISTS
---------------
`make probe-softtap` proves the Synplify+Identify leg on a throwaway RM. It
also proves, by counting the ports of the emitted EDIF, that
`device jtagport soft` ADDS identify_jtag_{tck,tms,tdi,tdo} to the synthesis
top: 47 contract ports -> 51.

That leaves exactly one link in this flow unproven: can Vivado consume an
EDIF-sourced 39-port cell as the CHILD of an RTL parent and emit an
out-of-context checkpoint whose top carries only the 47 contract ports? That is
the mechanism `ooc_synth_synplify.tcl` relies on for the real build
(read_edif + read_verilog + synth_design -mode out_of_context), and if it does
not work the fallback is a full boundary re-mint.

This script writes the throwaway parent for that experiment. It is the same
shape as rp_nanosoc_iice_shim.sv (the same 1149.1 daisy-chain splice of the
soft TAP into the jtag_* wire-set, same default order) but over the probe RM
instead of nanosoc, so the experiment tests the MECHANISM without needing the
246-file DUT to elaborate.

The port list is read out of the probe RM's own source via
fpga/dfx/pin_check.py's parser, so it cannot drift.

Usage:
    probe_shim_gen.py [--blackbox] <repo_root> <probe_rm_source.sv> <out.sv>

--blackbox emits the (* black_box *) 51-port stub of the child instead of the
47-port parent. Both are needed: the PROVEN Vivado recipe is
    read_edif <core>.edf ; read_verilog -sv <bb stub> ; read_verilog -sv <shim>
    ; synth_design -mode out_of_context -top <shim>
"""
import sys
from pathlib import Path

SOFT_TAP = ["identify_jtag_tck", "identify_jtag_tms",
            "identify_jtag_tdi", "identify_jtag_tdo"]

# The four JTAG partition pins the chain rides on (fpga/shell/boundary.yaml
# group `jtag`). Rebased 2026-09-10: the swd_* group these used to name does not
# exist in the then-fielded boundary (mint 0xA8C1C535).
JTAG_TCK = "jtag_tck"     # shell -> RP, shared by both TAPs
JTAG_TMS = "jtag_tms"     # shell -> RP, shared by both TAPs
JTAG_TDI = "jtag_tdi"     # shell -> RP, head of the chain
JTAG_TDO = "jtag_tdo"     # RP -> shell, tail of the chain


def main():
    argv = sys.argv[1:]
    blackbox = "--blackbox" in argv
    argv = [a for a in argv if a != "--blackbox"]
    if len(argv) != 3:
        print(__doc__)
        return 2
    root, src, out = (Path(argv[0]).resolve(),
                      Path(argv[1]).resolve(),
                      Path(argv[2]))
    sys.path.insert(0, str(root / "fpga" / "dfx"))
    import pin_check  # noqa: E402

    child, ports, ngpio = pin_check.parse_ports(src)
    if len(ports) != len(pin_check.CONTRACT):
        raise SystemExit(f"{src}: {len(ports)} ports, expected the "
                         f"{len(pin_check.CONTRACT)} contract ports")
    if ngpio != 16:
        raise SystemExit(f"{src}: NGPIO={ngpio}, expected 16")
    shim = f"{child}_iice_shim"

    def rng(w):
        return "" if w == "1" else ("[NGPIO-1:0] " if w == "NGPIO"
                                    else f"[{int(w) - 1}:0] ")

    if blackbox:
        bb = dict(ports)
        for n in SOFT_TAP:
            bb[n] = ("output" if n.endswith("tdo") else "input", "1")
        B = [f"// GENERATED by probe_shim_gen.py --blackbox from {src}. THROWAWAY.",
             "// (* black_box *) is load-bearing: it lets synth_design elaborate the",
             "// shim while leaving this cell empty for read_edif to fill.",
             "(* black_box *)",
             f"module {child} #(", "  parameter int NGPIO = 16", ") ("]
        B.append(",\n".join(f"  {d:<6s} logic {rng(w)}{n}" for n, (d, w) in bb.items()))
        B += [");", "endmodule"]
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(B) + "\n")
        print(f"probe black box: {child} ({len(bb)} ports) -> {out}")
        return 0

    L = [f"// GENERATED by probe_shim_gen.py from {src}. THROWAWAY — do not commit,",
         "// do not synthesise into anything real. Phase-1 mechanism proof only:",
         "// 47-port RTL parent over a 51-port instrumented EDIF child.",
         f"module {shim} #(",
         "  parameter int NGPIO = 16",
         ") ("]
    L.append(",\n".join(f"  {d:<6s} logic {rng(w)}{n}" for n, (d, w) in ports.items()))
    L.append(");")
    L.append("  // 1149.1 daisy chain, default order (IICE_TAP_NEAREST_TDI=1):")
    L.append(f"  //   {JTAG_TDI} -> Identify soft TAP -> child TAP -> {JTAG_TDO}")
    L.append("  logic iice_tdo, dap_tdo;")
    L.append(f"  assign {JTAG_TDO} = dap_tdo;")
    L.append(f"  {child} #(.NGPIO(NGPIO)) u_core (")
    conn = []
    for n in ports:
        if n == JTAG_TDI:
            conn.append(f"    .{n}(iice_tdo)")     # chain hop into the child TAP
        elif n == JTAG_TDO:
            conn.append(f"    .{n}(dap_tdo)")
        else:
            conn.append(f"    .{n}({n})")
    conn.append(f"    .identify_jtag_tck({JTAG_TCK})")
    conn.append(f"    .identify_jtag_tms({JTAG_TMS})")
    conn.append(f"    .identify_jtag_tdi({JTAG_TDI})")
    conn.append("    .identify_jtag_tdo(iice_tdo)")
    L.append(",\n".join(conn))
    L.append("  );")
    L.append("endmodule")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"probe shim: {shim} ({len(ports)} ports) over {child} "
          f"({len(ports)} + {len(SOFT_TAP)} soft-TAP) -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
