#!/usr/bin/env python3
"""
gen_greybox_blob.py — produce firmware/platform/generated/greybox_blob.c,
the strong definitions for the five `mps3_greybox_clearing_*` externs
overlay_store.c expects (the greybox clearing bitstream "baked into the
shell image", ARCHITECTURE_SPEC "greybox + NVM" default / D14) plus the
strong `mps3_shell_static_id()` override (coordinator.h's static_id seam —
coordinator.c's weak fallback returns 0 = "not provisioned").

Identity fields (static_id, rm_id, and in --mode real the payload
CRC/length) come from the A2 overlay manifest
(fpga/dfx/overlay/greybox/manifest.json); the payload comes from
greybox_clear.bin next to it.

Two modes — because the REAL clearing blob does not fit the MicroBlaze's
local BRAM (see the honesty note below):

  --mode placeholder (default)
      Payload = 64 ICAP type-1 NOP words (0x20000000). Streaming NOPs into
      ICAP is a hardware no-op, so a boot/swap path that reaches the
      clearing stream does nothing (safe) instead of feeding ICAP garbage.
      len_words/crc32 are computed over THIS payload so every firmware
      CRC/length self-check stays internally consistent; rm_id/static_id
      are the real manifest values so `ping` reports the true shell
      identity and config_agent accepts real host pushes.
      *** A placeholder blob cannot actually clear the RP: real clearing
      at bring-up must come over the network (swap flow) or from QSPI. ***

  --mode real
      Payload = the full greybox_clear.bin (240,404 bytes for the current
      shell). HONESTY NOTE: this CANNOT link into the 128 KiB (or even the
      one-doubling 256 KiB) LMB BRAM alongside code + lwIP. Use only once
      the image has a home for it (QSPI-resident greybox via overlay_store
      is the architectural fix — flagged in firmware/platform/README.md;
      DDR staging is the v2 alternative).

Equivalent objcopy route (documented, not used — the C array keeps one
mechanism for both modes and needs no linker-symbol aliasing shim):
  mb-objcopy -I binary -O elf32-microblazeel -B microblaze \
      greybox_clear.bin greybox_clear.o
  (then a shim mapping _binary_*_start/_size onto the five extern names)

Usage:
  python3 gen_greybox_blob.py \
      [--manifest fpga/dfx/overlay/greybox/manifest.json] \
      [--bin fpga/dfx/overlay/greybox/greybox_clear.bin] \
      [--out firmware/platform/generated/greybox_blob.c] \
      [--mode placeholder|real]
If the manifest/bin are missing (fresh clone: overlay payloads are
gitignored, regenerate with `make -C fpga/dfx overlays`), placeholder mode
still works with identity 0 and says so loudly in the generated comment.
"""
import argparse
import json
import struct
import sys
import zlib
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

ICAP_NOP_WORD = 0x20000000  # 7-series/UltraScale type-1 NOP
PLACEHOLDER_WORDS = 64


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path,
                    default=REPO / "fpga/dfx/overlay/greybox/manifest.json")
    ap.add_argument("--bin", type=Path,
                    default=REPO / "fpga/dfx/overlay/greybox/greybox_clear.bin")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent / "generated/greybox_blob.c")
    ap.add_argument("--mode", choices=("placeholder", "real"), default="placeholder")
    args = ap.parse_args()

    static_id = 0
    rm_id = 0
    identity_src = "NOT PROVISIONED (manifest missing at generation time)"
    if args.manifest.is_file():
        m = json.loads(args.manifest.read_text())
        static_id = int(m["static_id"], 16)
        rm_id = int(m["rm_id"], 16)
        identity_src = str(args.manifest.relative_to(REPO)) if str(args.manifest).startswith(str(REPO)) else str(args.manifest)

    if args.mode == "real":
        if not args.bin.is_file():
            sys.exit(f"--mode real: {args.bin} not found "
                     "(regenerate with `make -C fpga/dfx overlays`)")
        payload = args.bin.read_bytes()
        if len(payload) % 4:
            sys.exit(f"{args.bin}: length {len(payload)} not word-aligned")
        payload_src = f"{args.bin.name} (REAL greybox clearing bitstream)"
    else:
        payload = struct.pack("<%dI" % PLACEHOLDER_WORDS,
                              *([ICAP_NOP_WORD] * PLACEHOLDER_WORDS))
        payload_src = (f"{PLACEHOLDER_WORDS} ICAP type-1 NOP words (PLACEHOLDER — "
                       "does NOT clear the RP; safe no-op if streamed)")

    crc = zlib.crc32(payload) & 0xFFFFFFFF
    len_words = len(payload) // 4

    lines = []
    a = lines.append
    a("/*")
    a(" * greybox_blob.c — GENERATED by firmware/platform/gen_greybox_blob.py.")
    a(" * DO NOT EDIT; regenerate instead (see that script's header for the")
    a(" * placeholder-vs-real story and the LMB-BRAM honesty note).")
    a(" *")
    a(f" * mode:     {args.mode}")
    a(f" * payload:  {payload_src}")
    a(f" * identity: {identity_src}")
    a(" */")
    a("#include <stdint.h>")
    a("")
    a("const uint8_t mps3_greybox_clearing_bin[] = {")
    for off in range(0, len(payload), 12):
        chunk = payload[off:off + 12]
        a("    " + " ".join(f"0x{b:02X}," for b in chunk))
    a("};")
    a("")
    a(f"const uint32_t mps3_greybox_clearing_len_words = {len_words}u;")
    a(f"const uint32_t mps3_greybox_clearing_crc32     = 0x{crc:08X}u;")
    a(f"const uint32_t mps3_greybox_clearing_rm_id     = 0x{rm_id:08X}u; /* rm_greybox */")
    a(f"const uint32_t mps3_greybox_clearing_static_id = 0x{static_id:08X}u;")
    a("")
    a("/* Strong override of coordinator.c's weak fallback (static_id seam,")
    a(" * coordinator.h): the shell identity `ping` reports and config_agent")
    a(" * matches pushed bitstream headers against. */")
    a("uint32_t mps3_shell_static_id(void)")
    a("{")
    a(f"    return 0x{static_id:08X}u;")
    a("}")
    a("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out}: mode={args.mode}, {len(payload)} payload bytes, "
          f"len_words={len_words}, crc32=0x{crc:08X}, static_id=0x{static_id:08X}")


if __name__ == "__main__":
    main()
