/*
 * mps3_version.h — the HARNESS VERSION seam (committed; hand-written).
 *
 * This is the header CALLERS include. It declares the mps3_harness_*()
 * accessors and the HARNESS_VER32 pack/unpack macros, and nothing else — no
 * build-specific constant lives here, so it never churns.
 *
 * ---------------------------------------------------------------------------
 * The seam (same shape as coordinator.h's mps3_shell_static_id())
 * ---------------------------------------------------------------------------
 *   WEAK fallback : firmware/platform/mps3_version_weak.c  (committed)
 *                   -> version 0.0.0, sha "unknown"  = "not provisioned"
 *   STRONG override: firmware/platform/generated/mps3_version.c (GENERATED by
 *                   scripts/gen_version.py, gitignored, regenerated every
 *                   firmware build)
 *
 * Weak-linking is what keeps this file identical between the MicroBlaze target
 * build and every host-gcc firmware/test/ binary: a test that links only the
 * weak TU still builds and links, exactly as firmware/test/ binaries do for
 * mps3_shell_static_id() today. It also means a fresh clone, before anything
 * has been generated, compiles.
 *
 * ---------------------------------------------------------------------------
 * HARNESS_VER32 — the packed encoding (docs/VERSIONING_PLAN.md §3.1)
 * ---------------------------------------------------------------------------
 *
 *    31           24 23           16 15            8 7             0
 *   +---------------+---------------+---------------+---------------+
 *   |     major     |     minor     |     patch     |     flags     |
 *   +---------------+---------------+---------------+---------------+
 *
 *   flags bit0      = dirty working tree at build time
 *   flags bits[7:1] = RESERVED, always 0
 *
 *   v1.4.2 clean -> 0x01040200          v1.4.2 dirty -> 0x01040201
 *
 * The SAME 32-bit value is stamped into the static bitstream's USR_ACCESS
 * (AXSS) configuration register by fpga/dfx/build_dfx.tcl. So:
 *
 *   - firmware reports it via mps3_harness_version()  (this seam), and
 *   - JTAG reports it via `get_property REGISTER.USR_ACCESS.SLR0
 *     [current_hw_device]` after refresh_hw_device — with NO firmware running.
 *
 * Those two agreeing is a live check against firmware/bitstream skew (the
 * "flashable base whose updatemem was never re-run" hazard). Those two
 * DISAGREEING means the .bit and the image inside it are from different builds.
 *
 * ---------------------------------------------------------------------------
 * This is NOT static_id, and does not replace it
 * ---------------------------------------------------------------------------
 *   static_id (coordinator.h, mps3_shell_static_id())
 *       CRC-32 of static_routed_locked.dcp. Answers "will this partial FIT this
 *       fabric?". A compatibility fingerprint. Unordered. Load-bearing: checked
 *       before every ICAP write.
 *   harness version (this file)
 *       Semantic release number. Answers "WHICH RELEASE is this?". Ordered.
 *       Provenance, not compatibility.
 *
 * They are orthogonal, and ONE static_id can serve SEVERAL harness versions: a
 * firmware-only bump changes the .bit (firmware is baked in via updatemem) but
 * not the static routing, so every fielded partial stays valid. Bumping VERSION
 * must therefore NEVER be expected to change static_id — that is correct
 * behaviour, not a bug.
 */
#ifndef MPS3_VERSION_H
#define MPS3_VERSION_H

#include <stdbool.h>
#include <stdint.h>

/* ---- HARNESS_VER32 pack / unpack ---------------------------------------- */

/** flags bit0: the working tree had uncommitted changes when this was built. */
#define MPS3_HARNESS_FLAG_DIRTY   0x01u

/** Pack a harness version. Mirrors scripts/gen_version.py's pack_ver32(); the
 *  two are pinned together by firmware/test/test_version.c.
 *
 *  NOTE the name: the PACKER is MPS3_HARNESS_PACK_VER32(). The bare name
 *  MPS3_HARNESS_VER32 is reserved for the generated object-like constant
 *  holding THIS build's packed value (generated/mps3_version.h) — the thing the
 *  docs and the USR_ACCESS stamp both call "HARNESS_VER32". Colliding the two
 *  is a -Wmacro-redefined error, which is how the split was found. */
#define MPS3_HARNESS_PACK_VER32(maj, min, pat, flags) \
    ((uint32_t)(((uint32_t)(maj)   & 0xFFu) << 24) | \
     (uint32_t)(((uint32_t)(min)   & 0xFFu) << 16) | \
     (uint32_t)(((uint32_t)(pat)   & 0xFFu) <<  8) | \
     (uint32_t)( (uint32_t)(flags) & 0xFFu))

#define MPS3_HARNESS_VER_MAJOR(v)  ((uint8_t)(((uint32_t)(v) >> 24) & 0xFFu))
#define MPS3_HARNESS_VER_MINOR(v)  ((uint8_t)(((uint32_t)(v) >> 16) & 0xFFu))
#define MPS3_HARNESS_VER_PATCH(v)  ((uint8_t)(((uint32_t)(v) >>  8) & 0xFFu))
#define MPS3_HARNESS_VER_FLAGS(v)  ((uint8_t)( (uint32_t)(v)        & 0xFFu))

/** True if HARNESS_VER32 `v` was built from a dirty tree. */
#define MPS3_HARNESS_VER_IS_DIRTY(v) \
    ((MPS3_HARNESS_VER_FLAGS(v) & MPS3_HARNESS_FLAG_DIRTY) != 0u)

/* ---- the accessors (weak fallback + generated strong override) ----------- */

/** Packed HARNESS_VER32 for this build. 0 = "not provisioned" (no generated
 *  identity linked) — the same convention mps3_shell_static_id() uses. */
uint32_t mps3_harness_version(void);

/** "1.4.2" — the harness semantic version. "0.0.0" when not provisioned. */
const char *mps3_harness_version_str(void);

/** "a1b2c3d4" — 8 hex chars of the build commit. "unknown" when not
 *  provisioned or when built outside a git checkout. */
const char *mps3_harness_git_sha(void);

/** True if the working tree had uncommitted changes at build time. Equivalent
 *  to MPS3_HARNESS_VER_IS_DIRTY(mps3_harness_version()); provided as a function
 *  so a caller holding no ver32 need not unpack one. */
bool mps3_harness_dirty(void);

/** "2026-07-14" (UTC). "unknown" when not provisioned. */
const char *mps3_harness_build_date(void);

/* ---- THE OTHER HALF OF THE CROSS-CHECK: what the FABRIC says --------------
 *
 * Everything above answers "what was this IMAGE built as". This answers "what
 * is the bitstream the image is running INSIDE", by reading the AXSS
 * configuration register back out of the fabric through USRACC
 * (fpga/shell/ip/usr_access_rd/, docs/VERSIONING_PLAN.md §3.4). Declared HERE
 * because it is the counterpart of mps3_harness_version() and this header
 * already explains, at length, why the two agreeing matters -- and because
 * firmware/coordinator/coordinator.c already includes this file, so the whole
 * change in that file is ONE line.
 *
 * Writes "0x" + 8 lowercase hex digits, or "" (empty) if the fabric value
 * could not be read -- which is a THIRD state, not a pass:
 *
 *   - a shell built WITHOUT the USRACC block (every shell up to and including
 *     0xA8C1C535): the page is unmapped, reads 0, and USRACC_MAGIC does not
 *     match. Empty.
 *   - the block is there but the primitive has not presented DATAVALID yet:
 *     USRACC_STATUS.VALID is low. Empty.
 *   - otherwise: the word.
 *
 * The empty case is what makes net_proto.c emit `"usr_access":null,"skew":null`
 * instead of a comparison it did not make. A zero here, or a `false` skew with
 * no value, would read as "checked, fine" -- the one answer this must never
 * give for a check that did not happen.
 *
 * RENDERING IS LOAD-BEARING: the codec derives the skew verdict by comparing
 * this string against the `ver32` string, so this must format IDENTICALLY to
 * coordinator.c's format_id_hex(). That is not left to inspection -- a drift in
 * either formatter makes an AGREEING board report skew, which is exactly what
 * firmware/test/test_coordinator_dispatch.c's skew-false case asserts.
 *
 * Defined in firmware/platform/mps3_usr_access.c (it needs platform_regs.h, so
 * it cannot live in the register-free common/ files).
 */
void mps3_fabric_usr_access_str(char *dst, unsigned dst_sz);

#endif /* MPS3_VERSION_H */
