##############################################################################
# nanosoc_mps3.xdc -- monolithic nanoSoC-on-MPS3 baseline constraints
#
# Ported from the legacy single-core nanoSoC arm_mps3 FPGA target (2021.1):
#   nanosoc-multicore-system/nanosoc_arch_tech/fpga/fpga/targets/arm_mps3/
#     fpga_pinmap.xdc   (pin/IOSTANDARD/PULLUP assignments, MPS3 Rev-C SMM wrapper)
#     fpga_timing.xdc   (board input/output clocks)
# Target: Vivado 2024.1, part xcku115-flvb1760-1-c (Arm MPS3, Kintex UltraScale)
#
# Every pin/IOSTANDARD/PULLUP value below is copied verbatim from the legacy
# file (same PACKAGE_PIN letter-codes -- KU115 package pinout is unchanged
# between Vivado versions); only the ORGANIZATION changed: pins are grouped by
# board subsystem (matching nanosoc_design_wrapper.v's port list) with a
# provenance comment per group instead of the legacy file's single flat,
# alphabetically-interleaved list. No 2021.1->2024.1 XDC syntax is deprecated
# here (set_property/get_ports/create_clock/set_input_delay/set_output_delay
# are all unchanged); the only real port work is on the .tcl build script, see
# build_monolithic.tcl for the flagged deprecations there.
#
# Scope: this file constrains every port on nanosoc_design_wrapper.v (the
# legacy top). Most groups below (CLCD/HDMI/Audio/eMMC/MMB/QSPI/USD/shield)
# are DECLARED ports that the wrapper ties off or leaves unconnected -- nanosoc
# itself only drives/reads UART_TX_F[2]/UART_RX_F[2], OSCCLK[1] (ACLK), and
# CB_nRST/CS_nSRST (reset). They are constrained anyway because Vivado requires
# every top-level port to have a legal site/standard before bitstream generation
# on a board wrapper (SMM-style) target.
##############################################################################

#------------------------------------------------------------------------------
# LAN9220 Ethernet SMC interface (10/100, promiscuous on real HW)
# Provenance: fpga_pinmap.xdc lines ~37-39, ~319-321 (ETH_*); shares the SMBF_* static-memory-controller bus below
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AL24 [get_ports ETH_nCS]
set_property IOSTANDARD LVCMOS18 [get_ports ETH_nCS]
set_property PACKAGE_PIN AJ23 [get_ports ETH_nOE]
set_property IOSTANDARD LVCMOS18 [get_ports ETH_nOE]
set_property PACKAGE_PIN AK23 [get_ports ETH_INT]
set_property IOSTANDARD LVCMOS18 [get_ports ETH_INT]

#------------------------------------------------------------------------------
# SMBF_* static memory bus (FPGA-side SMC master; carries LAN9220 + USB debug FIFO on the same 16-bit mux)
# Provenance: fpga_pinmap.xdc lines ~10-39 (IOSTANDARD), ~639-665 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AK20 [get_ports {SMBF_ADDR[0]}]
set_property PACKAGE_PIN AK21 [get_ports {SMBF_ADDR[1]}]
set_property PACKAGE_PIN AJ18 [get_ports {SMBF_ADDR[2]}]
set_property PACKAGE_PIN AJ19 [get_ports {SMBF_ADDR[3]}]
set_property PACKAGE_PIN AH21 [get_ports {SMBF_ADDR[4]}]
set_property PACKAGE_PIN AJ21 [get_ports {SMBF_ADDR[5]}]
set_property PACKAGE_PIN AH19 [get_ports {SMBF_ADDR[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[0]}]
set_property PACKAGE_PIN AK22 [get_ports {SMBF_DATA[0]}]
set_property PACKAGE_PIN AL22 [get_ports {SMBF_DATA[1]}]
set_property PACKAGE_PIN AL19 [get_ports {SMBF_DATA[2]}]
set_property PACKAGE_PIN AL20 [get_ports {SMBF_DATA[3]}]
set_property PACKAGE_PIN AH18 [get_ports {SMBF_DATA[4]}]
set_property PACKAGE_PIN AM19 [get_ports {SMBF_DATA[5]}]
set_property PACKAGE_PIN AN19 [get_ports {SMBF_DATA[6]}]
set_property PACKAGE_PIN AP19 [get_ports {SMBF_DATA[7]}]
set_property PACKAGE_PIN AP20 [get_ports {SMBF_DATA[8]}]
set_property PACKAGE_PIN AM20 [get_ports {SMBF_DATA[9]}]
set_property PACKAGE_PIN AN21 [get_ports {SMBF_DATA[10]}]
set_property PACKAGE_PIN AP21 [get_ports {SMBF_DATA[11]}]
set_property PACKAGE_PIN AR22 [get_ports {SMBF_DATA[12]}]
set_property PACKAGE_PIN AM21 [get_ports {SMBF_DATA[13]}]
set_property PACKAGE_PIN AM22 [get_ports {SMBF_DATA[14]}]
set_property PACKAGE_PIN AN22 [get_ports {SMBF_DATA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[0]}]
set_property PACKAGE_PIN AJ20 [get_ports SMBF_FIFOSEL]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_FIFOSEL]
set_property PACKAGE_PIN AN23 [get_ports SMBF_nOE]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_nOE]
set_property PACKAGE_PIN AP23 [get_ports SMBF_nWE]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_nWE]
set_property PACKAGE_PIN AL23 [get_ports SMBF_nRST]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_nRST]

#------------------------------------------------------------------------------
# USB debug/trace FIFO (shares SMBF_* bus with the LAN9220 chip-select decode)
# Provenance: fpga_pinmap.xdc lines ~40-43 (IOSTANDARD), ~745-748 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AM26 [get_ports USB_nCS]
set_property IOSTANDARD LVCMOS18 [get_ports USB_nCS]
set_property PACKAGE_PIN AN26 [get_ports USB_DACK]
set_property IOSTANDARD LVCMOS18 [get_ports USB_DACK]
set_property PACKAGE_PIN AN24 [get_ports USB_DREQ]
set_property IOSTANDARD LVCMOS18 [get_ports USB_DREQ]
set_property PACKAGE_PIN AP24 [get_ports USB_INT]
set_property IOSTANDARD LVCMOS18 [get_ports USB_INT]

#------------------------------------------------------------------------------
# UART_TX_F/UART_RX_F -- 4 FPGA-side UART lanes; lane [2] is the one wired to nanosoc's cmsdk_apb_usrt in nanosoc_design_wrapper.v
# Provenance: fpga_pinmap.xdc line 1 + ~114-121 (IOSTANDARD), ~738-744 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AD28 [get_ports {UART_TX_F[2]}]
set_property PACKAGE_PIN AF27 [get_ports {UART_TX_F[0]}]
set_property PACKAGE_PIN AE30 [get_ports {UART_TX_F[1]}]
set_property PACKAGE_PIN AD29 [get_ports {UART_TX_F[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[0]}]
set_property PACKAGE_PIN AF28 [get_ports {UART_RX_F[0]}]
set_property PACKAGE_PIN AE31 [get_ports {UART_RX_F[1]}]
set_property PACKAGE_PIN AE28 [get_ports {UART_RX_F[2]}]
set_property PACKAGE_PIN AD30 [get_ports {UART_RX_F[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[0]}]

#------------------------------------------------------------------------------
# CoreSight debug: CS_TDI/TDO/TMS/TCK (JTAG-DP), CS_nSRST/nTRST/nDET, CS_T_* trace port
# Provenance: fpga_pinmap.xdc lines ~85-109 (IOSTANDARD), ~244-268 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN BA35 [get_ports CS_TDI]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TDI]
set_property PACKAGE_PIN AW38 [get_ports CS_TDO]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TDO]
set_property PACKAGE_PIN AY38 [get_ports CS_TMS]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TMS]
set_property PACKAGE_PIN AV33 [get_ports CS_TCK]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TCK]
set_property PACKAGE_PIN BB36 [get_ports CS_nSRST]
set_property IOSTANDARD LVCMOS18 [get_ports CS_nSRST]
set_property PACKAGE_PIN BB37 [get_ports CS_nTRST]
set_property IOSTANDARD LVCMOS18 [get_ports CS_nTRST]
set_property PACKAGE_PIN BB39 [get_ports CS_nDET]
set_property IOSTANDARD LVCMOS18 [get_ports CS_nDET]
set_property PACKAGE_PIN AW34 [get_ports {CS_T_D[0]}]
set_property PACKAGE_PIN AT34 [get_ports {CS_T_D[1]}]
set_property PACKAGE_PIN AU34 [get_ports {CS_T_D[2]}]
set_property PACKAGE_PIN AV36 [get_ports {CS_T_D[3]}]
set_property PACKAGE_PIN AW36 [get_ports {CS_T_D[4]}]
set_property PACKAGE_PIN AT35 [get_ports {CS_T_D[5]}]
set_property PACKAGE_PIN AU35 [get_ports {CS_T_D[6]}]
set_property PACKAGE_PIN AU36 [get_ports {CS_T_D[7]}]
set_property PACKAGE_PIN AV37 [get_ports {CS_T_D[8]}]
set_property PACKAGE_PIN AW35 [get_ports {CS_T_D[9]}]
set_property PACKAGE_PIN AY36 [get_ports {CS_T_D[10]}]
set_property PACKAGE_PIN AY37 [get_ports {CS_T_D[11]}]
set_property PACKAGE_PIN BB34 [get_ports {CS_T_D[12]}]
set_property PACKAGE_PIN BB35 [get_ports {CS_T_D[13]}]
set_property PACKAGE_PIN BA37 [get_ports {CS_T_D[14]}]
set_property PACKAGE_PIN BA38 [get_ports {CS_T_D[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[0]}]
set_property PACKAGE_PIN AW33 [get_ports CS_T_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CS_T_CLK]
set_property PACKAGE_PIN AY35 [get_ports CS_T_CTL]
set_property IOSTANDARD LVCMOS18 [get_ports CS_T_CTL]

#------------------------------------------------------------------------------
# USER_nLED / USER_SW / USER_nPB -- MPS3 shield LEDs / DIP switches / push-buttons
# Provenance: fpga_pinmap.xdc lines ~62-81 (IOSTANDARD), ~763-782 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AU32 [get_ports {USER_nLED[0]}]
set_property PACKAGE_PIN AU30 [get_ports {USER_nLED[1]}]
set_property PACKAGE_PIN AU31 [get_ports {USER_nLED[2]}]
set_property PACKAGE_PIN AR32 [get_ports {USER_nLED[3]}]
set_property PACKAGE_PIN AT33 [get_ports {USER_nLED[4]}]
set_property PACKAGE_PIN AW30 [get_ports {USER_nLED[5]}]
set_property PACKAGE_PIN AW31 [get_ports {USER_nLED[6]}]
set_property PACKAGE_PIN AR30 [get_ports {USER_nLED[7]}]
set_property PACKAGE_PIN BB31 [get_ports {USER_nLED[8]}]
set_property PACKAGE_PIN BB32 [get_ports {USER_nLED[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[0]}]
set_property PACKAGE_PIN BA29 [get_ports {USER_SW[0]}]
set_property PACKAGE_PIN BB29 [get_ports {USER_SW[1]}]
set_property PACKAGE_PIN BA32 [get_ports {USER_SW[2]}]
set_property PACKAGE_PIN BA33 [get_ports {USER_SW[3]}]
set_property PACKAGE_PIN BA30 [get_ports {USER_SW[4]}]
set_property PACKAGE_PIN BB30 [get_ports {USER_SW[5]}]
set_property PACKAGE_PIN AY33 [get_ports {USER_SW[6]}]
set_property PACKAGE_PIN AY31 [get_ports {USER_SW[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[0]}]
set_property PACKAGE_PIN AT30 [get_ports {USER_nPB[0]}]
set_property PACKAGE_PIN AT32 [get_ports {USER_nPB[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nPB[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nPB[0]}]

#------------------------------------------------------------------------------
# OSCCLK[5:0] -- MPS3 SCC-generated reference clocks. [1]=ACLK 50 MHz (nanosoc's EXT_CLK), [2]=BCLK, [0]=REFCLK24MHZ
# Provenance: fpga_pinmap.xdc lines ~123-128 (IOSTANDARD), ~538-543 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AL15 [get_ports {OSCCLK[0]}]
set_property PACKAGE_PIN AK16 [get_ports {OSCCLK[1]}]
set_property PACKAGE_PIN AY32 [get_ports {OSCCLK[2]}]
set_property PACKAGE_PIN AY30 [get_ports {OSCCLK[3]}]
set_property PACKAGE_PIN AC31 [get_ports {OSCCLK[4]}]
set_property PACKAGE_PIN AC32 [get_ports {OSCCLK[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[0]}]

#------------------------------------------------------------------------------
# Quad SPI boot/overlay flash (SST26VF064B) -- NOT used by the monolithic bitstream logic (tied off in the wrapper); constrained so the pins are legally assigned
# Provenance: fpga_pinmap.xdc lines ~546-557 (IOSTANDARD+PACKAGE_PIN), ~970-973 (PULLUP)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AU24 [get_ports QSPI_D0]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D0]
set_property PULLUP true [get_ports QSPI_D0]
set_property PACKAGE_PIN AV24 [get_ports QSPI_D1]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D1]
set_property PULLUP true [get_ports QSPI_D1]
set_property PACKAGE_PIN AV21 [get_ports QSPI_D2]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D2]
set_property PULLUP true [get_ports QSPI_D2]
set_property PACKAGE_PIN AV22 [get_ports QSPI_D3]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D3]
set_property PULLUP true [get_ports QSPI_D3]
set_property PACKAGE_PIN AT25 [get_ports QSPI_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_SCLK]
set_property PACKAGE_PIN AT24 [get_ports QSPI_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_nCS]

#------------------------------------------------------------------------------
# User microSD interface (FPGA-wired per MPS3 TRM Sec 2.15) -- unused by this baseline, constrained only
# Provenance: fpga_pinmap.xdc lines ~749-762
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AV14 [get_ports {USD_DAT[0]}]
set_property PACKAGE_PIN AV13 [get_ports {USD_DAT[1]}]
set_property PACKAGE_PIN AT13 [get_ports {USD_DAT[2]}]
set_property PACKAGE_PIN AT12 [get_ports {USD_DAT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[3]}]
set_property PACKAGE_PIN AU16 [get_ports USD_CMD]
set_property IOSTANDARD LVCMOS33 [get_ports USD_CMD]
set_property PACKAGE_PIN AU15 [get_ports USD_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports USD_CLK]
set_property PACKAGE_PIN AT15 [get_ports USD_NCD]
set_property IOSTANDARD LVCMOS33 [get_ports USD_NCD]

#------------------------------------------------------------------------------
# Board-level reset/run signals from the MCC (CB_*) and IO-FPGA supervisor
# Provenance: fpga_pinmap.xdc lines ~197-202 (CB_*), ~429-434 (IOFPGA_*), ~544 (PB_IRQ), ~783-784 (WDOG_RREQ)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AU22 [get_ports CB_nPOR]
set_property IOSTANDARD LVCMOS33 [get_ports CB_nPOR]
set_property PACKAGE_PIN AV23 [get_ports CB_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports CB_nRST]
set_property PACKAGE_PIN AR25 [get_ports CB_RUN]
set_property IOSTANDARD LVCMOS33 [get_ports CB_RUN]
set_property PACKAGE_PIN AV31 [get_ports IOFPGA_NRST]
set_property IOSTANDARD LVCMOS18 [get_ports IOFPGA_NRST]
set_property PACKAGE_PIN AV32 [get_ports IOFPGA_NSPIR]
set_property IOSTANDARD LVCMOS18 [get_ports IOFPGA_NSPIR]
set_property PACKAGE_PIN AU20 [get_ports IOFPGA_SYSWDT]
set_property IOSTANDARD LVCMOS33 [get_ports IOFPGA_SYSWDT]
set_property PACKAGE_PIN AT29 [get_ports PB_IRQ]
set_property PACKAGE_PIN AU19 [get_ports WDOG_RREQ]
set_property IOSTANDARD LVCMOS33 [get_ports WDOG_RREQ]

#------------------------------------------------------------------------------
# SCC (System Configuration Controller) serial config bus -- MCC-side board bring-up, tied off in the wrapper
# Provenance: fpga_pinmap.xdc lines ~203-214
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AV18 [get_ports CFG_DATAOUT]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_DATAOUT]
set_property PACKAGE_PIN AW18 [get_ports CFG_LOAD]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_LOAD]
set_property PACKAGE_PIN AR20 [get_ports CFG_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_nRST]
set_property PACKAGE_PIN AT20 [get_ports CFG_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_CLK]
set_property PACKAGE_PIN AT19 [get_ports CFG_DATAIN]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_DATAIN]
set_property PACKAGE_PIN AT18 [get_ports CFG_WnR]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_WnR]

#------------------------------------------------------------------------------
# MCC SMB backdoor bus (MCC <-> FPGA-design memory-mapped access, DEPOSIT/EXAM)
# Provenance: fpga_pinmap.xdc lines ~666-737
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AR26 [get_ports {SMBM_A[16]}]
set_property PACKAGE_PIN AT22 [get_ports {SMBM_A[17]}]
set_property PACKAGE_PIN AT23 [get_ports {SMBM_A[18]}]
set_property PACKAGE_PIN AU21 [get_ports {SMBM_A[19]}]
set_property PACKAGE_PIN AY22 [get_ports {SMBM_A[20]}]
set_property PACKAGE_PIN BA22 [get_ports {SMBM_A[21]}]
set_property PACKAGE_PIN AW21 [get_ports {SMBM_A[22]}]
set_property PACKAGE_PIN AY21 [get_ports {SMBM_A[23]}]
set_property PACKAGE_PIN BA23 [get_ports {SMBM_A[24]}]
set_property PACKAGE_PIN BA24 [get_ports {SMBM_A[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[25]}]
set_property PACKAGE_PIN BB21 [get_ports {SMBM_D[0]}]
set_property PACKAGE_PIN BB22 [get_ports {SMBM_D[1]}]
set_property PACKAGE_PIN AW24 [get_ports {SMBM_D[2]}]
set_property PACKAGE_PIN AW25 [get_ports {SMBM_D[3]}]
set_property PACKAGE_PIN AW23 [get_ports {SMBM_D[4]}]
set_property PACKAGE_PIN AY23 [get_ports {SMBM_D[5]}]
set_property PACKAGE_PIN BB24 [get_ports {SMBM_D[6]}]
set_property PACKAGE_PIN AY27 [get_ports {SMBM_D[7]}]
set_property PACKAGE_PIN AY26 [get_ports {SMBM_D[8]}]
set_property PACKAGE_PIN AY28 [get_ports {SMBM_D[9]}]
set_property PACKAGE_PIN BA28 [get_ports {SMBM_D[10]}]
set_property PACKAGE_PIN BA25 [get_ports {SMBM_D[11]}]
set_property PACKAGE_PIN BB25 [get_ports {SMBM_D[12]}]
set_property PACKAGE_PIN AW28 [get_ports {SMBM_D[13]}]
set_property PACKAGE_PIN AW29 [get_ports {SMBM_D[14]}]
set_property PACKAGE_PIN BB26 [get_ports {SMBM_D[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[15]}]
set_property PACKAGE_PIN BB27 [get_ports {SMBM_nE[1]}]
set_property PACKAGE_PIN AU27 [get_ports {SMBM_nE[2]}]
set_property PACKAGE_PIN AV28 [get_ports {SMBM_nE[3]}]
set_property PACKAGE_PIN AU25 [get_ports {SMBM_nE[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[4]}]
set_property PACKAGE_PIN AY25 [get_ports SMBM_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_CLK]
set_property PACKAGE_PIN AU26 [get_ports {SMBM_nBL[0]}]
set_property PACKAGE_PIN AR28 [get_ports {SMBM_nBL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nBL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nBL[1]}]
set_property PACKAGE_PIN AT28 [get_ports SMBM_nOE]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_nOE]
set_property PACKAGE_PIN AR27 [get_ports SMBM_nWE]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_nWE]
set_property PACKAGE_PIN AP28 [get_ports SMBM_nWAIT]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_nWAIT]

#------------------------------------------------------------------------------
# Arduino-style shield header SH0_IO/SH1_IO + on-shield ADC SPI -- carries the PMOD0 debug/ADP-injection path wired in nanosoc_design_wrapper.v (SWDIO/SWCLK, FT1248 bit-bang)
# Provenance: fpga_pinmap.xdc lines ~561-638
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AW14 [get_ports {SH0_IO[0]}]
set_property PACKAGE_PIN AW13 [get_ports {SH0_IO[1]}]
set_property PACKAGE_PIN AW15 [get_ports {SH0_IO[2]}]
set_property PACKAGE_PIN AY15 [get_ports {SH0_IO[3]}]
set_property PACKAGE_PIN AY13 [get_ports {SH0_IO[4]}]
set_property PACKAGE_PIN AY12 [get_ports {SH0_IO[5]}]
set_property PACKAGE_PIN BA15 [get_ports {SH0_IO[6]}]
set_property PACKAGE_PIN BB14 [get_ports {SH0_IO[7]}]
set_property PACKAGE_PIN BA12 [get_ports {SH0_IO[8]}]
set_property PACKAGE_PIN BB12 [get_ports {SH0_IO[9]}]
set_property PACKAGE_PIN BA14 [get_ports {SH0_IO[10]}]
set_property PACKAGE_PIN BA13 [get_ports {SH0_IO[11]}]
set_property PACKAGE_PIN BB15 [get_ports {SH0_IO[12]}]
set_property PACKAGE_PIN AU12 [get_ports {SH0_IO[13]}]
set_property PACKAGE_PIN AV12 [get_ports {SH0_IO[14]}]
set_property PACKAGE_PIN AV17 [get_ports {SH0_IO[15]}]
set_property PACKAGE_PIN AV16 [get_ports {SH0_IO[16]}]
set_property PACKAGE_PIN AT14 [get_ports {SH0_IO[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[17]}]
set_property PACKAGE_PIN AT17 [get_ports {SH1_IO[0]}]
set_property PACKAGE_PIN AU17 [get_ports {SH1_IO[1]}]
set_property PACKAGE_PIN AV19 [get_ports {SH1_IO[2]}]
set_property PACKAGE_PIN AW19 [get_ports {SH1_IO[3]}]
set_property PACKAGE_PIN AW20 [get_ports {SH1_IO[4]}]
set_property PACKAGE_PIN BA19 [get_ports {SH1_IO[5]}]
set_property PACKAGE_PIN BA18 [get_ports {SH1_IO[6]}]
set_property PACKAGE_PIN AY20 [get_ports {SH1_IO[7]}]
set_property PACKAGE_PIN BA20 [get_ports {SH1_IO[8]}]
set_property PACKAGE_PIN BA17 [get_ports {SH1_IO[9]}]
set_property PACKAGE_PIN BB17 [get_ports {SH1_IO[10]}]
set_property PACKAGE_PIN BB20 [get_ports {SH1_IO[11]}]
set_property PACKAGE_PIN BB19 [get_ports {SH1_IO[12]}]
set_property PACKAGE_PIN AW16 [get_ports {SH1_IO[13]}]
set_property PACKAGE_PIN AY16 [get_ports {SH1_IO[14]}]
set_property PACKAGE_PIN AY18 [get_ports {SH1_IO[15]}]
set_property PACKAGE_PIN AY17 [get_ports {SH1_IO[16]}]
set_property PACKAGE_PIN BB16 [get_ports {SH1_IO[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[17]}]
set_property PACKAGE_PIN AU14 [get_ports SH_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports SH_nRST]
set_property PACKAGE_PIN AM25 [get_ports SH_ADC_CS]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_CS]
set_property PACKAGE_PIN AL25 [get_ports SH_ADC_CK]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_CK]
set_property PACKAGE_PIN AP25 [get_ports SH_ADC_DI]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_DI]
set_property PACKAGE_PIN AP26 [get_ports SH_ADC_DO]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_DO]

#------------------------------------------------------------------------------
# CLCD (character/graphics LCD) parallel interface -- unused, tied off (CLCD_BL=0 in wrapper)
# Provenance: fpga_pinmap.xdc lines ~44-61 (IOSTANDARD), ~215-234 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AN17 [get_ports {CLCD_PD[10]}]
set_property PACKAGE_PIN AP16 [get_ports {CLCD_PD[11]}]
set_property PACKAGE_PIN AP18 [get_ports {CLCD_PD[12]}]
set_property PACKAGE_PIN AR18 [get_ports {CLCD_PD[13]}]
set_property PACKAGE_PIN AM16 [get_ports {CLCD_PD[14]}]
set_property PACKAGE_PIN AN16 [get_ports {CLCD_PD[15]}]
set_property PACKAGE_PIN AR17 [get_ports {CLCD_PD[16]}]
set_property PACKAGE_PIN AR16 [get_ports {CLCD_PD[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[10]}]
set_property PACKAGE_PIN AM15 [get_ports CLCD_RD]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_RD]
set_property PACKAGE_PIN AN14 [get_ports CLCD_RS]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_RS]
set_property PACKAGE_PIN AP15 [get_ports CLCD_CS]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_CS]
set_property PACKAGE_PIN AP14 [get_ports CLCD_WR_SCL]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_WR_SCL]
set_property PACKAGE_PIN AJ16 [get_ports CLCD_BL]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_BL]
set_property PACKAGE_PIN AK18 [get_ports CLCD_RST]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_RST]
set_property PACKAGE_PIN AL18 [get_ports CLCD_TSCL]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TSCL]
set_property PACKAGE_PIN AJ15 [get_ports CLCD_TSDA]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TSDA]
set_property PACKAGE_PIN AJ14 [get_ports CLCD_TINT]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TINT]
set_property PACKAGE_PIN AL17 [get_ports CLCD_TNC]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TNC]

#------------------------------------------------------------------------------
# HDMI CEC/DDC side-channel -- unused, present only because the wrapper declares the port
# Provenance: fpga_pinmap.xdc lines ~82-84, ~304-306
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AG34 [get_ports HDMI_CSCL]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_CSCL]
set_property PACKAGE_PIN AE33 [get_ports HDMI_CSDA]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_CSDA]
set_property PACKAGE_PIN AF33 [get_ports HDMI_INT]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_INT]

#------------------------------------------------------------------------------
# Audio codec I2S + I2C control -- unused, present only because the wrapper declares the port
# Provenance: fpga_pinmap.xdc lines ~181-196
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AB29 [get_ports AUD_MCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_MCLK]
set_property PACKAGE_PIN AB30 [get_ports AUD_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SCLK]
set_property PACKAGE_PIN Y30 [get_ports AUD_LRCK]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_LRCK]
set_property PACKAGE_PIN AA30 [get_ports AUD_SDIN]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SDIN]
set_property PACKAGE_PIN Y27 [get_ports AUD_SDOUT]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SDOUT]
set_property PACKAGE_PIN AA27 [get_ports AUD_nRST]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_nRST]
set_property PACKAGE_PIN AA28 [get_ports AUD_SCL]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SCL]
set_property PACKAGE_PIN AA29 [get_ports AUD_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SDA]

#------------------------------------------------------------------------------
# eMMC interface -- unused, tied off (EMMC_CLK=0 in wrapper)
# Provenance: fpga_pinmap.xdc lines ~163-174 (IOSTANDARD), ~307-318 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN Y32 [get_ports {EMMC_DAT[0]}]
set_property PACKAGE_PIN Y33 [get_ports {EMMC_DAT[1]}]
set_property PACKAGE_PIN W33 [get_ports {EMMC_DAT[2]}]
set_property PACKAGE_PIN W34 [get_ports {EMMC_DAT[3]}]
set_property PACKAGE_PIN AA34 [get_ports {EMMC_DAT[4]}]
set_property PACKAGE_PIN AB34 [get_ports {EMMC_DAT[5]}]
set_property PACKAGE_PIN W31 [get_ports {EMMC_DAT[6]}]
set_property PACKAGE_PIN Y31 [get_ports {EMMC_DAT[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[0]}]
set_property PACKAGE_PIN AC34 [get_ports EMMC_CMD]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_CMD]
set_property PACKAGE_PIN W29 [get_ports EMMC_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_CLK]
set_property PACKAGE_PIN W30 [get_ports EMMC_nRST]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_nRST]
set_property PACKAGE_PIN AE32 [get_ports EMMC_DS]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_DS]

#------------------------------------------------------------------------------
# MMB (motherboard multimedia bus, parallel video-out) -- unused, tied off (MMB_IDCLK=0 in wrapper)
# Provenance: fpga_pinmap.xdc lines ~129-162 (IOSTANDARD), ~504-537 (PACKAGE_PIN)
#------------------------------------------------------------------------------
set_property PACKAGE_PIN AM17 [get_ports {MMB_DATA[0]}]
set_property PACKAGE_PIN AL14 [get_ports {MMB_DATA[1]}]
set_property PACKAGE_PIN AK15 [get_ports {MMB_DATA[2]}]
set_property PACKAGE_PIN AK17 [get_ports {MMB_DATA[3]}]
set_property PACKAGE_PIN AM14 [get_ports {MMB_DATA[4]}]
set_property PACKAGE_PIN AN13 [get_ports {MMB_DATA[5]}]
set_property PACKAGE_PIN AM11 [get_ports {MMB_DATA[6]}]
set_property PACKAGE_PIN AN11 [get_ports {MMB_DATA[7]}]
set_property PACKAGE_PIN AR13 [get_ports {MMB_DATA[8]}]
set_property PACKAGE_PIN AR12 [get_ports {MMB_DATA[9]}]
set_property PACKAGE_PIN AL10 [get_ports {MMB_DATA[10]}]
set_property PACKAGE_PIN AM10 [get_ports {MMB_DATA[11]}]
set_property PACKAGE_PIN AM12 [get_ports {MMB_DATA[12]}]
set_property PACKAGE_PIN AN12 [get_ports {MMB_DATA[13]}]
set_property PACKAGE_PIN AP13 [get_ports {MMB_DATA[14]}]
set_property PACKAGE_PIN AK13 [get_ports {MMB_DATA[15]}]
set_property PACKAGE_PIN AK12 [get_ports {MMB_DATA[16]}]
set_property PACKAGE_PIN AK11 [get_ports {MMB_DATA[17]}]
set_property PACKAGE_PIN AK10 [get_ports {MMB_DATA[18]}]
set_property PACKAGE_PIN AH13 [get_ports {MMB_DATA[19]}]
set_property PACKAGE_PIN AJ13 [get_ports {MMB_DATA[20]}]
set_property PACKAGE_PIN AJ11 [get_ports {MMB_DATA[21]}]
set_property PACKAGE_PIN AJ10 [get_ports {MMB_DATA[22]}]
set_property PACKAGE_PIN AH12 [get_ports {MMB_DATA[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[0]}]
set_property PACKAGE_PIN AH11 [get_ports MMB_DE]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_DE]
set_property PACKAGE_PIN AG12 [get_ports MMB_HS]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_HS]
set_property PACKAGE_PIN AG11 [get_ports MMB_VS]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_VS]
set_property PACKAGE_PIN AH14 [get_ports MMB_IDCLK]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_IDCLK]
set_property PACKAGE_PIN AF29 [get_ports MMB_SCK]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_SCK]
set_property PACKAGE_PIN AF30 [get_ports MMB_WS]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_WS]
set_property PACKAGE_PIN AC28 [get_ports {MMB_SD[0]}]
set_property PACKAGE_PIN AC29 [get_ports {MMB_SD[1]}]
set_property PACKAGE_PIN AE27 [get_ports {MMB_SD[2]}]
set_property PACKAGE_PIN AF34 [get_ports {MMB_SD[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[0]}]

#------------------------------------------------------------------------------
# Bitstream / config-mode properties (current_design)
# Provenance: fpga_pinmap.xdc lines ~978-984
# NOTE (platform invariant, see docs/ARCHITECTURE_SPEC.md + README.md):
#   BITSTREAM.CONFIG.PERSIST=Yes is carried over unchanged from the legacy
#   monolithic target -- this is fine for THIS whole-FPGA, MCC-loaded,
#   no-ICAP bitstream. It must NOT be reused verbatim in the DFX shell build
#   (fpga/shell/): PERSIST is mutually exclusive with ICAP there.
#------------------------------------------------------------------------------
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]
set_property BITSTREAM.CONFIG.PERSIST Yes [current_design]
set_property BITSTREAM.STARTUP.MATCH_CYCLE Auto [current_design]
set_property BITSTREAM.GENERAL.COMPRESS True [current_design]
set_property CONFIG_MODE S_SELECTMAP [current_design]

#------------------------------------------------------------------------------
# Timing constraints
# Provenance: fpga_timing.xdc (verbatim, Arm MPS3 Rev-C timing XDC)
#------------------------------------------------------------------------------
create_clock -period 100.000 -name CS_TCK -waveform {0.000 50.000} [get_ports CS_TCK]
create_clock -period 20.000 -name {OSCCLK[1]} -waveform {0.000 10.000} [get_ports {OSCCLK[1]}]
set_input_delay -clock [get_clocks {OSCCLK[1]}] -min -add_delay 11.000 [get_ports {UART_RX_F[*]}]
set_input_delay -clock [get_clocks {OSCCLK[1]}] -max -add_delay 15.000 [get_ports {UART_RX_F[*]}]
set_input_delay -clock [get_clocks {OSCCLK[1]}] -min -add_delay 11.000 [get_ports CB_nRST]
set_input_delay -clock [get_clocks {OSCCLK[1]}] -max -add_delay 15.000 [get_ports CB_nRST]
set_input_delay -clock [get_clocks CS_TCK] -min -add_delay 5.000 [get_ports CS_TMS]
set_input_delay -clock [get_clocks CS_TCK] -max -add_delay 9.000 [get_ports CS_TMS]
set_input_delay -clock [get_clocks {OSCCLK[1]}] -min -add_delay 11.000 [get_ports CS_nSRST]
set_input_delay -clock [get_clocks {OSCCLK[1]}] -max -add_delay 15.000 [get_ports CS_nSRST]
set_output_delay -clock [get_clocks {OSCCLK[1]}] -min -add_delay -5.000 [get_ports {SH0_IO[*]}]
set_output_delay -clock [get_clocks {OSCCLK[1]}] -max -add_delay 15.000 [get_ports {SH0_IO[*]}]
set_output_delay -clock [get_clocks {OSCCLK[1]}] -min -add_delay 0.000 [get_ports {UART_TX_F[*]}]
set_output_delay -clock [get_clocks {OSCCLK[1]}] -max -add_delay 6.000 [get_ports {UART_TX_F[*]}]
set_output_delay -clock [get_clocks CS_TCK] -min -add_delay -1.000 [get_ports CS_TMS]
set_output_delay -clock [get_clocks CS_TCK] -max -add_delay 5.000 [get_ports CS_TMS]
