"""pyverify.regmap — the shell register map, as data.

GENERATED by tools/gen_regmap.py — DO NOT EDIT. Every value here is
derived from fpga/shell/bd/shell_bd.tcl (block bases) and the owning CSR
RTL under fpga/ (register offsets); the four Xilinx blocks are quoted
from their product guides and carry ``derived = False``.

Re-run::

    python3 tools/gen_regmap.py

and see scripts/harness_gates/check_generated_fresh.py, which fails CI
if this file and its siblings do not match a fresh generation.
"""
from __future__ import annotations

from typing import NamedTuple


class Register(NamedTuple):
    """One register: byte offset from its block base."""

    name: str
    offset: int
    note: str


class Reservation(NamedTuple):
    """A 64 KiB page held for a designed-but-unbuilt block."""

    name: str
    base: int
    range: str
    why: str
    pins: tuple[tuple[str, str], ...]   # (tracked file, symbol) pairs


class Block(NamedTuple):
    """One AXI4-Lite slave page in the 0x44A0_0000 contract window."""

    name: str
    base: int
    range: str
    cell: str
    source: str
    derived: bool          # True = parsed from RTL in this tree
    gate: str | None       # env flag the BD needs to instantiate it
    legacy_of: str | None  # shares another block's page
    registers: tuple[Register, ...]


BLOCKS: tuple[Block, ...] = (
    Block(
        name='CLKRST',
        base=0x44A00000,
        range='64K',
        cell='dut_clkrst_0',
        source='fpga/shell/ip/clkrst/dut_clkrst.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('RESET_CTRL', 0x00, ''),
            Register('DUT_CLK_SEL', 0x04, ''),
            Register('DUT_CLK_DRP', 0x08, ''),
            Register('STATUS', 0x0C, '(ro)'),
        ),
    ),
    Block(
        name='DFXCTL',
        base=0x44A10000,
        range='64K',
        cell='dfx_ctl_0',
        source='fpga/shell/ip/dfx_ctl/dfx_ctl.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('DECOUPLE', 0x00, ''),
            Register('SHUTDOWN', 0x04, ''),
            Register('STATUS', 0x08, '(ro)'),
            Register('RM_ID', 0x10, '(ro)'),
            Register('RM_STATUS', 0x14, '(ro)'),
        ),
    ),
    Block(
        name='HWICAP',
        base=0x44A20000,
        range='64K',
        cell='axi_hwicap_0',
        source='Xilinx AXI HWICAP (PG134)',
        derived=False,
        gate=None,
        legacy_of=None,
        registers=(
            Register('GIER', 0x1C, 'global interrupt enable'),
            Register('ISR', 0x20, 'interrupt status'),
            Register('IER', 0x28, 'interrupt enable'),
            Register('WF', 0x100, 'write FIFO — bitstream words, ICAP order'),
            Register('RF', 0x104, 'read FIFO'),
            Register('SZ', 0x108, 'transfer size, in 32-bit words'),
            Register('CR', 0x10C, 'control: [0] write (FIFO->ICAP), [1] read'),
            Register('SR', 0x110, 'status: [0] done, [2] EOS'),
            Register('WFV', 0x114, 'write FIFO vacancy, in words'),
            Register('RFO', 0x118, 'read FIFO occupancy, in words'),
        ),
    ),
    Block(
        name='VPHY',
        base=0x44A30000,
        range='4K',
        cell='eth_mac_test_subsystem_0',
        source='fpga/ethernet/mdio_phy_model/mdio_phy_model.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('PHY_STATE', 0x00, ''),
            Register('PHY_ID', 0x04, ''),
            Register('LINK_EVENT', 0x08, ''),
        ),
    ),
    Block(
        name='USD',
        base=0x44A40000,
        range='64K',
        cell='usd_spi_0',
        source='fpga/shell/ip/usd_spi/usd_spi.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('ID', 0x00, '(ro) block-present witness 0x55534431 "USD1"'),
            Register('CTRL', 0x04, 'EN / CS / WIDE / CD_POL / CD_IGNORE'),
            Register('CLKDIV', 0x08, 'SCK = aclk / (2*(DIV+1)), reset 124'),
            Register('DATA', 0x0C, 'W: start a shift / R: last RX word'),
            Register('STATUS', 0x10, 'BUSY, CD, sticky CD_CHANGED/OVR/ABORT (W1C)'),
        ),
    ),
    Block(
        name='TELEM',
        base=0x44A50000,
        range='64K',
        cell='telem_0',
        source='fpga/shell/ip/telem/telem.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('CTRL', 0x00, ''),
            Register('BUS_MV', 0x04, '(ro)'),
            Register('CURR_UA', 0x08, '(ro)'),
            Register('POWER_MW', 0x0C, '(ro)'),
            Register('STATUS', 0x10, '(ro)'),
        ),
    ),
    Block(
        name='GENCHK',
        base=0x44A60000,
        range='4K',
        cell='eth_mac_test_subsystem_0',
        source='fpga/ethernet/gen_checker/gen_checker.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('CTRL', 0x00, ''),
            Register('INJECT', 0x04, ''),
            Register('TX_CNT', 0x08, '(ro)'),
            Register('RX_CNT', 0x0C, '(ro)'),
            Register('ERR_CNT', 0x10, '(ro)'),
            Register('DUT_IP', 0x14, '(ro) DUT-IP sniffer'),
            Register('DUT_STATUS', 0x18, '(ro) DUT-IP sniffer'),
        ),
    ),
    Block(
        name='JTAGBB',
        base=0x44A70000,
        range='64K',
        cell='jtag_bb_0',
        source='fpga/shell/ip/jtag_bb/jtag_bb.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('DRIVE', 0x00, ''),
            Register('SAMPLE', 0x04, '(ro)'),
        ),
    ),
    Block(
        name='SWDBB',
        base=0x44A70000,
        range='64K',
        cell='jtag_bb_0',
        source='fpga/shell/ip/swd_bb/swd_bb.sv',
        derived=True,
        gate=None,
        legacy_of='JTAGBB',
        registers=(
            Register('DRIVE', 0x00, ''),
            Register('SAMPLE', 0x04, '(ro)'),
        ),
    ),
    Block(
        name='DBGBR',
        base=0x44A80000,
        range='64K',
        cell='debug_bridge_0',
        source='Xilinx Debug Bridge, AXI->BSCAN (PG245)',
        derived=False,
        gate=None,
        legacy_of=None,
        registers=(
            Register('LENGTH', 0x00, 'rw — bits to shift this chunk (1..32)'),
            Register('TMS', 0x04, 'rw — TMS vector chunk, LSB shifts first'),
            Register('TDI', 0x08, 'rw — TDI vector chunk, LSB shifts first'),
            Register('TDO', 0x0C, 'ro — captured TDO chunk'),
            Register('CTRL', 0x10, '[0] GO: write 1 to start, self-clears'),
        ),
    ),
    Block(
        name='UARTBR',
        base=0x44A90000,
        range='64K',
        cell='uart_bridge_0',
        source='fpga/shell/ip/uart_bridge/uart_bridge.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('U0_DATA', 0x00, 'W: U0_TX push / R: U0_RX pop'),
            Register('U1_DATA', 0x08, 'W: U1_TX push / R: U1_RX pop'),
            Register('SWO_RX', 0x10, 'R: SWO_RX pop (ro)'),
            Register('FIFO_STATUS', 0x14, '(ro)'),
            Register('SWO_CFG', 0x18, '(added, see ambiguities)'),
        ),
    ),
    Block(
        name='GPIO',
        base=0x44AA0000,
        range='64K',
        cell='board_gpio_0',
        source='fpga/shell/ip/board_gpio/board_gpio.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('IN', 0x00, '(ro)'),
            Register('OUT', 0x04, ''),
            Register('OE', 0x08, ''),
            Register('OWN', 0x0C, ''),
        ),
    ),
    Block(
        name='MMCM_DRP',
        base=0x44AB0000,
        range='64K',
        cell='clk_wiz_dut',
        source='Xilinx Clocking Wizard AXI4-Lite DRP (PG065)',
        derived=False,
        gate=None,
        legacy_of=None,
        registers=(
            Register('SW_RESET', 0x00, '[0] soft reset (self-clearing)'),
            Register('STATUS', 0x04, 'ro: [0] LOCKED'),
            Register('CFG_REG0', 0x200, '[7:0] DIVCLK_DIVIDE, [15:8] CLKFBOUT_MULT, [25:16] frac'),
            Register('CFG_REG2', 0x208, '[7:0] CLKOUT0_DIVIDE, [17:8] CLKOUT0_FRAC'),
            Register('LOAD', 0x25C, '[0] LOAD, [1] SEN — latch+apply CFG_REG*'),
        ),
    ),
    Block(
        name='CLCD',
        base=0x44AC0000,
        range='64K',
        cell='clcd_0',
        source='fpga/shell/ip/clcd/clcd.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('CTRL', 0x00, ''),
            Register('CMD', 0x04, '(W1, RS=0)'),
            Register('DATA', 0x08, '(W1, RS=1)'),
            Register('STATUS', 0x0C, '(ro)'),
            Register('READ', 0x10, '(ro)'),
            Register('TIMING', 0x14, ''),
        ),
    ),
    Block(
        name='CLCDKVM',
        base=0x44AD0000,
        range='64K',
        cell='clcd_kvm_0',
        source='fpga/shell/ip/clcd_kvm/clcd_kvm.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('CTRL', 0x00, ''),
            Register('STATUS', 0x04, '(ro)'),
            Register('EVENT', 0x08, '(RW1C)'),
            Register('PANEL_TMR', 0x0C, ''),
            Register('TIMEOUT', 0x10, ''),
            Register('DEBOUNCE', 0x14, ''),
            Register('TUNNEL', 0x18, '(ro)'),
        ),
    ),
    Block(
        name='TOUCH',
        base=0x44AE0000,
        range='64K',
        cell='touch_iic_0',
        source='Xilinx AXI IIC (PG090)',
        derived=False,
        gate='SHELL_TOUCH',
        legacy_of=None,
        registers=(
            Register('IIC_GIE', 0x1C, 'global interrupt enable'),
            Register('IIC_ISR', 0x20, 'interrupt status (W1C)'),
            Register('IIC_IER', 0x28, 'interrupt enable'),
            Register('IIC_SOFTR', 0x40, 'soft reset — write the reset key 0x0000000A'),
            Register('IIC_CR', 0x100, 'control'),
            Register('IIC_SR', 0x104, 'status (ro)'),
            Register('IIC_TX_FIFO', 0x108, 'transmit FIFO (data + dynamic start/stop)'),
            Register('IIC_RX_FIFO', 0x10C, 'receive FIFO (ro, destructive pop)'),
            Register('IIC_ADR', 0x110, 'own slave address (slave mode)'),
            Register('IIC_TX_FIFO_OCY', 0x114, 'TX FIFO occupancy (ro)'),
            Register('IIC_RX_FIFO_OCY', 0x118, 'RX FIFO occupancy (ro)'),
            Register('IIC_TEN_ADR', 0x11C, '10-bit slave address (unused here)'),
            Register('IIC_RX_FIFO_PIRQ', 0x120, 'RX FIFO programmable depth IRQ / dyn count'),
            Register('IIC_GPO', 0x124, 'general-purpose output'),
        ),
    ),
    Block(
        name='DUTEGR',
        base=0x44B20000,
        range='64K',
        cell='dut_egress_0',
        source='fpga/shell/ip/dut_egress/dut_egress.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('CTRL', 0x00, 'rw enable / flush / clear-counters'),
            Register('STATUS', 0x04, 'ro frame-ready, empty, full, sticky flags'),
            Register('LEVEL', 0x08, 'ro committed bytes and frames waiting'),
            Register('FRAME_LEN', 0x0C, 'ro head frame bytes remaining and total'),
            Register('DATA', 0x10, 'ro destructive byte pop with valid/last'),
            Register('RX_FRAMES', 0x14, 'ro frames captured whole'),
            Register('DROP_FULL', 0x18, 'ro frames dropped for want of room'),
            Register('DROP_GIANT', 0x1C, 'ro frames dropped for exceeding MAX_FRAME'),
            Register('TX_CTRL', 0x20, 'rw commit / abort / clear-counters / flush, RAW mode'),
            Register('TX_STATUS', 0x24, 'ro room, empty, full, staging, sticky flags'),
            Register('TX_SPACE', 0x28, 'ro free bytes and free frame slots'),
            Register('TX_DATA', 0x2C, 'wo stage one byte (reads 0, no side effect)'),
            Register('TX_FRAMES', 0x30, 'ro frames handed to the bridge whole'),
            Register('TX_REJECT', 0x34, 'ro commits refused (empty, short, long, no room)'),
            Register('TX_FLUSHED', 0x38, 'ro committed frames discarded by TX_CTRL.FLUSH'),
        ),
    ),
    Block(
        name='USRACC',
        base=0x44B30000,
        range='64K',
        cell='usr_access_rd_0',
        source='fpga/shell/ip/usr_access_rd/usr_access_rd.sv',
        derived=True,
        gate=None,
        legacy_of=None,
        registers=(
            Register('MAGIC', 0x00, '(ro) block-present witness 0x55535241 "USRA"'),
            Register('VALUE', 0x04, '(ro) AXSS USR_ACCESS word, HARNESS_VER32'),
            Register('STATUS', 0x08, '(ro) bit0 valid — a stable AXSS sample is held'),
        ),
    ),
    Block(
        name='WDOG',
        base=0x44B40000,
        range='64K',
        cell='axi_timebase_wdt_0',
        source='Xilinx AXI Timebase Watchdog Timer (PG128)',
        derived=False,
        gate=None,
        legacy_of=None,
        registers=(
            Register('TWCSR0', 0x00, 'control/status 0: [3] WRS reset-status, [2] WDS 1st-expiry status (W1C — THE KICK), [1] EWDT1 enable'),
            Register('TWCSR1', 0x04, 'control/status 1: [0] EWDT2 — both enables must be set for the watchdog to run'),
            Register('TBR', 0x08, 'ro: the free-running timebase counter'),
        ),
    ),
)

#: Pages held for a block that is designed but in no block design yet.
#: They have NO base constant anywhere in firmware or the bench on
#: purpose: a base for a slave that is not in the fabric is how one page
#: comes to be claimed twice (0x44AE_0000 was, by TOUCH and by the staged
#: axi_jtag). `pins` lists every tracked file that writes the literal;
#: tests/firmware_logic/test_regmap_conformance.py reads them back.
RESERVATIONS: tuple[Reservation, ...] = (
    Reservation(
        name='AXIJTAG',
        base=0x44AF0000,
        range='64K',
        why='axi_jtag:1.0 AXI->JTAG shifter into the DUT SWJ-DP (staged carry-across; MUTUALLY EXCLUSIVE with the fielded JTAGBB @0x44A7)',
        pins=(
            ('fpga/shell/bd/axijtag_uart_carry.tcl', '::MPS3_AXIJTAG_BASE'),
            ('host/socket_harness/carry_across.py', 'AXIJTAG_BASE'),
        ),
    ),
    Reservation(
        name='MAGICID',
        base=0x44B00000,
        range='64K',
        why="axi_gpio:2.0 all-inputs magic word 0x4A544147 ('JTAG') -- aperture-alive preflight (staged carry-across)",
        pins=(
            ('fpga/shell/bd/axijtag_uart_carry.tcl', '::MPS3_MAGICID_BASE'),
            ('host/socket_harness/carry_across.py', 'MAGIC_BASE'),
        ),
    ),
    Reservation(
        name='UART16550',
        base=0x44B10000,
        range='64K',
        why='axi_uart16550:2.0 ns16550a console, regfile at +0x1000 (staged carry-across)',
        pins=(
            ('fpga/shell/bd/axijtag_uart_carry.tcl', '::MPS3_UART16550_BASE'),
            ('host/socket_harness/carry_across.py', 'UART16550_BASE'),
        ),
    ),
)

#: The page-allocation region this map is the single authority for.
REGION_LO = 0x44A00000
REGION_HI = 0x44B50000
PAGE = 0x10000

#: name -> Block. A legacy alias (SWDBB) is present under its own name
#: and shares the base of the block that actually holds the page.
BY_NAME: dict[str, Block] = {b.name: b for b in BLOCKS}


def addr(block: str, register: str) -> int:
    """Absolute address of ``block.register`` (raises KeyError if absent)."""
    b = BY_NAME[block]
    for r in b.registers:
        if r.name == register:
            return b.base + r.offset
    raise KeyError(f'{block} has no register {register!r}')


#: page base -> owner name, for EVERY page in the region: the BD
#: blocks and the reservations in one dict. A page absent from it
#: is free.
PAGE_OWNER: dict[int, str] = {
    **{b.base: b.name for b in BLOCKS if b.legacy_of is None},
    **{r.base: r.name for r in RESERVATIONS},
}
