"""regmap.py — shared AXI4-Lite register constants (shell-regmap.md) + a
generic AXI4-Lite BFM for the dfx_ctl/clkrst/mdio_phy_model/gen_checker
benches.

Constants below are transcribed from two sources, cross-checked against
each other:
  - docs/contracts/shell-regmap.md (the contract, v0)
  - firmware/common/platform_regs.h (A3's shared C header, which already
    flags several gaps as "AMBIGUITY(A6) #N" comments — numbering
    preserved here so this file's comments and platform_regs.h's line up)
tests/common/test_regmap.py sanity-checks these constants against both.

**v0.1 update (2026-07-04, W5):** shell-regmap.md moved to v0.1, which
resolves OPEN_ISSUES I4/I8 by giving DFXCTL a *real* RM-load-verify pair
(`RM_ID`@0x10, `RM_STATUS`@0x14 — no longer AMBIGUITY(A6) #4's placeholder)
and adds a new GPIO passthrough block (`0x44AA_0000`, I4 board-port group).
`firmware/common/platform_regs.h` and `firmware/coordinator/swap_fsm.c`
were **stale relative to v0.1 earlier in this same delivery window** (they
still read the old placeholder `DFXCTL_RM_ID`@0x0C / `DFXCTL_CFG_CRC`@0x10
pair) but have since been updated to match (confirmed by re-reading
`platform_regs.h` directly: `DFXCTL_RM_ID`@0x10/`DFXCTL_RM_STATUS`@0x14,
both marked "v0.1 RESOLVED... I8"; `swap_fsm.c`'s `step_verify()` now does
a real `DFXCTL.RM_ID == target && RM_STATUS.rm_id_valid` compare, I25).
**The RTL has not caught up**: `fpga/shell/ip/dfx_ctl/dfx_ctl.sv` is still
a "Phase 0 stub" — `rm_id_i`/`dut_lockup_i` remain plain, AXI-Lite-
invisible ports (`s_axi_rdata` is tied to `'0` unconditionally,
`// TODO(A1)`) — so `DFXCTL_RM_ID`/`DFXCTL_RM_STATUS` are real, agreed-on
offsets in the contract *and* the firmware, but there is no RTL decode
logic backing them yet; see `tests/dfx_ctl/dut_notes.md`. The constants
below track the contract (shell-regmap.md v0.1), which the firmware side
now also matches.

AXI-Lite port binding: all four RTL blocks this covers
(fpga/shell/ip/{clkrst,dfx_ctl}/*.sv, fpga/ethernet/{mdio_phy_model,
gen_checker}/*.sv) were written with the IDENTICAL standard port names
(`s_axi_aclk`, `s_axi_awaddr`, ... — verified by reading all four files),
so `AxiLiteMaster.from_dut(dut)` below binds directly with no per-bench
signal-name plumbing needed.
"""
from __future__ import annotations

import cocotb
from cocotb.triggers import RisingEdge, ReadOnly

# cocotb 2.x port note (2026-07-04, W-SIM): the original write()/read() below
# deasserted valid/ready handles *while parked in the ReadOnly phase*, which
# raises "Attempting setting a value during the ReadOnly phase" — under
# cocotb 2.0.1 AND 1.7.2 alike (1.7.2's scheduler.py:596 has the same check;
# this BFM was only ever `make -n` dry-run under 1.7.2, never executed).
# The port keeps the public API (from_dut()/write()/read() signatures and
# return values unchanged) and restructures each call into: sample handshake
# progress in ReadOnly, then perform every signal write in a writable phase
# (immediately after a RisingEdge callback). See the comment above write()
# for the two slave handshake styles this must serve concurrently — the
# Xilinx-template FSMs (dfx_ctl/dut_clkrst/board_gpio) and mdio_phy_model's
# accept-on-valid style (response valid registered at the SAME edge as
# ready) — and why ready observation and response capture are one loop.

# --------------------------------------------------------------------------- #
# THE BASES AND OFFSETS BELOW ARE GENERATED by tools/gen_regmap.py from
# fpga/shell/bd/shell_bd.tcl (block bases) and the owning CSR RTL (register
# offsets). Do not edit them here -- edit the BD or the RTL and re-run the
# generator. Bit-field constants and the AXI-Lite BFM below are NOT generated.
# --------------------------------------------------------------------------- #
# BEGIN GENERATED[regmap] — gen_regmap.py — DO NOT EDIT BY HAND

# CLKRST @ 0x44A00000 (64K) — fpga/shell/ip/clkrst/dut_clkrst.sv
CLKRST_BASE = 0x44A00000
CLKRST_RESET_CTRL = 0x00
CLKRST_DUT_CLK_SEL = 0x04
CLKRST_DUT_CLK_DRP = 0x08
CLKRST_STATUS = 0x0C  # (ro)

# DFXCTL @ 0x44A10000 (64K) — fpga/shell/ip/dfx_ctl/dfx_ctl.sv
DFXCTL_BASE = 0x44A10000
DFXCTL_DECOUPLE = 0x00
DFXCTL_SHUTDOWN = 0x04
DFXCTL_STATUS = 0x08  # (ro)
DFXCTL_RM_ID = 0x10  # (ro)
DFXCTL_RM_STATUS = 0x14  # (ro)

# HWICAP @ 0x44A20000 (64K) — Xilinx AXI HWICAP (PG134) [vendor doc, not derived]
HWICAP_BASE = 0x44A20000
HWICAP_GIER = 0x1C  # global interrupt enable
HWICAP_ISR = 0x20  # interrupt status
HWICAP_IER = 0x28  # interrupt enable
HWICAP_WF = 0x100  # write FIFO — bitstream words, ICAP order
HWICAP_RF = 0x104  # read FIFO
HWICAP_SZ = 0x108  # transfer size, in 32-bit words
HWICAP_CR = 0x10C  # control: [0] write (FIFO->ICAP), [1] read
HWICAP_SR = 0x110  # status: [0] done, [2] EOS
HWICAP_WFV = 0x114  # write FIFO vacancy, in words
HWICAP_RFO = 0x118  # read FIFO occupancy, in words

# VPHY @ 0x44A30000 (4K) — fpga/ethernet/mdio_phy_model/mdio_phy_model.sv
VPHY_BASE = 0x44A30000
VPHY_PHY_STATE = 0x00
VPHY_PHY_ID = 0x04
VPHY_LINK_EVENT = 0x08

# USD @ 0x44A40000 (64K) — fpga/shell/ip/usd_spi/usd_spi.sv
USD_BASE = 0x44A40000
USD_ID = 0x00  # (ro) block-present witness 0x55534431 "USD1"
USD_CTRL = 0x04  # EN / CS / WIDE / CD_POL / CD_IGNORE
USD_CLKDIV = 0x08  # SCK = aclk / (2*(DIV+1)), reset 124
USD_DATA = 0x0C  # W: start a shift / R: last RX word
USD_STATUS = 0x10  # BUSY, CD, sticky CD_CHANGED/OVR/ABORT (W1C)

# TELEM @ 0x44A50000 (64K) — fpga/shell/ip/telem/telem.sv
TELEM_BASE = 0x44A50000
TELEM_CTRL = 0x00
TELEM_BUS_MV = 0x04  # (ro)
TELEM_CURR_UA = 0x08  # (ro)
TELEM_POWER_MW = 0x0C  # (ro)
TELEM_STATUS = 0x10  # (ro)

# GENCHK @ 0x44A60000 (4K) — fpga/ethernet/gen_checker/gen_checker.sv
GENCHK_BASE = 0x44A60000
GENCHK_CTRL = 0x00
GENCHK_INJECT = 0x04
GENCHK_TX_CNT = 0x08  # (ro)
GENCHK_RX_CNT = 0x0C  # (ro)
GENCHK_ERR_CNT = 0x10  # (ro)
GENCHK_DUT_IP = 0x14  # (ro) DUT-IP sniffer
GENCHK_DUT_STATUS = 0x18  # (ro) DUT-IP sniffer

# JTAGBB @ 0x44A70000 (64K) — fpga/shell/ip/jtag_bb/jtag_bb.sv
JTAGBB_BASE = 0x44A70000
JTAGBB_DRIVE = 0x00
JTAGBB_SAMPLE = 0x04  # (ro)

# SWDBB @ 0x44A70000 (64K) — fpga/shell/ip/swd_bb/swd_bb.sv (legacy, retired at the A6 SWD->JTAG cutover; shares the JTAGBB page)
SWDBB_BASE = 0x44A70000  # legacy: retired at the A6 SWD->JTAG cutover; shares the JTAGBB page
SWDBB_DRIVE = 0x00
SWDBB_SAMPLE = 0x04  # (ro)

# DBGBR @ 0x44A80000 (64K) — Xilinx Debug Bridge, AXI->BSCAN (PG245) [vendor doc, not derived]
DBGBR_BASE = 0x44A80000
DBGBR_LENGTH = 0x00  # rw — bits to shift this chunk (1..32)
DBGBR_TMS = 0x04  # rw — TMS vector chunk, LSB shifts first
DBGBR_TDI = 0x08  # rw — TDI vector chunk, LSB shifts first
DBGBR_TDO = 0x0C  # ro — captured TDO chunk
DBGBR_CTRL = 0x10  # [0] GO: write 1 to start, self-clears

# UARTBR @ 0x44A90000 (64K) — fpga/shell/ip/uart_bridge/uart_bridge.sv
UARTBR_BASE = 0x44A90000
UARTBR_U0_DATA = 0x00  # W: U0_TX push / R: U0_RX pop
UARTBR_U1_DATA = 0x08  # W: U1_TX push / R: U1_RX pop
UARTBR_SWO_RX = 0x10  # R: SWO_RX pop (ro)
UARTBR_FIFO_STATUS = 0x14  # (ro)
UARTBR_SWO_CFG = 0x18  # (added, see ambiguities)

# GPIO @ 0x44AA0000 (64K) — fpga/shell/ip/board_gpio/board_gpio.sv
GPIO_BASE = 0x44AA0000
GPIO_IN = 0x00  # (ro)
GPIO_OUT = 0x04
GPIO_OE = 0x08
GPIO_OWN = 0x0C

# MMCM_DRP @ 0x44AB0000 (64K) — Xilinx Clocking Wizard AXI4-Lite DRP (PG065) [vendor doc, not derived]
MMCM_DRP_BASE = 0x44AB0000
MMCM_DRP_SW_RESET = 0x00  # [0] soft reset (self-clearing)
MMCM_DRP_STATUS = 0x04  # ro: [0] LOCKED
MMCM_DRP_CFG_REG0 = 0x200  # [7:0] DIVCLK_DIVIDE, [15:8] CLKFBOUT_MULT, [25:16] frac
MMCM_DRP_CFG_REG2 = 0x208  # [7:0] CLKOUT0_DIVIDE, [17:8] CLKOUT0_FRAC
MMCM_DRP_LOAD = 0x25C  # [0] LOAD, [1] SEN — latch+apply CFG_REG*

# CLCD @ 0x44AC0000 (64K) — fpga/shell/ip/clcd/clcd.sv
CLCD_BASE = 0x44AC0000
CLCD_CTRL = 0x00
CLCD_CMD = 0x04  # (W1, RS=0)
CLCD_DATA = 0x08  # (W1, RS=1)
CLCD_STATUS = 0x0C  # (ro)
CLCD_READ = 0x10  # (ro)
CLCD_TIMING = 0x14

# CLCDKVM @ 0x44AD0000 (64K) — fpga/shell/ip/clcd_kvm/clcd_kvm.sv
CLCDKVM_BASE = 0x44AD0000
CLCDKVM_CTRL = 0x00
CLCDKVM_STATUS = 0x04  # (ro)
CLCDKVM_EVENT = 0x08  # (RW1C)
CLCDKVM_PANEL_TMR = 0x0C
CLCDKVM_TIMEOUT = 0x10
CLCDKVM_DEBOUNCE = 0x14
CLCDKVM_TUNNEL = 0x18  # (ro)

# TOUCH @ 0x44AE0000 (64K) — Xilinx AXI IIC (PG090) [vendor doc, not derived]
TOUCH_BASE = 0x44AE0000  # GATED: SHELL_TOUCH=1 builds only
TOUCH_IIC_GIE = 0x1C  # global interrupt enable
TOUCH_IIC_ISR = 0x20  # interrupt status (W1C)
TOUCH_IIC_IER = 0x28  # interrupt enable
TOUCH_IIC_SOFTR = 0x40  # soft reset — write the reset key 0x0000000A
TOUCH_IIC_CR = 0x100  # control
TOUCH_IIC_SR = 0x104  # status (ro)
TOUCH_IIC_TX_FIFO = 0x108  # transmit FIFO (data + dynamic start/stop)
TOUCH_IIC_RX_FIFO = 0x10C  # receive FIFO (ro, destructive pop)
TOUCH_IIC_ADR = 0x110  # own slave address (slave mode)
TOUCH_IIC_TX_FIFO_OCY = 0x114  # TX FIFO occupancy (ro)
TOUCH_IIC_RX_FIFO_OCY = 0x118  # RX FIFO occupancy (ro)
TOUCH_IIC_TEN_ADR = 0x11C  # 10-bit slave address (unused here)
TOUCH_IIC_RX_FIFO_PIRQ = 0x120  # RX FIFO programmable depth IRQ / dyn count
TOUCH_IIC_GPO = 0x124  # general-purpose output

# DUTEGR @ 0x44B20000 (64K) — fpga/shell/ip/dut_egress/dut_egress.sv
DUTEGR_BASE = 0x44B20000
DUTEGR_CTRL = 0x00  # rw enable / flush / clear-counters
DUTEGR_STATUS = 0x04  # ro frame-ready, empty, full, sticky flags
DUTEGR_LEVEL = 0x08  # ro committed bytes and frames waiting
DUTEGR_FRAME_LEN = 0x0C  # ro head frame bytes remaining and total
DUTEGR_DATA = 0x10  # ro destructive byte pop with valid/last
DUTEGR_RX_FRAMES = 0x14  # ro frames captured whole
DUTEGR_DROP_FULL = 0x18  # ro frames dropped for want of room
DUTEGR_DROP_GIANT = 0x1C  # ro frames dropped for exceeding MAX_FRAME
DUTEGR_TX_CTRL = 0x20  # rw commit / abort / clear-counters / flush, RAW mode
DUTEGR_TX_STATUS = 0x24  # ro room, empty, full, staging, sticky flags
DUTEGR_TX_SPACE = 0x28  # ro free bytes and free frame slots
DUTEGR_TX_DATA = 0x2C  # wo stage one byte (reads 0, no side effect)
DUTEGR_TX_FRAMES = 0x30  # ro frames handed to the bridge whole
DUTEGR_TX_REJECT = 0x34  # ro commits refused (empty, short, long, no room)
DUTEGR_TX_FLUSHED = 0x38  # ro committed frames discarded by TX_CTRL.FLUSH

# USRACC @ 0x44B30000 (64K) — fpga/shell/ip/usr_access_rd/usr_access_rd.sv
USRACC_BASE = 0x44B30000
USRACC_MAGIC = 0x00  # (ro) block-present witness 0x55535241 "USRA"
USRACC_VALUE = 0x04  # (ro) AXSS USR_ACCESS word, HARNESS_VER32
USRACC_STATUS = 0x08  # (ro) bit0 valid — a stable AXSS sample is held

# WDOG @ 0x44B40000 (64K) — Xilinx AXI Timebase Watchdog Timer (PG128) [vendor doc, not derived]
WDOG_BASE = 0x44B40000
WDOG_TWCSR0 = 0x00  # control/status 0: [3] WRS reset-status, [2] WDS 1st-expiry status (W1C — THE KICK), [1] EWDT1 enable
WDOG_TWCSR1 = 0x04  # control/status 1: [0] EWDT2 — both enables must be set for the watchdog to run
WDOG_TBR = 0x08  # ro: the free-running timebase counter

# Pages RESERVED by a block that is DESIGNED but in no block design yet.
# No base is emitted for them -- nothing can drive a slave that is not in
# the fabric, and a base for one is how a page gets claimed twice. They are
# listed so the NEXT block takes a page nobody holds. The authority is
# tools/gen_regmap.py's RESERVATIONS; every file that writes one of these
# literals is listed there and checked against it by
# tests/firmware_logic/test_regmap_conformance.py.
#
#   0x44AF0000 (64K)  AXIJTAG
#       axi_jtag:1.0 AXI->JTAG shifter into the DUT SWJ-DP (staged carry-across; MUTUALLY EXCLUSIVE with the fielded JTAGBB @0x44A7)
#
#   0x44B00000 (64K)  MAGICID
#       axi_gpio:2.0 all-inputs magic word 0x4A544147 ('JTAG') -- aperture-alive preflight (staged carry-across)
#
#   0x44B10000 (64K)  UART16550
#       axi_uart16550:2.0 ns16550a console, regfile at +0x1000 (staged carry-across)
#
# Region 0x44A00000..0x44B50000: FULL -- a new block must extend REGION_HI, and say so.
# END GENERATED[regmap]

# --------------------------------------------------------------------------- #
# Block base addresses (shell-regmap.md table / platform_regs.h MPS3_*_BASE)
# --------------------------------------------------------------------------- #
# v0.1 additions (I5-I11). SWDBB/UARTBR grew real RTL + benches in the
# W-RTL-NEWIP wave (fpga/shell/ip/{swd_bb,uart_bridge}, tests/{swd_bb,
# uart_bridge}); DBGBR remains Xilinx IP with no custom RTL/bench here.

# --------------------------------------------------------------------------- #
# CLKRST (0x44A0_0000) — dut_clkrst.sv
# --------------------------------------------------------------------------- #

RESET_CTRL_DUT_RESETN = 1 << 0   # 1 = released
RESET_CTRL_RP_RESETN = 1 << 1
RESET_CTRL_DBG_RESETN = 1 << 2

CLKRST_STATUS_MMCM_LOCKED = 1 << 0
CLKRST_STATUS_DUT_CLK_ALIVE = 1 << 1

# --------------------------------------------------------------------------- #
# DFXCTL (0x44A1_0000) — dfx_ctl.sv
# --------------------------------------------------------------------------- #

DECOUPLE_EN = 1 << 0
SHUTDOWN_AXI_SHUTDOWN = 1 << 0
DFXCTL_STATUS_DECOUPLED = 1 << 0
DFXCTL_STATUS_RP_IN_RESET = 1 << 1

# AMBIGUITY(A6) #4 -- RESOLVED for shell-regmap.md v0.1 (OPEN_ISSUES I8
# resolved there, though OPEN_ISSUES.md's own front-matter hasn't been
# updated to say so -- flag for A6 below). v0.1 gives RM-load verify two
# REAL, non-placeholder offsets:
#   RM_ID     @0x10  [31:0] rm_id            (ro; the RP's rm_id partition pin)
#   RM_STATUS @0x14  [0] rm_id_valid, [1] dut_lockup (ro)
# There is no CFG_CRC register in shell-regmap.md v0.1 at all (superseded by
# RM_STATUS.rm_id_valid). `firmware/common/platform_regs.h` and
# `firmware/coordinator/swap_fsm.c` have CAUGHT UP to these offsets
# (confirmed by re-reading platform_regs.h directly, same day: it now
# defines `DFXCTL_RM_ID`@0x10/`DFXCTL_RM_STATUS`@0x14 with a comment citing
# "v0.1 RESOLVED... I8", and swap_fsm.c's step_verify() does a real compare,
# I25). `dfx_ctl.sv` (RTL) has NOT caught up: it still only accepts
# rm_id_i/dut_lockup_i as plain ports with `s_axi_rdata` tied to `'0`
# unconditionally (`// TODO(A1)`) -- contract and firmware agree on these
# offsets now, but no AXI-Lite decode logic backs them yet.
DFXCTL_RM_STATUS_RM_ID_VALID = 1 << 0
DFXCTL_RM_STATUS_DUT_LOCKUP = 1 << 1
DFXCTL_RM_STATUS_DUT_ETH_IRQ = 1 << 2   # DUT ethernet irq_out (2-FF synced), added 2026-07-24

# --------------------------------------------------------------------------- #
# VPHY (0x44A3_0000) — mdio_phy_model.sv
# --------------------------------------------------------------------------- #

PHY_STATE_LINK_UP = 1 << 0
PHY_STATE_SPEED100 = 1 << 1
PHY_STATE_FULL_DUPLEX = 1 << 2

LINK_EVENT_FORCE_DOWN = 1 << 0
LINK_EVENT_PULSE = 1 << 1

# --------------------------------------------------------------------------- #
# GENCHK (0x44A6_0000) — gen_checker.sv
#
# **FROZEN layout** (shell-regmap.md GENCHK table + firmware/common/
# platform_regs.h GENCHK block + host/pyverify macgen driver — one authoritative
# contract, I10 RESOLVED). This SUPERSEDES the dead Phase-0 draft that used to
# live here (mode-field GEN_CTRL / GEN_COUNT / packed CHK_STATUS / CHK_CLEAR),
# which no longer matched the RTL, the firmware, or the pyverify macgen path.
# Names/values are identical to platform_regs.h's GENCHK_* macros so tests,
# firmware, and the host driver all agree. Updated by W-ETH-SS per the macgen
# agent's cross-workstream freeze.
#
# Semantics (all honoured by gen_checker.sv): CTRL sets gen_en/chk_en; INJECT
# is a one-hot fault that arms the NEXT generated frame (0 = none — the RTL
# consumes/clears it per frame, and the coordinator also rewrites it every
# macgen call); TX_CNT/RX_CNT/ERR_CNT are RO frame tallies the host snapshots
# as deltas (no counter-clear register exists — the RTL's clear-on-enable-rise
# is a v1 convenience that does not disturb a within-session delta snapshot).
# --------------------------------------------------------------------------- #

GENCHK_CTRL_GEN_EN = 1 << 0
GENCHK_CTRL_CHK_EN = 1 << 1

# DUT-IP sniffer (Phase-3): the always-on chk_s_* tap latches the DUT's own
# IPv4 (IPv4 src / ARP SPA) so firmware learns it without arming the checker.
GENCHK_DUT_STATUS_IP_SEEN = 1 << 0
GENCHK_DUT_STATUS_ETHERTYPE_SHIFT = 16

GENCHK_INJECT_BAD_FCS = 1 << 0
GENCHK_INJECT_RUNT = 1 << 1
GENCHK_INJECT_GIANT = 1 << 2
GENCHK_INJECT_IFG = 1 << 3
GENCHK_INJECT_DRIBBLE = 1 << 4
GENCHK_INJECT_MASK = (GENCHK_INJECT_BAD_FCS | GENCHK_INJECT_RUNT
                      | GENCHK_INJECT_GIANT | GENCHK_INJECT_IFG
                      | GENCHK_INJECT_DRIBBLE)

# --------------------------------------------------------------------------- #
# DUTEGR (0x44B2_0000) — dut_egress.sv. The DUT's Ethernet RETURN path: the
# frames the DUT transmits, captured out of eth_bridge_3port's management
# egress (which shell_bd.tcl SECTION 5 drained into a constant until this block
# existed). Semantics: docs/contracts/shell-regmap.md's DUTEGR section.
# --------------------------------------------------------------------------- #

DUTEGR_CTRL_EN = 1 << 0
DUTEGR_CTRL_FLUSH = 1 << 1        # W1, self-clearing: bounded drain
DUTEGR_CTRL_CLR_CNT = 1 << 2      # W1, self-clearing: counters + sticky bits

DUTEGR_STATUS_FRAME_RDY = 1 << 0
DUTEGR_STATUS_EMPTY = 1 << 1
DUTEGR_STATUS_DATA_FULL = 1 << 2
DUTEGR_STATUS_DESC_FULL = 1 << 3
DUTEGR_STATUS_OVF = 1 << 4        # sticky: at least one frame was dropped
DUTEGR_STATUS_FLUSH_BUSY = 1 << 5
DUTEGR_STATUS_DESYNC = 1 << 6     # sticky: end-of-frame marker vs descriptor
DUTEGR_STATUS_EN = 1 << 8         # capture-side read-back of CTRL.EN

# DATA is a DESTRUCTIVE read: one byte per read, VALID low (and nothing popped)
# when no whole frame is at the head.
DUTEGR_DATA_BYTE_MASK = 0xFF
DUTEGR_DATA_VALID = 1 << 8
DUTEGR_DATA_LAST = 1 << 9

# LEVEL / FRAME_LEN pack two 16-bit fields each.
DUTEGR_LEVEL_BYTES_MASK = 0xFFFF
DUTEGR_LEVEL_FRAMES_SHIFT = 16
DUTEGR_FRAME_LEN_REM_MASK = 0xFFFF
DUTEGR_FRAME_LEN_TOTAL_SHIFT = 16

# The block's shipped sizing (shell_bd.tcl CONFIG.* on dut_egress_0).
DUTEGR_DATA_DEPTH = 2048
DUTEGR_FRAME_DEPTH = 16
DUTEGR_MAX_FRAME = 1536

# --------------------------------------------------------------------------- #
# TELEM (0x44A5_0000) — telem.sv (I9, W-RTL-NEWIP). Offsets transcribed from
# shell-regmap.md v0.1's TELEM table and confirmed against telem.sv's
# IDX_* localparams (read directly, 2026-07-06). All five offsets match the
# contract exactly.
# --------------------------------------------------------------------------- #

TELEM_CTRL_ENABLE = 1 << 0
TELEM_CTRL_ALARM_EN = 1 << 1
TELEM_STATUS_ALARM = 1 << 0
TELEM_STATUS_I2C_ERR = 1 << 1

# --------------------------------------------------------------------------- #
# SWDBB (0x44A7_0000) — swd_bb.sv (I5, W-RTL-NEWIP). Both offsets match
# shell-regmap.md v0.1 exactly (confirmed against swd_bb.sv's IDX_*,
# 2026-07-06). Decode: the FULL local word address (widened 2026-07-09 —
# it used to decode only bit [2], so offsets >= 0x08 aliased onto
# DRIVE/SAMPLE and a stray write to 0x08 rewrote the SWD pins). Unmapped
# offsets now read 0 and their writes are inert — tests/swd_bb/ pins that.
# --------------------------------------------------------------------------- #

SWDBB_DRIVE_SWCLK = 1 << 0
SWDBB_DRIVE_SWDIO_O = 1 << 1
SWDBB_DRIVE_SWDIO_OE = 1 << 2

# JTAGBB (0x44A7_0000) — jtag_bb.sv (A6, SWD->JTAG cutover). Same 0x44A7 slot as
# swd_bb (mutually exclusive), same CSR layout, JTAG pin names. Folded into the
# contract with the 0xCD74B6AE re-mint; mirrors firmware/common/platform_regs.h.

JTAGBB_DRIVE_TCK = 1 << 0
JTAGBB_DRIVE_TMS = 1 << 1
JTAGBB_DRIVE_TDI = 1 << 2

# --------------------------------------------------------------------------- #
# UARTBR (0x44A9_0000) — uart_bridge.sv (I7, W-RTL-NEWIP). 0x00/0x08/0x10/
# 0x14 match shell-regmap.md v0.1; SWO_CFG @0x18 is an RTL-added register
# NOT in the v0.1 contract (uart_bridge.sv ambiguity #2 — the deliverable
# brief asked for a programmable divisor at a spare offset; codify into
# v0.2 or strike). Data-window reads are DESTRUCTIVE (each read pops one
# byte); FIFO_STATUS bit positions are the RTL's own choice (ambiguity #4).
# --------------------------------------------------------------------------- #

UARTBR_DATA_VALID = 1 << 8  # [8] valid qualifier on every data-window READ

UARTBR_STATUS_U0_TX_FULL = 1 << 0
UARTBR_STATUS_U0_RX_EMPTY = 1 << 1
UARTBR_STATUS_U1_TX_FULL = 1 << 2
UARTBR_STATUS_U1_RX_EMPTY = 1 << 3
UARTBR_STATUS_SWO_RX_EMPTY = 1 << 4

UARTBR_SWO_CFG_ENABLE = 1 << 16
UARTBR_SWO_CFG_OVERFLOW = 1 << 30   # sticky, ro, clears while enable=0
UARTBR_SWO_CFG_FRAME_ERR = 1 << 31  # sticky, ro, clears while enable=0

# --------------------------------------------------------------------------- #
# GPIO (0x44AA_0000) — board_gpio.sv (I4 board-port passthrough, v0.1 NEW).
#
# shell-regmap.md v0.1: "Default = the DUT's dut_gpio_* drives the pads; the
# host can override per-bit when no DUT owns them." Width NGPIO is a build
# parameter, v0 default 16 (partition-pins.md board-port group). No RTL for
# this block exists yet (fpga/shell/ip/board_gpio/ is not created) -- these
# offsets are transcribed straight from the contract table, not confirmed
# against any .sv (there isn't one to confirm against). See
# tests/board_gpio/dut_notes.md.
# --------------------------------------------------------------------------- #

GPIO_NGPIO_DEFAULT = 16  # partition-pins.md board-port group: "v0: 16"


class AxiLiteMaster:
    """Minimal self-contained AXI4-Lite master BFM (no cocotbext-axi
    dependency). One in-flight transaction at a time — plenty for
    register-poke benches.
    """

    def __init__(self, clk, awaddr, awvalid, awready, wdata, wstrb, wvalid,
                 wready, bresp, bvalid, bready, araddr, arvalid, arready,
                 rdata, rresp, rvalid, rready):
        self.clk = clk
        self.awaddr, self.awvalid, self.awready = awaddr, awvalid, awready
        self.wdata, self.wstrb, self.wvalid, self.wready = wdata, wstrb, wvalid, wready
        self.bresp, self.bvalid, self.bready = bresp, bvalid, bready
        self.araddr, self.arvalid, self.arready = araddr, arvalid, arready
        self.rdata, self.rresp, self.rvalid, self.rready = rdata, rresp, rvalid, rready

    @classmethod
    def from_dut(cls, dut, prefix: str = "s_axi_"):
        """Binds directly to the `s_axi_*` ports shared verbatim by
        dut_clkrst.sv / dfx_ctl.sv / mdio_phy_model.sv / gen_checker.sv."""
        g = lambda name: getattr(dut, f"{prefix}{name}")  # noqa: E731
        return cls(
            clk=g("aclk"),
            awaddr=g("awaddr"), awvalid=g("awvalid"), awready=g("awready"),
            wdata=g("wdata"), wstrb=g("wstrb"), wvalid=g("wvalid"), wready=g("wready"),
            bresp=g("bresp"), bvalid=g("bvalid"), bready=g("bready"),
            araddr=g("araddr"), arvalid=g("arvalid"), arready=g("arready"),
            rdata=g("rdata"), rresp=g("rresp"), rvalid=g("rvalid"), rready=g("rready"),
        )

    # The two slave styles this BFM must serve (verified by reading the RTL):
    #   - Xilinx-template FSM (dfx_ctl/dut_clkrst/board_gpio): ready pulses
    #     one cycle, THEN bvalid/rvalid assert one cycle later.
    #   - accept-on-valid (mdio_phy_model.sv): awready+bvalid (and
    #     arready+rvalid) are registered high at the SAME edge.
    # So ready observation and response capture must run CONCURRENTLY (a
    # sequential ready-then-response wait misses the mdio-style response
    # pulse and hangs — found the hard way under VCS). VALID/READY drives
    # are held through the clock edge that retires the last handshake, then
    # deasserted in that edge's writable window.

    async def write(self, addr: int, data: int, strb: int = 0xF) -> int:
        self.awaddr.value = addr
        self.awvalid.value = 1
        self.wdata.value = data
        self.wstrb.value = strb
        self.wvalid.value = 1
        self.bready.value = 1
        aw_seen = w_seen = False
        resp = None
        while resp is None or not (aw_seen and w_seen):
            await RisingEdge(self.clk)
            await ReadOnly()
            aw_seen = aw_seen or bool(int(self.awready.value))
            w_seen = w_seen or bool(int(self.wready.value))
            if resp is None and int(self.bvalid.value):
                resp = int(self.bresp.value)  # BREADY is held high throughout
        await RisingEdge(self.clk)  # last-observed handshake retires here
        self.awvalid.value = 0      # writable phase (post-edge callback)
        self.wvalid.value = 0
        self.bready.value = 0
        return resp

    async def write_bytes(self, addr: int, data: int, strb: int) -> int:
        """WSTRB-aware write: drive `data` with an explicit byte-lane strobe
        `strb` (bit i enables wdata[8*i +: 8]). Thin, self-documenting wrapper
        over write() — write() always drove strb=0xF (a full-word write), so
        every AXI4-Lite slave's per-lane WSTRB decode went UNTESTED until this
        entry point existed. A slave that ignores WSTRB (commits the whole
        word regardless of the strobe) is caught by the per-block
        `test_wstrb_*` benches that drive partial strobes through here and
        assert only the enabled lanes changed.

        `strb=0` is a legal, no-lane write (a bare address touch): the AXI-Lite
        transaction still completes with BRESP=OKAY, and a correct slave leaves
        every register byte unchanged.
        """
        return await self.write(addr, data, strb)

    async def read(self, addr: int):
        self.araddr.value = addr
        self.arvalid.value = 1
        self.rready.value = 1
        ar_seen = False
        data = resp = None
        while data is None or not ar_seen:
            await RisingEdge(self.clk)
            await ReadOnly()
            ar_seen = ar_seen or bool(int(self.arready.value))
            if data is None and int(self.rvalid.value):
                data = int(self.rdata.value)  # RREADY is held high throughout
                resp = int(self.rresp.value)
        await RisingEdge(self.clk)  # last-observed handshake retires here
        self.arvalid.value = 0      # writable phase (post-edge callback)
        self.rready.value = 0
        # One idle edge with ARVALID low before returning (found 2026-07-06
        # while benching swd_bb with ZERO-GAP back-to-back read() calls —
        # the older benches always had at least one await between reads, so
        # this never fired for them): the Xilinx-template FSM re-asserts
        # ARREADY at the retire edge above (ARVALID is still high there)
        # and re-captures the OLD ARADDR into axi_araddr_q. If the caller
        # issues the next read() in this same writable window, ARVALID
        # never dips at a clock edge, that phantom acceptance completes,
        # and the data returned is for the PREVIOUS address. The idle edge
        # kills the phantom (ARREADY falls with ARVALID low, no rden).
        # write() needs no equivalent: its aw_en_q interlock means a
        # zero-gap follow-on write is accepted with the NEW address.
        await RisingEdge(self.clk)
        return data, resp
