"""The front panel's files vendored from Harness Manager have not drifted
(firmware/clcd/HM_VENDORED.md).

  * firmware/clcd/clcd_palette.h -- HM's generated role palette, vendored
    UNCHANGED: its sha256 is pinned in HM_VENDORED.md.
  * firmware/clcd/clcd_glyphs.h  -- HM's generated status glyphs (0x80-0x86),
    vendored UNCHANGED: its sha256 is pinned in HM_VENDORED.md, and its glyph
    bytes must hash to the sha256 the header records.
  * clcd.h's CLCD_GLYPH_* codes are the header's (the compiler also enforces it:
    clcd.c includes both), and there is ONE glyph table under firmware/clcd/.
  * With a Harness Manager checkout (HM_DIR, or ../harness-manager beside this
    repo) both files are also compared with HM byte for byte; a CI runner has
    none, so those two cases skip there.

Also negative controls: a one-byte change to a scratch copy of each file must
fail the same check. Stdlib + pytest only; board-free.
"""
from __future__ import annotations

import hashlib
import os
import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
CLCD = ROOT / "firmware" / "clcd"
NOTE = CLCD / "HM_VENDORED.md"
VENDORED = ("clcd_palette.h", "clcd_glyphs.h")


def _pinned_sha(name: str) -> str:
    m = re.search(r"\| `" + re.escape(name) + r"` \|.*?\| `([0-9a-f]{64})` \|", NOTE.read_text())
    assert m, f"HM_VENDORED.md has no pinned sha256 for {name}"
    return m.group(1)


def _hm_dir() -> pathlib.Path | None:
    for cand in (os.environ.get("HM_DIR"), ROOT.parent / "harness-manager",
                 pathlib.Path.home() / "SoCLabs" / "harness-manager"):
        if cand and (pathlib.Path(cand) / "design" / "generated" / "clcd_palette.h").exists():
            return pathlib.Path(cand)
    return None


def _glyph_bytes(text: str) -> bytes:
    body = text[text.index("font8x16_ext[CLCD_FONT_EXT_COUNT][16] = {"):].split("};")[0]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = body[body.index("{") + 1:]
    return bytes(int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})\b", body))


def _glyphs_self_consistent(text: str) -> list[str]:
    m = re.search(r'#define CLCD_GLYPHS_SHA256 "([0-9a-f]{64})"', text)
    count = re.search(r"#define CLCD_FONT_EXT_COUNT\s+(\d+)", text)
    if not m or not count:
        return ["clcd_glyphs.h: no CLCD_GLYPHS_SHA256 / CLCD_FONT_EXT_COUNT"]
    data = _glyph_bytes(text)
    if len(data) != 16 * int(count.group(1)):
        return [f"clcd_glyphs.h: {len(data)} scanlines, want {16 * int(count.group(1))}"]
    if hashlib.sha256(data).hexdigest() != m.group(1):
        return ["clcd_glyphs.h: glyph data does not match its recorded sha256 (hand edit?)"]
    return []


@pytest.mark.parametrize("name", VENDORED)
def test_vendored_file_matches_its_pinned_sha256(name):
    data = (CLCD / name).read_bytes()
    assert hashlib.sha256(data).hexdigest() == _pinned_sha(name), (
        f"firmware/clcd/{name} is not the file HM_VENDORED.md pins: re-vendor it from "
        "Harness Manager unchanged, or update the note with HM's commit")


def test_palette_negative_control():
    bad = bytearray((CLCD / "clcd_palette.h").read_bytes())
    i = bad.index(b"0xE73Du")
    bad[i + 5] ^= 0x01                                  # one nibble of one colour
    assert hashlib.sha256(bytes(bad)).hexdigest() != _pinned_sha("clcd_palette.h")


def test_palette_is_what_the_renderer_includes():
    text = (CLCD / "clcd_palette.h").read_text()
    assert "GENERATED by Harness Manager tools/gen_tokens.py" in text
    assert "CLCD_PALETTE_INIT" in text and "CLCD_ROLE_COUNT" in text
    assert '#include "clcd_palette.h"' in (CLCD / "clcd.h").read_text()


def test_glyph_header_is_self_consistent():
    text = (CLCD / "clcd_glyphs.h").read_text()
    assert "GENERATED by Harness Manager tools/gen_tokens.py" in text
    assert _glyphs_self_consistent(text) == []
    assert '#include "clcd_glyphs.h"' in (CLCD / "clcd.c").read_text()


def test_glyph_header_negative_control():
    text = (CLCD / "clcd_glyphs.h").read_text()
    bad = text.replace("0xEE, /* ###.###. */", "0xEF, /* ###.###. */", 1)
    assert bad != text
    assert _glyphs_self_consistent(bad) != []
    assert hashlib.sha256(bad.encode()).hexdigest() != _pinned_sha("clcd_glyphs.h")


def test_glyph_codes_are_the_headers():
    """clcd.h names the seven codes for every TU; the header is the source."""
    def codes(text: str) -> dict:
        return dict(re.findall(r"#define (CLCD_GLYPH_(?:OK|ERR|WARN|HELD|USER|UNK|DOT))\s+(0x[0-9A-Fa-f]+)\b",
                               text))
    ours = codes((CLCD / "clcd.h").read_text())
    theirs = codes((CLCD / "clcd_glyphs.h").read_text())
    assert len(theirs) == 7 and ours == theirs, (ours, theirs)


def test_one_glyph_table():
    """The retired font8x16_ext.h / gen_font_ext.py are gone: one source of glyphs."""
    tables = sorted(p.name for p in CLCD.rglob("*") if p.is_file()
                    and p.suffix in (".h", ".c", ".py") and "font8x16_ext[" in p.read_text(errors="replace"))
    assert tables in (["clcd.c", "clcd_glyphs.h"], ["clcd_glyphs.h"]), tables
    assert not (CLCD / "font8x16_ext.h").exists() and not (CLCD / "tools" / "gen_font_ext.py").exists()


@pytest.mark.parametrize("name", VENDORED)
def test_vendored_file_equals_harness_manager(name):
    hm = _hm_dir()
    if hm is None:
        pytest.skip("no Harness Manager checkout (set HM_DIR); the pinned sha256 still gates")
    ours = (CLCD / name).read_bytes()
    theirs = (hm / "design" / "generated" / name).read_bytes()
    assert ours == theirs, f"{name} differs from {hm}: re-vendor (HM_VENDORED.md)"
