"""E2E-1 (W-E2E convergence gate): full ``deploy`` end-to-end against the
FakeShell — CLI (``python -m pyverify.cli deploy``) and facade
(:meth:`pyverify.board.Mps3Board.deploy`) paths, over both push transports
(TFTP and raw TCP), plus the wrong-static_id rejection path.

Two overlay sources:

- **The real KU115 overlay triples** in ``fpga/dfx/overlay/<rm>/``
  (generated by ``fpga/dfx/gen_manifest.py`` from actual bitstreams). Payload
  sizes are read **from each RM's manifest on disk**; the running-shell
  ``static_id`` the FakeShell must report is read from the shell's OWN
  generated identity source, ``fpga/dfx/overlay/mps3_shell_static_id.c`` —
  *not* from an overlay's manifest, which only records the static that overlay
  was built AGAINST (see :func:`_real_static_id`). Nothing is hardcoded, so a
  DFX rebuild against a new static shell (which mints a fresh ``static_id``
  and, with compression, different sizes) re-keys these tests automatically.
  The ``.bin`` payloads are gitignored, so these tests ``pytest.skip`` cleanly
  on a fresh clone where only the manifest (or nothing) is present.
- **A small synthetic triple** built in ``tmp_path`` with a
  gen_manifest.py-compatible ``manifest.json`` — always runs, so CI never
  goes coverage-dark on the E2E path.

Everything crosses real sockets on 127.0.0.1 ephemeral ports: the CLI/
facade drive the production ``ShellClient`` + ``BitstreamPusher`` against
the FakeShell's control/TFTP/raw-TCP servers, and the swap is verified by
the same :mod:`pyverify.testing.swap_model` port of the firmware FSM.

**No ``rm_id`` is hard-coded here.** Under the v2 encoding
(docs/VERSIONING_PLAN.md §3.2) an ``rm_id`` is
``{ver_major[31:24], ver_minor[23:16], design_id[15:0]}``, so it legitimately
changes on every design *version* bump — a literal would re-break these tests
forever. Instead each test asserts the two things it actually means:

1. **the round trip** — the board reports back exactly the id that the pushed
   overlay's own ``manifest.json`` declared (:func:`_real_rm_id`); and
2. **the design** — the version-stable low half (``rm_id & 0xFFFF``) is the
   design we asked for (``DESIGN_ID_NANOSOC`` / ``DESIGN_ID_LED``), so pushing
   the wrong overlay still fails loudly.

``scripts/harness_gates/check_rm_id_literals.py`` enforces this repo-wide.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import zlib
from pathlib import Path

import pytest

from pyverify.board import Mps3Board
from pyverify.cli import main
from pyverify.rm_id import design_id as rm_design_id, format_rm_id
from pyverify.swap import SwapError
from pyverify.testing._pusher import BitstreamKind
from pyverify.testing.fakeshell import FakeShell

# --------------------------------------------------------------------------- #
# Overlay sources
# --------------------------------------------------------------------------- #

REPO_ROOT = Path(__file__).resolve().parents[3]
REAL_OVERLAY_ROOT = REPO_ROOT / "fpga" / "dfx" / "overlay"

#: The shell's OWN generated identity source: the strong
#: ``mps3_shell_static_id()`` override that ``make -C fpga/dfx overlays`` emits
#: and A3 links into the shell firmware image. This — not any per-RM overlay
#: manifest — is the authoritative record of the static_id the *running shell*
#: reports on ping (fpga/dfx/Makefile; net-protocol.md ping.shell_id). A DFX
#: rebuild rewrites it, so reading it here re-keys the tests with no edit.
SHELL_STATIC_ID_C = REAL_OVERLAY_ROOT / "mps3_shell_static_id.c"

#: Pulls the literal out of ``uint32_t mps3_shell_static_id(void) { return
#: 0x...; }`` — anchored to the function body (``)`` then ``{`` then
#: ``return``) so the file's own header comment, which also names
#: ``mps3_shell_static_id()``, cannot match. Tolerates the ``UL``/``u`` suffix
#: the Makefile / gen_greybox_blob.py emit (captured group stops at the digits).
_SHELL_STATIC_ID_RE = re.compile(
    r"mps3_shell_static_id\s*\([^)]*\)\s*\{\s*return\s+(0[xX][0-9A-Fa-f]+)",
    re.DOTALL,
)

PKG_ROOT = Path(__file__).resolve().parents[1]  # host/pyverify (has pyverify/)


def _real_manifest(rm_name: str = "nanosoc") -> dict | None:
    """Parse the real overlay's manifest.json if present, else None.

    The single source of truth for the real triple's ``static_id`` and
    payload sizes: a DFX rebuild against a new static shell rewrites this
    file (new ``static_id``, new compressed sizes) and the tests below track
    it with no edit. Returns None on a fresh clone (manifest absent) so the
    real-overlay tests skip rather than key off a stale constant.
    """
    manifest = REAL_OVERLAY_ROOT / rm_name / "manifest.json"
    if not manifest.is_file():
        return None
    try:
        return json.loads(manifest.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def _real_static_id() -> int:
    """The static_id the *running shell* reports on ping — what the FakeShell
    must claim so that CURRENT overlays validate against it (and STALE ones
    honestly do not).

    Read from the shell's OWN identity source
    (``fpga/dfx/overlay/mps3_shell_static_id.c``), NOT from a per-RM
    ``overlay/<rm>/manifest.json``. An overlay manifest records the static the
    overlay was *built against*; only ``mps3_shell_static_id.c`` records what
    the *running shell itself* reports on ping. Seeding the FakeShell from an
    overlay manifest is a category error: when that overlay is stale relative
    to the shell, every CURRENT overlay then appears to mismatch and the
    failure blames the wrong RM. This function is rm-independent by design.

    No hardcoded id and no fall-back constant: the file is git-tracked (only
    the ``.bin`` payloads are gitignored), and every caller runs
    ``real_overlay_dir()`` first — which skips on a fresh clone before this is
    reached — so a missing/garbled file is a real defect worth failing on, not
    something to paper over with a stale literal.
    """
    text = SHELL_STATIC_ID_C.read_text()
    match = _SHELL_STATIC_ID_RE.search(text)
    if match is None:
        raise ValueError(
            f"could not parse a static_id from {SHELL_STATIC_ID_C} "
            "(expected `uint32_t mps3_shell_static_id(void) {{ return 0x...; }}`; "
            "regenerate with `make -C fpga/dfx overlays`)"
        )
    return int(match.group(1), 0)


def _overlay_built_against_static_id(rm_name: str = "nanosoc") -> int:
    """The static_id an overlay declares it was BUILT AGAINST (its manifest's
    ``static_id``) — i.e. the shell that overlay is valid for.

    Deliberately NOT :func:`_real_static_id`. Used only to seed the FakeShell
    in the *single-overlay* happy-path tests, where a shell the
    overlay-under-test is compatible with is a PRECONDITION for exercising the
    real transport/swap mechanics — not the thing under test. Those tests carry
    no cross-overlay constraint, so they stay green regardless of any one
    overlay's freshness. The multi-overlay
    ``..._led_then_nanosoc_second_swap`` test is the one that pins overlays
    against the REAL running shell (:func:`_real_static_id`) and so honestly
    fails while ``nanosoc`` is stale — that mismatch is surfaced there, once,
    not smeared across every real-payload mechanics test.

    Only reached after ``real_overlay_dir()`` has confirmed the manifest
    exists, so a None here is a logic error, not a fresh clone.
    """
    m = _real_manifest(rm_name)
    assert m is not None, (
        "single-overlay test seeded its shell before real_overlay_dir() "
        "confirmed the manifest exists"
    )
    return int(m["static_id"], 0)


def real_overlay_dir(rm_name: str = "nanosoc") -> Path:
    """The real overlay triple for ``rm_name``, or skip: the ``.bin``
    payloads are gitignored (fresh clones have at most the manifest)."""
    directory = REAL_OVERLAY_ROOT / rm_name
    manifest_path = directory / "manifest.json"
    if not manifest_path.is_file():
        pytest.skip(f"real overlay not present: {manifest_path} (fresh clone?)")
    manifest = json.loads(manifest_path.read_text())
    for kind in ("clearing", "partial"):
        payload = directory / manifest[kind]["file"]
        if not payload.is_file():
            pytest.skip(
                f"real overlay {kind} payload not present: {payload} "
                "(bitstream .bins are gitignored)"
            )
    return directory


def _real_rm_id(rm_name: str = "nanosoc") -> int:
    """The rm_id the real overlay's manifest DECLARES — i.e. the value the
    board must read back at ``DFXCTL.RM_ID`` after this exact artefact lands.

    Derived, never hard-coded. Since the v2 encoding (VERSIONING_PLAN.md §3.2)
    an rm_id is ``{ver_major[31:24], ver_minor[23:16], design_id[15:0]}``, so
    it *legitimately changes on every design version bump* — nanosoc v1.0 is
    0x01000001, v1.1 will be 0x01010001. A literal here would be a maintenance
    landmine that re-breaks these tests on every bump, forever.

    Reading it from the manifest is also the *honest* subject of these tests:
    the round trip is "deploy pushes overlay X, and the board reports the id
    X's own manifest declared". The manifest is what the pusher puts in the
    partial's 24-byte header and what firmware's ``step_verify()`` compares
    ``DFXCTL.RM_ID`` against — so this asserts the real contract end to end.
    The *stable* half of the id is pinned separately (see DESIGN_ID_*) so a
    swap that lands the WRONG DESIGN still fails loudly.

    Called only after ``real_overlay_dir()`` has confirmed the manifest exists.
    """
    m = _real_manifest(rm_name)
    assert m is not None, "real manifest vanished after real_overlay_dir() check"
    return int(m["rm_id"], 0)


#: The version-STABLE half of each real RM's identity: ``rm_id & 0xFFFF``
#: (:mod:`pyverify.rm_id`). These are legitimate hard pins — a design_id is
#: fixed for the life of the design, and re-numbering one is a deliberate
#: breaking change (uart_echo, 2026-07-14). Pinning them is what makes these
#: tests still fail loudly if the deploy lands the WRONG DESIGN, while the
#: version half is derived from the manifest and so survives version bumps.
#: ``scripts/harness_gates/check_rm_id_literals.py`` machine-checks these two
#: literals against ``fpga/dfx/rm_list.tcl``, so a re-numbering cannot leave a
#: stale pin here undetected.
DESIGN_ID_NANOSOC = 0x0001
DESIGN_ID_LED = 0x001E

#: An arbitrary static_id for synthetic overlays — decoupled from any real
#: shell build (the synthetic test configures the FakeShell with the same
#: value, so it only needs to be self-consistent).
SYNTHETIC_STATIC_ID = 0x2F458F06

#: The synthetic overlay's id. Its design half (0x7A57) is deliberately OUTSIDE
#: the allocated design_id range in ``fpga/dfx/rm_list.tcl`` — a fixture must
#: never masquerade as a real design. (It used to be 0x0000_0001, which both
#: claimed to *be* nanosoc and, post-v2, is not even a well-formed nanosoc id.)
#: Version half v1.0, so it is a structurally valid v2 rm_id.
SYNTHETIC_RM_ID = 0x0100_7A57


def make_synthetic_overlay(
    root: Path,
    *,
    rm_name: str = "nanosoc",
    rm_id: int = SYNTHETIC_RM_ID,
    static_id: int = SYNTHETIC_STATIC_ID,
    clearing_payload: bytes = b"\xC1\x0E\xA2\x00" * 32,
    partial_payload: bytes = b"\xB1\x75\x00\x0D" * 96,
) -> Path:
    """A tiny fake triple whose manifest.json matches gen_manifest.py's
    output byte-for-byte in shape (same keys, same contract filenames,
    same '0x'-lowercase-hex crc32 strings)."""
    directory = root / rm_name
    directory.mkdir(parents=True)
    partial_name = f"{rm_name}.bin"
    clearing_name = f"{rm_name}_clear.bin"
    (directory / clearing_name).write_bytes(clearing_payload)
    (directory / partial_name).write_bytes(partial_payload)
    manifest = {
        "schema": 1,
        "static_id": f"0x{static_id:08X}",
        "rm_id": f"0x{rm_id:08x}",
        "rm_name": rm_name,
        "clearing": {
            "file": clearing_name,
            "len": len(clearing_payload),
            "crc32": f"0x{zlib.crc32(clearing_payload) & 0xFFFFFFFF:08x}",
        },
        "partial": {
            "file": partial_name,
            "len": len(partial_payload),
            "crc32": f"0x{zlib.crc32(partial_payload) & 0xFFFFFFFF:08x}",
        },
        "built": "2026-07-06",
        "vivado": "2024.1",
    }
    (directory / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return directory


def deploy_argv(fake: FakeShell, overlay_dir: Path, transport: str) -> list[str]:
    argv = [
        "deploy", "--host", fake.host, "--overlay", str(overlay_dir),
        "--control-port", str(fake.control_port),
    ]
    if transport == "tftp":
        argv += ["--tftp-port", str(fake.tftp_port)]
    else:
        argv += ["--pusher-transport", "tcp", "--src", "tcp",
                 "--tcp-push-port", str(fake.raw_tcp_port)]
    return argv


def assert_shell_saw_verified_deploy(
    fake: FakeShell, *, transport: str, rm_id: int, sizes: tuple[int, int],
) -> None:
    """Server-side truth: clearing-then-partial accepted on the expected
    transport with the expected byte counts, and the swap FSM ran to DONE."""
    assert [e.status for e in fake.push_events] == ["OK", "OK"]
    assert [e.transport for e in fake.accepted_pushes] == [transport, transport]
    assert [e.info.kind for e in fake.accepted_pushes] == [
        BitstreamKind.CLEARING, BitstreamKind.PARTIAL,
    ]
    assert [e.info.len_words * 4 for e in fake.accepted_pushes] == list(sizes)
    assert fake.swaps[-1]["final"] == "DONE"
    assert fake.current_rm_id == rm_id


# --------------------------------------------------------------------------- #
# E2E-1 headline: the REAL overlay triples (skip cleanly on a fresh clone)
# --------------------------------------------------------------------------- #

def _real_sizes(rm_name: str = "nanosoc") -> tuple[int, int]:
    """(clearing, partial) byte lengths from the real manifest — tracks the
    compression the shell's constraints apply, so a rebuild re-keys the
    byte-count assertions with no edit. Called only after real_overlay_dir()
    has confirmed the manifest+payloads exist."""
    m = _real_manifest(rm_name)
    assert m is not None, "real manifest vanished after real_overlay_dir() check"
    return (m["clearing"]["len"], m["partial"]["len"])


@pytest.mark.parametrize("transport", ["tftp", "tcp"])
def test_cli_deploy_real_nanosoc_overlay(transport, capsys):
    """``python -m pyverify.cli deploy`` semantics via ``main(argv)``: the
    real 3.6 MB partial + 240 KB clearing cross the wire, the swap is
    accepted and verified, exit code 0, exactly one JSON object on stdout.

    The rm_id assertion is the ROUND TRIP — the board reports back exactly the
    id nanosoc's own manifest declared — plus a pin on the version-stable
    design half, so a deploy that lands the wrong DESIGN still fails loudly.
    """
    overlay_dir = real_overlay_dir("nanosoc")
    want_rm_id = _real_rm_id("nanosoc")
    assert rm_design_id(want_rm_id) == DESIGN_ID_NANOSOC, (
        "the nanosoc overlay's manifest does not declare the nanosoc design"
    )
    with FakeShell.ephemeral(static_id=_overlay_built_against_static_id("nanosoc")) as fake:
        rc = main(deploy_argv(fake, overlay_dir, transport))
        captured = capsys.readouterr()
        assert rc == 0
        assert captured.err == ""
        result = json.loads(captured.out)
        assert result == {
            "ok": True, "rm_id": format_rm_id(want_rm_id),
            "verified": True, "ltx_path": None,
        }
        assert_shell_saw_verified_deploy(
            fake, transport=transport, rm_id=want_rm_id, sizes=_real_sizes(),
        )


def test_cli_deploy_real_nanosoc_overlay_as_subprocess():
    """The literal headline command — a separate ``python -m pyverify.cli``
    process pushing the real overlay to the fake shell over real sockets."""
    overlay_dir = real_overlay_dir("nanosoc")
    want_rm_id = _real_rm_id("nanosoc")
    assert rm_design_id(want_rm_id) == DESIGN_ID_NANOSOC
    env = dict(os.environ)
    env["PYTHONPATH"] = str(PKG_ROOT) + os.pathsep + env.get("PYTHONPATH", "")
    with FakeShell.ephemeral(static_id=_overlay_built_against_static_id("nanosoc")) as fake:
        proc = subprocess.run(
            [sys.executable, "-m", "pyverify.cli"]
            + deploy_argv(fake, overlay_dir, "tftp"),
            capture_output=True, text=True, timeout=120, env=env,
        )
        assert proc.returncode == 0, proc.stderr
        assert json.loads(proc.stdout) == {
            "ok": True, "rm_id": format_rm_id(want_rm_id),
            "verified": True, "ltx_path": None,
        }
        assert_shell_saw_verified_deploy(
            fake, transport="tftp", rm_id=want_rm_id, sizes=_real_sizes(),
        )


@pytest.mark.parametrize("transport", ["tftp", "tcp"])
def test_facade_deploy_real_nanosoc_overlay(transport):
    """``Mps3Board.deploy`` (the notebook/"PYNQ experience" path) with the
    real overlay, resolved as a bare RM name against overlay_root."""
    real_overlay_dir("nanosoc")
    want_rm_id = _real_rm_id("nanosoc")
    assert rm_design_id(want_rm_id) == DESIGN_ID_NANOSOC
    with FakeShell.ephemeral(static_id=_overlay_built_against_static_id("nanosoc")) as fake:
        with Mps3Board(
            fake.host,
            control_port=fake.control_port,
            tftp_port=fake.tftp_port,
            tcp_push_port=fake.raw_tcp_port,
            transport=transport,
            overlay_root=REAL_OVERLAY_ROOT,
        ) as board:
            result = board.deploy("nanosoc", src=transport)
            assert result.verified is True
            assert int(result.rm_id, 0) == want_rm_id
            assert rm_design_id(result.rm_id) == DESIGN_ID_NANOSOC
            assert board.last_deploy is result
            assert result.reattach.shell_host == fake.host
            # ping now reports the new RM (net-protocol.md swap step 7).
            assert int(board.ping().rm_id, 0) == want_rm_id
        assert_shell_saw_verified_deploy(
            fake, transport=transport, rm_id=want_rm_id, sizes=_real_sizes(),
        )


def test_facade_deploy_real_led_then_nanosoc_second_swap():
    """Two consecutive real-overlay swaps (led -> nanosoc): the second one
    clears the first RM using the clearing cached from led's own push —
    the server-visible half of the I2 clearing-cache contract.

    This is the test that would catch a deploy pushing the WRONG overlay: each
    leg pins the version-stable design half (led 0x001E, nanosoc 0x0001) as
    well as round-tripping that leg's own manifest-declared id.
    """
    led_dir = real_overlay_dir("led")
    nanosoc_dir = real_overlay_dir("nanosoc")
    led_rm_id = _real_rm_id("led")
    nanosoc_rm_id = _real_rm_id("nanosoc")
    assert rm_design_id(led_rm_id) == DESIGN_ID_LED
    assert rm_design_id(nanosoc_rm_id) == DESIGN_ID_NANOSOC
    assert led_rm_id != nanosoc_rm_id, "the two legs must be distinguishable"
    with FakeShell.ephemeral(static_id=_real_static_id()) as fake:
        with Mps3Board(
            fake.host,
            control_port=fake.control_port,
            tftp_port=fake.tftp_port,
            tcp_push_port=fake.raw_tcp_port,
            overlay_root=REAL_OVERLAY_ROOT,
        ) as board:
            led = board.deploy(led_dir)
            assert led.verified and int(led.rm_id, 0) == led_rm_id
            assert rm_design_id(led.rm_id) == DESIGN_ID_LED
            nanosoc = board.deploy(nanosoc_dir)
            assert nanosoc.verified and int(nanosoc.rm_id, 0) == nanosoc_rm_id
            assert rm_design_id(nanosoc.rm_id) == DESIGN_ID_NANOSOC
        assert [s["final"] for s in fake.swaps] == ["DONE", "DONE"]
        assert fake.current_rm_id == nanosoc_rm_id
        assert fake._current_clearing.rm_id == nanosoc_rm_id  # cached for swap 3


# --------------------------------------------------------------------------- #
# Always-on synthetic-overlay variants (CI never goes coverage-dark)
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("transport", ["tftp", "tcp"])
def test_cli_deploy_synthetic_overlay(transport, tmp_path, capsys):
    overlay_dir = make_synthetic_overlay(tmp_path)
    with FakeShell.ephemeral(static_id=SYNTHETIC_STATIC_ID) as fake:
        rc = main(deploy_argv(fake, overlay_dir, transport))
        captured = capsys.readouterr()
        assert rc == 0
        result = json.loads(captured.out)
        assert result["ok"] is True and result["verified"] is True
        # Same round-trip contract as the real-overlay tests: the board reports
        # back exactly what this overlay's manifest declared.
        assert result["rm_id"] == format_rm_id(SYNTHETIC_RM_ID)
        assert_shell_saw_verified_deploy(
            fake, transport=transport, rm_id=SYNTHETIC_RM_ID, sizes=(128, 384),
        )


@pytest.mark.parametrize("transport", ["tftp", "tcp"])
def test_facade_deploy_synthetic_overlay(transport, tmp_path):
    make_synthetic_overlay(tmp_path)
    with FakeShell.ephemeral(static_id=SYNTHETIC_STATIC_ID) as fake:
        with Mps3Board(
            fake.host,
            control_port=fake.control_port,
            tftp_port=fake.tftp_port,
            tcp_push_port=fake.raw_tcp_port,
            transport=transport,
            overlay_root=tmp_path,
        ) as board:
            result = board.deploy("nanosoc", src=transport)
            assert result.verified is True
            assert int(result.rm_id, 0) == SYNTHETIC_RM_ID
        assert_shell_saw_verified_deploy(
            fake, transport=transport, rm_id=SYNTHETIC_RM_ID, sizes=(128, 384),
        )


# --------------------------------------------------------------------------- #
# Rejection: overlay built for a different static (overlay-manifest.md rule)
# --------------------------------------------------------------------------- #

def test_cli_deploy_wrong_static_id_exits_1_and_pushes_nothing(tmp_path, capsys):
    """The shell reports a different static_id on ping, so validation
    fails HOST-side: exit 1, a clean one-line stderr, and — critically —
    no bitstream bytes ever cross the wire."""
    overlay_dir = make_synthetic_overlay(tmp_path)
    with FakeShell.ephemeral(static_id=0xDEADBEEF) as fake:
        rc = main(deploy_argv(fake, overlay_dir, "tftp"))
        captured = capsys.readouterr()
        assert rc == 1
        assert "static_id mismatch" in captured.err
        assert "Traceback" not in captured.err
        assert captured.out == ""
        assert fake.push_events == []
        assert fake.swaps == []


def test_facade_deploy_wrong_static_id_raises_swap_error(tmp_path):
    make_synthetic_overlay(tmp_path)
    with FakeShell.ephemeral(static_id=0xDEADBEEF) as fake:
        with Mps3Board(
            fake.host,
            control_port=fake.control_port,
            tftp_port=fake.tftp_port,
            tcp_push_port=fake.raw_tcp_port,
            overlay_root=tmp_path,
        ) as board:
            with pytest.raises(SwapError, match="static_id mismatch"):
                board.deploy("nanosoc")
            assert board.last_deploy is None
        assert fake.push_events == []
        assert fake.swaps == []
