#!/usr/bin/env python3
"""
gen_coe.py - turn a flat rv32 boot-stub .bin into a blk_mem_gen .coe that
initialises the linux_soc LMB boot BRAM (True_Dual_Port, Write_Width=32).

The LMB BRAM is 32-bit wide, so each COE entry is ONE 32-bit little-endian word
of the image. COE word index i == logical BRAM location i == byte address i*4,
and the reset vector is byte 0 == word 0 == _start. Little-endian assembly means
the COE hex value is exactly the 32-bit value a RISC-V load/fetch returns at that
address.

Usage: gen_coe.py <in.bin> <out.coe>
"""
import sys, struct

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_coe.py <in.bin> <out.coe>")
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        data = f.read()
    # pad up to a 4-byte boundary so the last word is complete
    if len(data) % 4:
        data += b"\x00" * (4 - (len(data) % 4))
    words = [struct.unpack_from("<I", data, i)[0] for i in range(0, len(data), 4)]
    if not words:
        words = [0]
    with open(dst, "w") as o:
        o.write("; mbv stage0 loader BRAM image -- generated by gen_coe.py\n")
        o.write("; %d words (%d bytes), 32-bit little-endian, word 0 = reset vector\n"
                % (len(words), len(data)))
        o.write("memory_initialization_radix=16;\n")
        o.write("memory_initialization_vector=\n")
        o.write(",\n".join("%08X" % w for w in words))
        o.write(";\n")
    print("gen_coe: %s -> %s (%d words / %d bytes)" % (src, dst, len(words), len(data)))

if __name__ == "__main__":
    main()
