#!/usr/bin/env python3
"""
bin2coe.py -- flat binary -> blk_mem_gen .coe, for the LMB boot BRAM.

Used only as the FALLBACK memory-init path in sim.tcl (MEM_INIT=coe). The
default path (MEM_INIT=elf) hands the ELF straight to Vivado, which drives
updatemem off the BD's own memory-map info -- that is the vendor flow and it
cannot get the byte lanes wrong.

BYTE ORDER -- the one thing this file can silently get wrong, so here is the
derivation rather than an assertion. Checked against the GENERATED RTL, not from
memory:

  * linux_soc_ilmb_bram_if_cntlr_0.vhd declares
        LMB_WriteDBus : IN  STD_LOGIC_VECTOR(0 TO 31);
        BRAM_Dout_A   : OUT STD_LOGIC_VECTOR(0 TO 31);
    and wires the one straight to the other. A VHDL (0 TO 31) vector maps
    positionally onto blk_mem_gen's Verilog dina[31:0], so the BRAM word IS the
    LMB word value -- the controller does no byte swapping of its own.
  * MicroBlaze V is little-endian, so the 32-bit word the core reads at
    word-aligned byte address A is {b[A+3], b[A+2], b[A+1], b[A]}.

  => BRAM word N must be the LITTLE-endian u32 of image bytes [4N .. 4N+3],
     which is exactly the "<I" packing below.

  If the CPU nevertheless boots into nothing with MEM_INIT=coe but is fine with
  MEM_INIT=elf, THIS derivation is what is wrong -- byte-swap here. Do not paper
  over it in the firmware.

  usage: bin2coe.py <in.bin> <out.coe> <depth_words>
"""
import sys
import struct


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    src, dst, depth = sys.argv[1], sys.argv[2], int(sys.argv[3])

    with open(src, "rb") as f:
        blob = f.read()
    if len(blob) % 4:
        blob += b"\x00" * (4 - len(blob) % 4)

    words = list(struct.unpack("<%dI" % (len(blob) // 4), blob))
    if len(words) > depth:
        sys.stderr.write(
            "bin2coe.py: image is %d words but the BRAM is only %d words deep "
            "(%d KiB). The LMB is too small for this firmware.\n"
            % (len(words), depth, depth * 4 // 1024)
        )
        return 1
    words += [0] * (depth - len(words))

    with open(dst, "w") as f:
        f.write("; generated by bin2coe.py from %s -- do not hand-edit\n" % src)
        f.write("memory_initialization_radix=16;\n")
        f.write("memory_initialization_vector=\n")
        f.write(",\n".join("%08X" % w for w in words))
        f.write(";\n")

    sys.stderr.write(
        "bin2coe.py: %s -> %s  (%d image words, padded to depth %d)\n"
        % (src, dst, len(blob) // 4, depth)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
