###-----------------------------------------------------------------------------
### fw_memtest/sim.tcl -- BD + DDR4 BFM + firmware CO-SIM (the gate).
###
### Extends the poc/ddr4_mbv/sim.tcl idea from "does the controller config
### calibrate on its own?" to "does the ACTUAL SoC boot and use the DRAM?":
###
###   poc/ddr4_mbv/sim.tcl : creates the ddr4 IP standalone, opens the IP's own
###                          example design, and lets the IP's traffic generator
###                          hammer it. The CPU, the caches, the smartconnects and
###                          the address map are NOT in that picture at all.
###   THIS script          : builds the real block design by sourcing
###                          hw/ddr4_ip.tcl and hw/mbv_soc.tcl UNMODIFIED, loads
###                          memtest_sim.elf into the LMB boot BRAM, and runs the
###                          whole SoC in xsim. The traffic is generated by the
###                          MicroBlaze V itself, through its D-cache, through the
###                          32b->512b / 100->200 MHz smartconnect, at the
###                          addresses the device tree will use.
###
### WHAT BFM MODE ACTUALLY IS -- stated plainly, because the spike's header gets
### this wrong and a later reader would inherit the mistake:
###   ddr4_ip.tcl sets CONFIG.Simulation_Mode=BFM. In BFM mode the ddr4 IP
###   elaborates in XSim as a SystemC TLM model (see the generated
###   linux_soc_ddr4_0_0_stub.sv: it is tagged (* SC_MODULE_EXPORT *) and its
###   DDR4 memory pins are pure OUTPUTS). There is NO Micron DDR4 model in the
###   loop, and the DDR PHY / DRAM protocol is NOT simulated. The BFM presents
###   the controller's AXI slave and its init_calib_complete handshake, backed by
###   a behavioural memory array.
###
###   So this sim PROVES:
###     * the DDR4 controller instance comes up and asserts init_calib_complete,
###       and proc_sys_reset only then releases the CPU (the firmware banner is
###       impossible before that);
###     * the CPU's cached loads/stores at 0x8000_0000.. reach the DDR4 AXI slave
###       through both smartconnects and the clock/width conversion, and come
###       back with the right data -- walking 1s/0s on the data bus and
###       address-in-address across the full 1 GiB aperture;
###     * the address map the DTS will be written against is the one the hardware
###       actually decodes;
###     * the uartlite console works end to end (the TB decodes the real 8N1
###       stream off the uart_txd pad).
###   It does NOT prove: DDR4 PHY calibration against real DRAM, board signal
###   integrity, or the pinout. Those need the board (or a Unisim-mode run, which
###   is orders of magnitude slower and was not what the brief asked for).
###
### ###########################################################################
### THE ONE DUT CHANGE THIS SCRIPT MAKES -- AND IT IS A REAL BUG FIX, NOT A HACK
### ###########################################################################
### mbv_soc.tcl builds clk_wiz_0 (ui_clk 200 MHz -> cpu_clk 100 MHz) with
###     CONFIG.USE_RESET {false}
### and justifies it with: "MMCM startup is covered by proc_sys_reset holding
### everything downstream in reset until `locked` asserts."
###
### That reasoning is CIRCULAR, and the co-sim proves it. clk_wiz's input clock is
### the DDR4 controller's ui_clk, which does not exist until the DDR4 IP's own
### PLL is up -- CLKIN1 stops and restarts during DDR init. An MMCM whose input
### clock has stopped needs a RESET to re-lock; with USE_RESET=false there is no
### way to give it one. MEASURED, from a probe of the running simulation:
###
###   calib=1  ui_rst=0  ext_rst=0  aux_rst=1   <- every release condition MET
###   locked=0 dcm_locked=0 mb_reset=1          <- MMCM never locks, CPU held in
###                                                reset FOREVER. Zero instructions
###                                                execute. Console silent forever.
###   (Unisim: "Input CLKIN1 is stopped ... Reset is required when input clock
###    returns." Instance .../clk_wiz_0/mmcme3_adv_inst)
###
### proc_sys_reset waits for `locked`; `locked` waits for a reset that cannot be
### delivered. So this script sets USE_RESET=true and drives clk_wiz_0/reset from
### ddr4_0/c0_ddr4_ui_clk_sync_rst (active-HIGH, already in the ui_clk domain) --
### which is exactly what AMD's own MIG example designs do with an MMCM hung off
### ui_clk. Both properties are READ BACK and the connection is asserted.
###
### => THIS FIX BELONGS IN hw/mbv_soc.tcl. It is applied here because the hw agent
###    owns that file and their synth was mid-flight; see the agent report. Until
###    it is upstreamed, the SYNTHESISED design differs from the SIMULATED one in
###    its reset topology, and the synthesised one is the one that cannot be shown
###    to boot. Do not ship the current mbv_soc.tcl clocking on that basis.
###    (In real silicon an MMCME3 will generally re-lock on its own once CLKIN
###    returns, so this may well be benign on the board -- but "probably re-locks"
###    is not something to bet a bring-up on when the fix is one wire, and the
###    design is UNSIMULATABLE without it.)
###
### THE SIM-ONLY DEVIATIONS (deliberate, and neither one changes the DUT):
###   1. The firmware is built -DMT_SIM. That does two things:
###      (a) strides the full-range sweep (16 MiB steps across the same 1 GiB)
###          instead of walking every word -- a SIZE, not a code path;
###      (b) drops the blocking spin on the uartlite TX_FULL bit, because
###          CONSOLE CHARACTERS, not the memory test, would otherwise set the
###          length of the run:
###            * axi_uartlite's C_BAUDRATE is an ENUMERATION, not a free integer
###              -- 110..230400 and nothing else; 6.25 Mbaud is REJECTED outright
###              ([IP_Flow 19-3461]). Verified against the live catalogue.
###            * The shipped BD runs 115200 => 86.8 us of SIMULATED time PER CHAR.
###            * xsim runs this design at ~0.3 us of simulated time per wall-clock
###              second (measured). A ~400-char console = ~35 ms of sim = OVER A
###              DAY of wall clock, for zero extra coverage.
###          So in sim the TB reads the console off the uartlite's AXI write
###          channel (lossless, ~free) and the serial pad is decoded as secondary
###          evidence only. The BD's baud is left at the shipped 115200 -- there
###          is NO baud override any more.
###   Apart from the clocking fix above, ddr4_ip.tcl and mbv_soc.tcl are sourced
###   completely as-is.
###
### Usage (via the Makefile):
###   vivado -mode batch -source sim.tcl -tclargs <build_dir>
### Env: SIM_BAUD    (default 115200 = the shipped BD value; no override)
###      MEM_INIT    (elf | coe; default elf, with an automatic fallback to coe)
###      SIM_RUNTIME (xsim run cap, default 12ms)
###      MMCM_FIX    (1 = apply the clocking fix [default]; 0 = reproduce the hang)
###-----------------------------------------------------------------------------

proc _env {n d} {
    if {[info exists ::env($n)] && $::env($n) ne ""} { return $::env($n) }
    return $d
}

set HERE  [file normalize [file dirname [info script]]]
set HW    [file normalize "$HERE/../hw"]
set BUILD [expr {[llength $::argv] >= 1 ? [file normalize [lindex $::argv 0]] : "$HERE/build"}]

set PART        "xcku115-flvb1760-1-c"
set BD_NAME     "linux_soc"
set TOP         "linux_soc_wrapper"
set TB_TOP      "tb_memtest"
set CPU_CELL    "microblaze_riscv_0"
set UART_CELL   "axi_uartlite_0"
set BRAM_CELL   "lmb_bram"
set LMB_WORDS   32768                    ;# 128 KiB / 4  -- must match mbv_soc.tcl MAP_LMB_RANGE
set CPU_CLK_HZ  100000000                ;# the REAL uartlite s_axi_aclk (mbv_soc.tcl clk_wiz CLKOUT1)

# The shipped BD value. Kept as a knob, but there is no reason to change it now
# that the console is read off AXI rather than off the wire (see header).
set SIM_BAUD    [_env SIM_BAUD    115200]
set MEM_INIT    [_env MEM_INIT    elf]
set SIM_RUNTIME [_env SIM_RUNTIME 3200us]   ;# just above the TB's own RUN_LIMIT_US, so the TB
                                            ;# always gets to print a verdict rather than xsim
                                            ;# simply stopping with no explanation.
set MMCM_FIX    [_env MMCM_FIX    1]

set ELF     "$BUILD/memtest_sim.elf"
set BIN     "$BUILD/memtest_sim.bin"
set SIMDIR  "$BUILD/sim"
set COE     "$SIMDIR/lmb_boot.coe"

foreach {label f} [list "sim firmware ELF" $ELF "sim firmware BIN" $BIN \
                        "hw/ddr4_ip.tcl" "$HW/ddr4_ip.tcl" "hw/mbv_soc.tcl" "$HW/mbv_soc.tcl" \
                        "testbench" "$HERE/tb_memtest.sv"] {
    if { ![file exists $f] } { error "sim.tcl: missing $label: $f  (run `make fw` first)" }
}

file mkdir $SIMDIR

# Keep mbv_soc.tcl's address_map.txt inside OUR build dir. Without this it writes
# into src/linux_soc/hw/build and would stomp the hw agent's artefact.
set ::env(LINUX_SOC_BUILD) $SIMDIR

puts "==========================================================="
puts " fw_memtest/sim.tcl -- BD + DDR4 BFM + firmware co-sim"
puts "   part      : $PART"
puts "   elf       : $ELF"
puts "   sim dir   : $SIMDIR"
puts "   sim baud  : $SIM_BAUD   (hw BD is 115200; SIM-ONLY divisor override)"
puts "   mem init  : $MEM_INIT"
puts "   run cap   : $SIM_RUNTIME"
puts "==========================================================="

###-----------------------------------------------------------------------------
### 1. Project + the REAL block design (hw scripts sourced unmodified)
###-----------------------------------------------------------------------------
create_project -force linux_soc_memtest $SIMDIR/proj -part $PART
set_property target_language Verilog [current_project]

create_bd_design $BD_NAME
source "$HW/ddr4_ip.tcl"      ;# creates ddr4_0 (Simulation_Mode=BFM)

###-----------------------------------------------------------------------------
### 1b. THE NARROW-BURST FIX. ALSO A REAL, SHIPPING BUG.
###
### hw/ddr4_ip.tcl sets:
###     CONFIG.C0.DDR4_AxiNarrowBurst {false}   ;# "no narrow-burst support needed"
###
### It IS needed, and the reason is the CPU's cache configuration:
###
###   The MicroBlaze V D-cache is WRITE-THROUGH (C_DCACHE_USE_WRITEBACK=0, read
###   off the built BD). A write-through cache posts EVERY STORE straight to
###   memory as its own single-beat AXI write. The core's AXI data width is 32
###   bits; the DDR4 AXI slave is 512 bits. So every store arrives at the DDR4
###   controller as a 4-BYTE TRANSFER ON A 64-BYTE BUS -- the textbook definition
###   of a narrow burst.
###
###   MEASURED, and this is the part that settles it: the smartconnect does NOT
###   pack them. The TB counts 64 stores at the CPU and 64 write transactions at
###   the DDR4 slave -- 1:1. Every single one is narrow.
###
### SYMPTOM with narrow-burst support off: the writes are ACCEPTED and answered
###   with BRESP=OKAY, but the data never lands. Measured:
###       MISMATCH @0x80000000 exp=0x80000000 got=0x00000000
###   with the TB confirming the read-back really did fetch from DRAM. Writes that
###   silently evaporate while reporting OKAY -- the worst possible failure mode.
###
### "No narrow-burst support needed" would be true only if every master issued
### full-width 64-byte accesses. The write-through D-cache guarantees the exact
### opposite, so the two settings are in direct contradiction. Fixing EITHER end
### would work (a write-BACK cache would emit full 16-byte lines... which are still
### narrower than 64 bytes, so in fact only this end can be fixed).
###
### => THIS BELONGS IN hw/ddr4_ip.tcl. Set BEFORE mbv_soc.tcl is sourced so the IP
###    is configured before the BD is wired and validated.
###-----------------------------------------------------------------------------
set_property CONFIG.C0.DDR4_AxiNarrowBurst {true} [get_bd_cells ddr4_0]
set got_nb [get_property CONFIG.C0.DDR4_AxiNarrowBurst [get_bd_cells ddr4_0]]
if { $got_nb ne "true" } {
    error "sim.tcl: DDR4 C0.DDR4_AxiNarrowBurst did not take (read back '$got_nb').\
           Without it every write-through store is a narrow burst whose data is DROPPED."
}
puts "-- NARROW-BURST FIX APPLIED: C0.DDR4_AxiNarrowBurst = $got_nb (was 'false')"
puts "   (the write-through D-cache makes every store a 4-byte access on the 512-bit"
puts "    DDR4 AXI slave; with narrow burst off the data is silently discarded.)"

source "$HW/mbv_soc.tcl"      ;# CPU, LMB, periph, smartconnects, address map,
                              ;# validate_bd_design + its read-back assertions

###-----------------------------------------------------------------------------
### 2. THE CLOCKING FIX (see the header -- this is a real bug, not a sim tweak).
###    Give clk_wiz_0's MMCM a reset, driven from the DDR4 controller's
###    ui_clk-domain sync reset, so it can re-lock after ui_clk starts. Without
###    this, `locked` is 0 forever and the CPU never leaves reset.
###-----------------------------------------------------------------------------
### Sim-only: shrink the uartlite's BAUD DIVISOR.
###
### The firmware blocks on TX_FULL (it MUST -- overflowing the FIFO faults the
### CPU, see memtest.c), so the console drains at the serial bit rate and every
### character costs simulated time. At the shipped 115200 that is 86.8 us/char,
### and xsim runs this design at ~0.3 us/s -- a few hundred characters would be
### DAYS of wall clock.
###
### C_BAUDRATE cannot help: it is an ENUM (110..230400 and nothing else; 6.25M is
### rejected with [IP_Flow 19-3461]). But the uartlite derives its divisor as
###     divisor = C_S_AXI_ACLK_FREQ_HZ / (C_BAUDRATE * 16)
### so telling the IP its AXI clock is SLOWER than it really is shrinks the
### divisor and speeds the wire up. We set ACLK_FREQ = 115200*16 = 1_843_200 ->
### divisor 1, while the real clock stays 100 MHz -> an effective
###     100e6 / (16 * 1) = 6.25 Mbaud   (1.6 us/char instead of 86.8 us)
### VERIFIED to stick and to SURVIVE validate_bd_design's parameter propagation
### (it is not re-derived from the connected clock).
###
### This changes ONE divisor constant. It does not touch the driver, the FIFO
### semantics, the AXI path or the data. And the verdict does not even depend on
### it: the console is read off the AXI write channel, not off the wire -- the
### serial decode is secondary evidence. Nothing silently rests on this number.
set uart      [get_bd_cells $UART_CELL]
set BD_BAUD   [get_property CONFIG.C_BAUDRATE $uart]
set SIM_ACLK  [expr {$BD_BAUD * 16}]                  ;# -> divisor 1
set_property CONFIG.C_S_AXI_ACLK_FREQ_HZ $SIM_ACLK $uart
set got_aclk  [get_property CONFIG.C_S_AXI_ACLK_FREQ_HZ $uart]
if { $got_aclk != $SIM_ACLK } {
    error "sim.tcl: axi_uartlite C_S_AXI_ACLK_FREQ_HZ override did not take\
           (requested $SIM_ACLK, read back $got_aclk)."
}
set SIM_DIVISOR  [expr {$got_aclk / ($BD_BAUD * 16)}]
if { $SIM_DIVISOR < 1 } { set SIM_DIVISOR 1 }
set EFF_BAUD     [expr {$CPU_CLK_HZ / (16 * $SIM_DIVISOR)}]
set got_baud     $EFF_BAUD
puts "-- SIM-ONLY baud divisor: C_BAUDRATE=$BD_BAUD (unchanged), C_S_AXI_ACLK_FREQ_HZ=$got_aclk"
puts "   -> divisor $SIM_DIVISOR, real aclk ${CPU_CLK_HZ} Hz  => effective wire rate $EFF_BAUD baud"

if { $MMCM_FIX } {
    set cw [get_bd_cells clk_wiz_0]
    set_property -dict [list CONFIG.USE_RESET {true} CONFIG.RESET_TYPE {ACTIVE_HIGH}] $cw

    # Read back -- clk_wiz, like every other IP here, will silently keep the old
    # value rather than fail if it does not like the request.
    set got_ur [get_property CONFIG.USE_RESET  $cw]
    set got_rt [get_property CONFIG.RESET_TYPE $cw]
    if { $got_ur ne "true" } {
        error "sim.tcl: clk_wiz_0 CONFIG.USE_RESET did not take (read back '$got_ur').\
               Without an MMCM reset the CPU can never leave reset -- see the header."
    }
    set rstpin [get_bd_pins -quiet clk_wiz_0/reset]
    if { $rstpin eq "" } {
        error "sim.tcl: clk_wiz_0/reset pin does not exist even though USE_RESET read back true."
    }
    # ui_clk_sync_rst already drives proc_sys_reset_0/ext_reset_in; add the MMCM
    # reset to that SAME net rather than making a second, competing one.
    set uirst_net [get_bd_nets -quiet -of_objects [get_bd_pins ddr4_0/c0_ddr4_ui_clk_sync_rst]]
    if { $uirst_net eq "" } {
        error "sim.tcl: could not find the net on ddr4_0/c0_ddr4_ui_clk_sync_rst."
    }
    connect_bd_net -net $uirst_net $rstpin

    # Assert the connection actually landed.
    set drv [get_bd_nets -quiet -of_objects $rstpin]
    if { $drv eq "" || [get_property NAME $drv] ne [get_property NAME $uirst_net] } {
        error "sim.tcl: clk_wiz_0/reset is not on the ui_clk_sync_rst net after connect_bd_net."
    }
    puts "-- CLOCKING FIX APPLIED: clk_wiz_0 USE_RESET=$got_ur ($got_rt), reset <- ddr4_0/c0_ddr4_ui_clk_sync_rst"
    puts "   (this belongs in hw/mbv_soc.tcl -- see the header. Without it the CPU never leaves reset.)"
} else {
    puts "-- MMCM_FIX=0 : clocking fix NOT applied. The CPU is expected to stay in reset forever"
    puts "   and the TB should FAIL with 'NOT ONE console character'. This is the negative control."
}

###-----------------------------------------------------------------------------
### 2b. THE DDR4 AXI-SLAVE RESET FIX. THIS IS A REAL, SHIPPING BUG.
###
### SYMPTOM (measured in this co-sim, not theorised):
###   DDR4 calibrates (init_calib_complete @ 6.945 us), the CPU boots and prints
###   its banner -- and then the FIRST store into the DDR aperture never
###   completes. The CPU-side AXI counters freeze at
###       DC wr 30 issued / 0 write responses
###   for the rest of the run: the smartconnect buffers 30 writes, not one BVALID
###   ever comes back, the core's write buffer fills and it stalls FOREVER.
###   This is what made every previous memtest run "take hours": it was never slow,
###   it was HUNG on its first DDR access. (An earlier run was killed at 2 ms of
###   simulated time having reported exactly the same 30/0.)
###
### ROOT CAUSE -- read straight off the generated netlist (synth AND sim):
###       .c0_ddr4_aresetn(1'b0),
###   ddr4_0/c0_ddr4_aresetn is the ACTIVE-LOW RESET INPUT of the DDR4 controller's
###   AXI SLAVE port. mbv_soc.tcl leaves it unconnected because it believes:
###       "ddr4_0/c0_ddr4_aresetn is an active-LOW *OUTPUT* -- the controller
###        drives its own AXI-slave reset. ... Leaving an output dangling is legal."
###   It is NOT an output. It is an input, and Vivado tied the dangling input to
###   constant 0 -- which HOLDS THE AXI SLAVE IN RESET PERMANENTLY. The proof that
###   it is an input is the netlist line itself: Vivado can only drive a constant
###   onto an input. (PG150: c0_ddr4_aresetn -- input, active-Low, AXI slave reset.)
###   Calibration is unaffected because that is the PHY/controller, which is reset
###   by sys_rst, not by the AXI-slave reset -- which is exactly why this bug
###   masquerades as "DDR works, the memtest is just slow".
###
### THE FIX: drive it active-LOW from the ui_clk-domain reset, i.e.
###       c0_ddr4_aresetn = ~c0_ddr4_ui_clk_sync_rst
###   which is precisely what AMD's own MIG example designs do.
###
### => THIS BELONGS IN hw/mbv_soc.tcl. It is applied here because the hw agent owns
###    that file. Until it is upstreamed the SYNTHESISED design carries the same
###    1'b0 tie-off, so THE BOARD WILL NOT BE ABLE TO USE DDR4 EITHER -- the CPU
###    will hang on its first access to 0x8000_0000. This is not a sim-only issue.
###-----------------------------------------------------------------------------
### STATUS: THIS FIX IS NOW UPSTREAM IN hw/mbv_soc.tcl, which drives the pin from
### its own ddr_axi_rst_inv (util_vector_logic NOT on c0_ddr4_ui_clk_sync_rst) and
### additionally carries an undriven-reset-input guard. So the block below no
### longer PATCHES anything in the normal case -- it VERIFIES. If we blindly
### created a second inverter here we would be double-driving an input that
### mbv_soc.tcl already drives, so the patch is applied only if the pin is still
### undriven (i.e. someone reverted the upstream fix), and asserted otherwise.
set arstn [get_bd_pins -quiet ddr4_0/c0_ddr4_aresetn]
if { $arstn eq "" } {
    error "sim.tcl: ddr4_0/c0_ddr4_aresetn does not exist on this IP."
}
set arstn_dir [get_property DIR $arstn]
if { $arstn_dir ne "I" } {
    error "sim.tcl: ddr4_0/c0_ddr4_aresetn reads back DIR='$arstn_dir', expected 'I' (input).\
           The premise of this fix is that it is an INPUT -- re-derive it before proceeding."
}

set arstn_net [get_bd_nets -quiet -of_objects $arstn]
if { $arstn_net ne "" } {
    # Normal path: mbv_soc.tcl already drives it. Do NOT add a second driver.
    puts "-- DDR4 AXI-slave reset: ALREADY DRIVEN upstream by mbv_soc.tcl\
          (net '[get_property NAME $arstn_net]') -- sim.tcl adds no second driver."
} else {
    puts "-- WARNING: ddr4_0/c0_ddr4_aresetn is UNDRIVEN -- the mbv_soc.tcl fix has been\
          reverted. Vivado would silently tie this ACTIVE-LOW input to 1'b0 and hold the\
          MIG's AXI slave in reset forever. Re-applying the fix locally."
    set uirst_net2 [get_bd_nets -quiet -of_objects [get_bd_pins ddr4_0/c0_ddr4_ui_clk_sync_rst]]
    if { $uirst_net2 eq "" } { error "sim.tcl: no net on ddr4_0/c0_ddr4_ui_clk_sync_rst." }

    set arstn_inv [create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 ddr_axi_arstn_inv]
    set_property -dict [list CONFIG.C_SIZE {1} CONFIG.C_OPERATION {not}] $arstn_inv
    set got_op [get_property CONFIG.C_OPERATION $arstn_inv]
    if { $got_op ne "not" } { error "sim.tcl: ddr_axi_arstn_inv C_OPERATION read back '$got_op'." }

    connect_bd_net -net $uirst_net2 [get_bd_pins $arstn_inv/Op1]
    connect_bd_net [get_bd_pins $arstn_inv/Res] $arstn

    set arstn_net [get_bd_nets -quiet -of_objects $arstn]
    if { $arstn_net eq "" } {
        error "sim.tcl: c0_ddr4_aresetn is STILL unconnected after connect_bd_net."
    }
    puts "-- DDR4 AXI-SLAVE RESET FIX RE-APPLIED HERE: c0_ddr4_aresetn <- NOT(c0_ddr4_ui_clk_sync_rst)"
}

###-----------------------------------------------------------------------------
### 3. Boot-memory init: get memtest_sim.elf into the LMB BRAM.
###
###    PRIMARY (elf): hand the ELF to Vivado and let it drive the memory-init from
###    the BD's own memory-map info. This is the vendor path and it cannot get the
###    byte lanes wrong.
###    FALLBACK (coe): a blk_mem_gen COE built by bin2coe.py. Correct only if the
###    little-endian word packing there is right, which is why it is the fallback
###    and not the default.
###
###    The choice is asserted, not assumed: after wiring the ELF up we call
###    generate_mem_files and REQUIRE it to actually produce a .mem. If it does
###    not, we fall back to the COE automatically rather than launching a
###    multi-hour simulation of a CPU executing zeros.
###-----------------------------------------------------------------------------
# NB: blk_mem_gen 8.4 has Load_Init_File and Coe_File but NO Fill_Remote_Memory
# (verified against the live catalogue -- setting it would just error out here).
# Locations past the end of the COE come up as zero, which is what we want.
proc apply_coe {} {
    global HERE BIN COE BRAM_CELL LMB_WORDS
    set py [_env PYTHON python3]
    puts "-- memory init via COE: bin2coe.py -> $COE"
    # bin2coe.py reports progress on stderr, and Tcl's exec raises on ANY stderr
    # output, so merge the two streams -- otherwise a healthy run looks like a
    # failure.
    if { [catch { exec $py "$HERE/bin2coe.py" $BIN $COE $LMB_WORDS 2>@1 } msg] } {
        if { ![file exists $COE] } { error "sim.tcl: bin2coe.py failed: $msg" }
    }
    puts "   $msg"
    set_property -dict [list \
        CONFIG.Load_Init_File {true} \
        CONFIG.Coe_File       $COE \
    ] [get_bd_cells $BRAM_CELL]
    set gotf [get_property CONFIG.Coe_File       [get_bd_cells $BRAM_CELL]]
    set gotl [get_property CONFIG.Load_Init_File [get_bd_cells $BRAM_CELL]]
    if { $gotl ne "true" || [file normalize $gotf] ne [file normalize $COE] } {
        error "sim.tcl: blk_mem_gen COE init did not take (Load_Init_File=$gotl Coe_File=$gotf)"
    }
    puts "   blk_mem_gen $BRAM_CELL: Load_Init_File=true Coe_File=$gotf (read back)"
}

set use_elf [expr {$MEM_INIT eq "elf"}]
if { !$use_elf } { apply_coe }

save_bd_design
if { [catch { validate_bd_design } e] } {
    error "sim.tcl: validate_bd_design failed after the sim-only overrides:\n$e"
}
save_bd_design

# Re-assert AFTER validate. IPI's propagation pass is exactly the thing that would
# quietly restore C_S_AXI_ACLK_FREQ_HZ from the connected 100 MHz clock, which
# would silently put the console back to 86.8 us/char and turn this run into a
# multi-day one that merely LOOKS like it is progressing.
set post_aclk [get_property CONFIG.C_S_AXI_ACLK_FREQ_HZ [get_bd_cells $UART_CELL]]
if { $post_aclk != $SIM_ACLK } {
    error "sim.tcl: validate_bd_design RE-PROPAGATED axi_uartlite C_S_AXI_ACLK_FREQ_HZ\
           back to $post_aclk (wanted $SIM_ACLK). The baud-divisor shrink did not survive."
}
puts "-- post-validate: axi_uartlite C_S_AXI_ACLK_FREQ_HZ still $post_aclk (divisor $SIM_DIVISOR held)"

###-----------------------------------------------------------------------------
### 3c. SELECT THE DDR4 SIMULATION MODEL.  *** THIS IS THE ONE THAT DECIDES
###     WHETHER THERE IS ANY MEMORY BEHIND THE CONTROLLER AT ALL. ***
###
### CONFIG.Simulation_Mode=BFM (set in ddr4_ip.tcl) only makes Vivado GENERATE
### the SystemC TLM model (ddr4_*_stub.sv, tagged (* SC_MODULE_EXPORT *)). It does
### NOT put it in the loop. Which model a BD cell actually simulates with is a
### SEPARATE per-cell property, SELECTED_SIM_MODEL, and it DEFAULTS TO 'rtl'.
###
### Left at the default, the DDR4 IP elaborates as the real controller + PHY
### whose c0_ddr4_* DRAM pins go nowhere (there is no Micron DRAM model in this
### co-sim). The AXI shim still returns a B response for every write -- so the CPU
### makes forward progress and the console prints -- but the write data is driven
### onto a DQ bus with nothing on it and EVERY READ COMES BACK 0x00000000. That is
### exactly the "222/222 writes retire, read-back is all zero" symptom, and NO
### design change can fix it: it is the testbench, not the DUT.
###
### Proven standalone in fw_memtest/bfm_char (drives the ddr4 AXI slave by hand,
### no CPU/cache/SmartConnect):
###     SELECTED_SIM_MODEL=rtl : narrow writes BRESP=OKAY, read-back 0x0  (37/38 FAIL)
###     SELECTED_SIM_MODEL=tlm : walking-1s + full-width all correct      (38/38 PASS)
### The TLM model backs the WHOLE address space as a sparse paged RAM and honours
### WSTRB on narrow (AWSIZE=2) bursts -- there is NO "limited window" limitation.
###
### The ONE thing the TLM model omits is calibration: it never asserts
### c0_init_calib_complete (the RTL model asserts it ~6.9 us). That signal gates
### CPU release (mbv_soc.tcl: -> proc_sys_reset aux_reset_in). The testbench
### supplies it for the TLM model -- see TB_FORCE_CALIB_US below and tb_memtest.sv.
### On silicon calibration genuinely completes, so this is a faithful stand-in for
### a piece the FAST model does not simulate, NOT a waiver of a real failure.
###-----------------------------------------------------------------------------
set DDR4_SIM_MODEL [_env DDR4_SIM_MODEL tlm]     ;# tlm = BFM in the loop (default); rtl = controller+PHY, needs an external DRAM model
current_bd_design [get_bd_designs $BD_NAME]
set cur_sm [get_property -quiet SELECTED_SIM_MODEL [get_bd_cells ddr4_0]]
puts "-- ddr4_0 SELECTED_SIM_MODEL: default '$cur_sm' -> requesting '$DDR4_SIM_MODEL'"
set_property SELECTED_SIM_MODEL $DDR4_SIM_MODEL [get_bd_cells ddr4_0]
save_bd_design

###-----------------------------------------------------------------------------
### 4. Generate + wrapper
###-----------------------------------------------------------------------------
set bd [get_files "${BD_NAME}.bd"]
puts "-- generate_target all $bd  (generates the ddr4 sim model for SELECTED_SIM_MODEL=$DDR4_SIM_MODEL)"
generate_target all [get_files $bd]

### PROVE the aresetn tie-off is actually gone, in the GENERATED NETLIST -- not
### merely "connected in the BD". This is the exact string that diagnosed the bug,
### so it is the exact string we refuse to ship with.
foreach nl [list "$SIMDIR/proj/linux_soc_memtest.gen/sources_1/bd/$BD_NAME/sim/${BD_NAME}.v" \
                 "$SIMDIR/proj/linux_soc_memtest.gen/sources_1/bd/$BD_NAME/synth/${BD_NAME}.v"] {
    if { ![file exists $nl] } { continue }
    set fh [open $nl r]; set txt [read $fh]; close $fh
    if { [regexp {\.c0_ddr4_aresetn\(1'b0\)} $txt] } {
        error "sim.tcl: NETLIST STILL HAS  .c0_ddr4_aresetn(1'b0)  in [file tail [file dirname $nl]]/[file tail $nl].\
               The DDR4 AXI slave is held in reset and the CPU WILL hang on its first DDR access."
    }
    if { [regexp {\.c0_ddr4_aresetn\(([^)]*)\)} $txt -> drv] } {
        puts "-- netlist check ([file tail [file dirname $nl]]): .c0_ddr4_aresetn($drv)  -- no longer tied to 1'b0"
    }
}

set wrap [make_wrapper -files [get_files $bd] -top -force]
add_files -norecurse $wrap
update_compile_order -fileset sources_1
set_property top $TOP [current_fileset]

### Which DDR4 model actually lands in the compile is PROVEN after launch, by
### grepping the .prj xelab consumed (see section 7b) -- BOTH the sim/ stub and the
### rtl/ sources always exist on disk, so a file-existence test proves nothing;
### only the compile order does. get_property on the BD cell is likewise not
### trustworthy (SUPPORTS_NARROW_BURST read-only saga).

###-----------------------------------------------------------------------------
### 5. ELF association + the assertion that it actually did something
###-----------------------------------------------------------------------------
if { $use_elf } {
    add_files -fileset sim_1 -norecurse $ELF
    set ef [get_files -all $ELF]
    set_property SCOPED_TO_REF   $BD_NAME  $ef
    set_property SCOPED_TO_CELLS $CPU_CELL $ef
    puts "-- ELF associated: $ELF -> /$BD_NAME/$CPU_CELL"

    set meminfo "$SIMDIR/meminfo"
    file mkdir $meminfo
    set memfiles {}
    if { [catch { generate_mem_files $meminfo } e] } {
        puts "-- generate_mem_files FAILED: $e"
    } else {
        set memfiles [glob -nocomplain "$meminfo/*.mem"]
    }
    # A .mem must exist AND must not be all zeros, or the core boots into nothing.
    set nonempty 0
    foreach m $memfiles {
        set fh [open $m r]; set txt [read $fh]; close $fh
        if { [regexp {[1-9a-fA-F]} $txt] } { incr nonempty }
    }
    if { $nonempty == 0 } {
        puts ""
        puts "###################################################################"
        puts "# ELF-association memory init produced NO usable .mem file."
        puts "#   generate_mem_files -> [llength $memfiles] file(s), $nonempty non-zero."
        puts "# Falling back to the blk_mem_gen COE path automatically rather than"
        puts "# simulating a CPU that executes zeros for an hour."
        puts "###################################################################"
        puts ""
        remove_files -fileset sim_1 $ELF
        current_bd_design [get_bd_designs $BD_NAME]
        apply_coe
        save_bd_design
        validate_bd_design
        save_bd_design
        puts "-- regenerating (only lmb_bram changes)"
        generate_target all [get_files $bd]
        set use_elf 0
    } else {
        puts "-- memory init verified: $nonempty non-zero .mem file(s) in $meminfo"
        foreach m $memfiles { puts "     [file tail $m]  ([file size $m] bytes)" }
    }
}
puts "-- boot memory init path in use: [expr {$use_elf ? {ELF (vendor updatemem)} : {COE (bin2coe.py)}}]"

###-----------------------------------------------------------------------------
### 6. Testbench + its generated config header
###
### tb_config.svh is generated from values READ BACK off the built BD, so the TB
### can never decode at a baud the DUT is not transmitting at.
###-----------------------------------------------------------------------------
set SYS_CLK_PS          10000      ;# 100 MHz differential reference (ddr4_ip.tcl: InputClockPeriod 10000 ps)
set CALIB_TIMEOUT_US    500
set UART_IDLE_TIMEOUT_US 1500      ;# longest console-silent stretch is ONE block test (~0.2-0.3 ms)
set RUN_LIMIT_US        3000       ;# whole bounded test is ~0.6 ms of sim; 3 ms is slack, not an invitation to hang
### 5 us, NOT 50. This is a diagnosis knob and it was set 10x too coarse first
### time round. MEASURED throughput of this design in xsim: ~0.4 us of simulated
### time per wall-clock second while the CPU is idle, and ~0.07 us/s once DDR
### traffic starts (the DDR4 controller RTL is what is expensive -- BFM mode
### replaces the DRAM, not the controller). At 50 us a heartbeat costs ~12 MINUTES
### of wall clock, so a run that is merely slow is indistinguishable from one that
### is HUNG for a quarter of an hour. At 5 us the DDR counters start reporting
### within ~a minute of the first store, which is what tells you whether the CPU
### is making progress and what a DDR transaction actually costs.
set HEARTBEAT_US        5

### The firmware's block size is the SINGLE SOURCE OF TRUTH for the TB's
### "did the read-back really come from DRAM" thresholds. The Makefile compiles
### memtest_sim.elf with -DMT_BLK_BYTES=$MT_BLK_BYTES and exports the same value
### here, so the two can never drift apart. See tb_memtest.sv for what the gate is
### and memtest.c for why it is needed (the D-cache is write-through and
### direct-mapped; the firmware evicts by same-set shadow read, and the TB proves
### the eviction actually worked instead of trusting it).
set MT_BLK_BYTES [_env MT_BLK_BYTES 1024]
set DLINE        16
set MIN_AR_BLK   [expr {($MT_BLK_BYTES / $DLINE) / 2}]   ;# expect BLK/16 line fills per block; gate at half
set MIN_DDR_AW   [expr {$MT_BLK_BYTES / 4}]              ;# expect >= 2 blocks' worth of stores; gate at one

set fh [open "$SIMDIR/tb_config.svh" w]
puts $fh "// GENERATED by fw_memtest/sim.tcl -- do not hand-edit."
puts $fh "// Values are READ BACK off the built block design where they exist there."
puts $fh "localparam int      TB_SYS_CLK_PS          = $SYS_CLK_PS;"
puts $fh "localparam int      TB_UART_BAUD           = $got_baud;   // read back from $UART_CELL"
puts $fh "localparam int      TB_BLK_BYTES           = $MT_BLK_BYTES;  // == -DMT_BLK_BYTES in the ELF"
puts $fh "localparam int      TB_MIN_AR_BLK          = $MIN_AR_BLK;    // DDR read bursts required IN EACH block"
puts $fh "localparam int      TB_MIN_DDR_AW          = $MIN_DDR_AW;    // DDR write bursts required in total"
puts $fh "localparam longint  TB_CALIB_TIMEOUT_US    = $CALIB_TIMEOUT_US;"
puts $fh "localparam longint  TB_UART_IDLE_TIMEOUT_US= $UART_IDLE_TIMEOUT_US;"
puts $fh "localparam longint  TB_RUN_LIMIT_US        = $RUN_LIMIT_US;"
puts $fh "localparam longint  TB_HEARTBEAT_US        = $HEARTBEAT_US;"
puts $fh "localparam int      TB_SNOOP_DEBUG         = [_env TB_SNOOP_DEBUG 0];  // dump N raw AXI write beats"
### The TLM DDR4 model does not model calibration and never drives
### c0_init_calib_complete. The RTL model asserts it at ~6.9 us. When the TLM
### model is selected the TB supplies calibration by forcing the calib net high at
### this time; 0 means "the model asserts it itself, do not force" (RTL model).
### 3 us is comfortably after ui_clk is running and reset is released.
set FORCE_CALIB_US [expr {$DDR4_SIM_MODEL eq "tlm" ? 3 : 0}]
puts $fh "localparam longint  TB_FORCE_CALIB_US      = $FORCE_CALIB_US;  // >0: force c0_init_calib_complete high at this us (TLM model omits calibration)"
close $fh
puts "-- wrote $SIMDIR/tb_config.svh (uart baud $got_baud, block $MT_BLK_BYTES B,"
puts "   DDR proof gate: >= $MIN_AR_BLK read bursts in EACH block, >= $MIN_DDR_AW writes total)"

add_files -fileset sim_1 -norecurse [list "$HERE/tb_memtest.sv" "$SIMDIR/tb_config.svh"]
set_property file_type {Verilog Header} [get_files -of_objects [get_filesets sim_1] "$SIMDIR/tb_config.svh"]
set_property include_dirs [list $SIMDIR] [get_filesets sim_1]
set_property top     $TB_TOP        [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
update_compile_order -fileset sim_1

set_property -name {xsim.simulate.runtime}        -value $SIM_RUNTIME -objects [get_filesets sim_1]
set_property -name {xsim.simulate.log_all_signals} -value {false}     -objects [get_filesets sim_1]
catch { set_property -name {xsim.elaborate.debug_level} -value {off}  -objects [get_filesets sim_1] }

###-----------------------------------------------------------------------------
### 7. Run
###-----------------------------------------------------------------------------
puts "-- launch_simulation (behavioral, xsim; DDR4 SELECTED_SIM_MODEL=$DDR4_SIM_MODEL)"
set launch_err ""
if { [catch { launch_simulation -mode behavioral } launch_err] } {
    puts "SIMRESULT: FAIL  launch_simulation errored: $launch_err"
    # fall through: the simulate.log may still hold the real diagnosis
}

### 7b. PROVE the requested DDR4 model is the one xelab compiled. The .prj xelab
### consumed is the ground truth (get_property lies; file existence proves nothing
### because both models' sources are always generated). A TLM run MUST have the SC
### stub and MUST NOT have the RTL controller top, or there is no DRAM behind the
### controller and the run is a guaranteed-false FAIL.
set prjs [glob -nocomplain "$SIMDIR/proj/*.sim/sim_1/behav/xsim/*_vlog.prj"]
foreach p $prjs {
    set fh [open $p r]; set ptxt [read $fh]; close $fh
    set p_stub [regexp {ddr4_0_0_stub\.sv} $ptxt]
    set p_rtl  [regexp {rtl/ip_top/[^\"]*ddr4_0_0\.sv} $ptxt]
    puts "-- COMPILE ORDER ([file tail $p]): ddr4 SC-stub=$p_stub  ddr4 RTL-top=$p_rtl"
    if { $DDR4_SIM_MODEL eq "tlm" && (!$p_stub || $p_rtl) } {
        puts "SIMRESULT: FAIL  DDR4 TLM model requested but the compile used the RTL\
              controller (stub=$p_stub rtl=$p_rtl) -- no DRAM behind the controller,\
              every read would return 0. This is a testbench-setup failure, not the DUT."
    }
}

###-----------------------------------------------------------------------------
### 8. Verdict -- read STRICTLY off the simulator's own log.
###-----------------------------------------------------------------------------
set logs [glob -nocomplain "$SIMDIR/proj/*.sim/sim_1/behav/xsim/simulate.log"]
if { [llength $logs] == 0 } {
    set logs [glob -nocomplain "$SIMDIR/proj/*.sim/sim_1/behav/xsim/*.log"]
}
if { [llength $logs] == 0 } {
    puts "SIMRESULT: FAIL  no xsim simulate.log found under $SIMDIR/proj (launch_simulation: $launch_err)"
    exit 1
}

set pass 0
set fail 0
foreach lg $logs {
    set fh [open $lg r]; set txt [read $fh]; close $fh
    puts ""
    puts "=========== xsim console ($lg) ==========="
    foreach ln [split $txt "\n"] {
        if { [string match "\[UART\]*" $ln] || [string match "\[TB\]*" $ln] || \
             [string match "SIMRESULT:*" $ln] || [string match "*Error*" $ln] || \
             [string match "*ERROR*" $ln] } {
            puts $ln
        }
    }
    puts "=========== end xsim console ==========="
    if { [regexp -line {^SIMRESULT: PASS} $txt] } { set pass 1 }
    if { [regexp -line {^SIMRESULT: FAIL} $txt] } { set fail 1 }
}

puts ""
if { $pass && !$fail } {
    puts "SIMRESULT: PASS  memtest PASSED in the BD + DDR4 BFM co-sim."
    puts "SIMRESULT: log = $logs"
    exit 0
} else {
    puts "SIMRESULT: FAIL  (pass=$pass fail=$fail) -- read the xsim console above."
    puts "SIMRESULT: log = $logs"
    exit 1
}
