/* clcd_glyphs.h: the MPS3 front panel's extension glyphs, 0x80-0x86, as 8x16 bitmaps.
 *
 * GENERATED by Harness Manager tools/gen_tokens.py from its CLCD_GLYPHS table (the one
 * glyph table: tools/clcd_mock.py renders with it): do not edit.
 * Regenerate in Harness Manager: python3 tools/gen_tokens.py
 * This file is vendored by the Linux harness (firmware/clcd/HM_VENDORED.md), with clcd_palette.h.
 *
 * source commit:  c74a1cfe734c
 * glyphs sha256:  b28180da76c99e975ba6d342740b5a22ff85925a70dcd939a04cf360fbe59f71
 * layout:         16 scanlines per glyph, top first; bit 7 = the leftmost pixel
 *
 * font8x16_ext[c - CLCD_FONT_EXT_FIRST] is the bitmap of character c.
 */
#ifndef CLCD_GLYPHS_H
#define CLCD_GLYPHS_H

#include <stdint.h>

#define CLCD_GLYPHS_SHA256 "b28180da76c99e975ba6d342740b5a22ff85925a70dcd939a04cf360fbe59f71"
#define CLCD_FONT_EXT_FIRST 0x80
#define CLCD_FONT_EXT_COUNT 7

#define CLCD_GLYPH_OK   0x80
#define CLCD_GLYPH_ERR  0x81
#define CLCD_GLYPH_WARN 0x82
#define CLCD_GLYPH_HELD 0x83
#define CLCD_GLYPH_USER 0x84
#define CLCD_GLYPH_UNK  0x85
#define CLCD_GLYPH_DOT  0x86

static const uint8_t font8x16_ext[CLCD_FONT_EXT_COUNT][16] = {
    /* 0x80 ok */ {
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x02, /* ......#. */
        0x06, /* .....##. */
        0x04, /* .....#.. */
        0x8C, /* #...##.. */
        0xD8, /* ##.##... */
        0x70, /* .###.... */
        0x20, /* ..#..... */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
    },
    /* 0x81 err */ {
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0xC6, /* ##...##. */
        0xEE, /* ###.###. */
        0x7C, /* .#####.. */
        0x38, /* ..###... */
        0x7C, /* .#####.. */
        0xEE, /* ###.###. */
        0xC6, /* ##...##. */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
    },
    /* 0x82 warn */ {
        0x00, /* ........ */
        0x00, /* ........ */
        0x10, /* ...#.... */
        0x38, /* ..###... */
        0x28, /* ..#.#... */
        0x6C, /* .##.##.. */
        0x54, /* .#.#.#.. */
        0xD6, /* ##.#.##. */
        0x92, /* #..#..#. */
        0x82, /* #.....#. */
        0x92, /* #..#..#. */
        0xFE, /* #######. */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
    },
    /* 0x83 held */ {
        0x00, /* ........ */
        0x00, /* ........ */
        0x38, /* ..###... */
        0x44, /* .#...#.. */
        0x44, /* .#...#.. */
        0x44, /* .#...#.. */
        0xFE, /* #######. */
        0xFE, /* #######. */
        0xEE, /* ###.###. */
        0xEE, /* ###.###. */
        0xFE, /* #######. */
        0xFE, /* #######. */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
    },
    /* 0x84 user */ {
        0x00, /* ........ */
        0x00, /* ........ */
        0x38, /* ..###... */
        0x7C, /* .#####.. */
        0x7C, /* .#####.. */
        0x7C, /* .#####.. */
        0x38, /* ..###... */
        0x00, /* ........ */
        0x7C, /* .#####.. */
        0xFE, /* #######. */
        0xFE, /* #######. */
        0xFE, /* #######. */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
    },
    /* 0x85 unk */ {
        0x00, /* ........ */
        0x00, /* ........ */
        0x38, /* ..###... */
        0x44, /* .#...#.. */
        0x04, /* .....#.. */
        0x08, /* ....#... */
        0x10, /* ...#.... */
        0x10, /* ...#.... */
        0x00, /* ........ */
        0x10, /* ...#.... */
        0x10, /* ...#.... */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
    },
    /* 0x86 dot */ {
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x38, /* ..###... */
        0x7C, /* .#####.. */
        0x7C, /* .#####.. */
        0x7C, /* .#####.. */
        0x38, /* ..###... */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
        0x00, /* ........ */
    },
};

#endif /* CLCD_GLYPHS_H */
