/* clcd_palette.h: the MPS3 front panel's colour roles as RGB565 words.
 *
 * GENERATED by Harness Manager tools/gen_tokens.py from design/tokens.json: do not edit.
 * Vendor it unchanged; to change a colour, change the tokens in Harness Manager and
 * regenerate there (decision P4). Linux harness only (decision P3).
 *
 * tokens.json sha256: 59011d724e13ec07902e37ffdd3f6a480394cc0995d42649b3af320a73c4a4bb
 * schema:             soclabs-harness-tokens/1
 * panel:              320x240, RGB565 high byte first, channel order RGB,
 *                     theme dark, background #000000
 *
 * CLCD_PALETTE_INIT initialises a table indexed by enum clcd_role, {fg, bg} per role:
 *     static const uint16_t pal[CLCD_ROLE_COUNT][2] = CLCD_PALETTE_INIT;
 */
#ifndef CLCD_PALETTE_H
#define CLCD_PALETTE_H

#define CLCD_TOKENS_SHA256 "59011d724e13ec07902e37ffdd3f6a480394cc0995d42649b3af320a73c4a4bb"

enum clcd_role {
    CLCD_ROLE_TEXT = 0,
    CLCD_ROLE_LABEL,
    CLCD_ROLE_VALUE,
    CLCD_ROLE_RULE,
    CLCD_ROLE_CHROME,
    CLCD_ROLE_TITLE,
    CLCD_ROLE_TITLE_HELD,
    CLCD_ROLE_TITLE_WARN,
    CLCD_ROLE_OK,
    CLCD_ROLE_WARN,
    CLCD_ROLE_ERR,
    CLCD_ROLE_BUSY,
    CLCD_ROLE_UNK,
    CLCD_ROLE_HELD,
    CLCD_ROLE_BAR,
    CLCD_ROLE_TRACK,
    CLCD_ROLE_BANNER_ERR,
    CLCD_ROLE_BANNER_WARN,
    CLCD_ROLE_BANNER_OK,
    CLCD_ROLE_BANNER_BUSY,
    CLCD_ROLE_BANNER_HELD,
    CLCD_ROLE_COUNT
};

/* role fg/bg: the RGB565 word, then the token it comes from and the colour the
 * word shows on the glass. */
#define CLCD_RGB565_TEXT_FG         0xE73Du  /* text #e4e7ec -> #e7e7ef */
#define CLCD_RGB565_TEXT_BG         0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_LABEL_FG        0x7C32u  /* text-3 #7e8794 -> #7b8694 */
#define CLCD_RGB565_LABEL_BG        0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_VALUE_FG        0xE73Du  /* text #e4e7ec -> #e7e7ef */
#define CLCD_RGB565_VALUE_BG        0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_RULE_FG         0x31E9u  /* border-strong #353d49 -> #313c4a */
#define CLCD_RGB565_RULE_BG         0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_CHROME_FG       0xAD97u  /* text-2 #a9b1bd -> #adb2bd */
#define CLCD_RGB565_CHROME_BG       0x1905u  /* surface-2 #1b2028 -> #182029 */
#define CLCD_RGB565_TITLE_FG        0xE73Du  /* text #e4e7ec -> #e7e7ef */
#define CLCD_RGB565_TITLE_BG        0x1905u  /* surface-2 #1b2028 -> #182029 */
#define CLCD_RGB565_TITLE_HELD_FG   0xB4FEu  /* held #b69cf5 -> #b59ef7 */
#define CLCD_RGB565_TITLE_HELD_BG   0x1905u  /* surface-2 #1b2028 -> #182029 */
#define CLCD_RGB565_TITLE_WARN_FG   0xE56Bu  /* warn #e8ad58 -> #e7ae5a */
#define CLCD_RGB565_TITLE_WARN_BG   0x1905u  /* surface-2 #1b2028 -> #182029 */
#define CLCD_RGB565_OK_FG           0x5E31u  /* ok #5cc68c -> #5ac78c */
#define CLCD_RGB565_OK_BG           0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_WARN_FG         0xE56Bu  /* warn #e8ad58 -> #e7ae5a */
#define CLCD_RGB565_WARN_BG         0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_ERR_FG          0xEC50u  /* err #f08b82 -> #ef8a84 */
#define CLCD_RGB565_ERR_BG          0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_BUSY_FG         0x7CFEu  /* accent #7d9cf4 -> #7b9ef7 */
#define CLCD_RGB565_BUSY_BG         0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_UNK_FG          0xCE13u  /* unk #cbc19e -> #cec39c */
#define CLCD_RGB565_UNK_BG          0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_HELD_FG         0xB4FEu  /* held #b69cf5 -> #b59ef7 */
#define CLCD_RGB565_HELD_BG         0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_BAR_FG          0x0000u  /* bg #000000 -> #000000 */
#define CLCD_RGB565_BAR_BG          0x7CFEu  /* accent #7d9cf4 -> #7b9ef7 */
#define CLCD_RGB565_TRACK_FG        0x7C32u  /* text-3 #7e8794 -> #7b8694 */
#define CLCD_RGB565_TRACK_BG        0x1905u  /* surface-2 #1b2028 -> #182029 */
#define CLCD_RGB565_BANNER_ERR_FG   0xFFFFu  /* literal #ffffff -> #ffffff */
#define CLCD_RGB565_BANNER_ERR_BG   0xB124u  /* err@light #b1261d -> #b52421 */
#define CLCD_RGB565_BANNER_WARN_FG  0xFFFFu  /* literal #ffffff -> #ffffff */
#define CLCD_RGB565_BANNER_WARN_BG  0x92C0u  /* warn@light #945800 -> #945900 */
#define CLCD_RGB565_BANNER_OK_FG    0xFFFFu  /* literal #ffffff -> #ffffff */
#define CLCD_RGB565_BANNER_OK_BG    0x1BC9u  /* ok@light #1b7a48 -> #18794a */
#define CLCD_RGB565_BANNER_BUSY_FG  0xFFFFu  /* literal #ffffff -> #ffffff */
#define CLCD_RGB565_BANNER_BUSY_BG  0x32DAu  /* accent@light #2f5bd3 -> #3159d6 */
#define CLCD_RGB565_BANNER_HELD_FG  0xFFFFu  /* literal #ffffff -> #ffffff */
#define CLCD_RGB565_BANNER_HELD_BG  0x6A18u  /* held@light #6b3fc4 -> #6b41c6 */

#define CLCD_PALETTE_INIT { \
    { CLCD_RGB565_TEXT_FG, CLCD_RGB565_TEXT_BG }, \
    { CLCD_RGB565_LABEL_FG, CLCD_RGB565_LABEL_BG }, \
    { CLCD_RGB565_VALUE_FG, CLCD_RGB565_VALUE_BG }, \
    { CLCD_RGB565_RULE_FG, CLCD_RGB565_RULE_BG }, \
    { CLCD_RGB565_CHROME_FG, CLCD_RGB565_CHROME_BG }, \
    { CLCD_RGB565_TITLE_FG, CLCD_RGB565_TITLE_BG }, \
    { CLCD_RGB565_TITLE_HELD_FG, CLCD_RGB565_TITLE_HELD_BG }, \
    { CLCD_RGB565_TITLE_WARN_FG, CLCD_RGB565_TITLE_WARN_BG }, \
    { CLCD_RGB565_OK_FG, CLCD_RGB565_OK_BG }, \
    { CLCD_RGB565_WARN_FG, CLCD_RGB565_WARN_BG }, \
    { CLCD_RGB565_ERR_FG, CLCD_RGB565_ERR_BG }, \
    { CLCD_RGB565_BUSY_FG, CLCD_RGB565_BUSY_BG }, \
    { CLCD_RGB565_UNK_FG, CLCD_RGB565_UNK_BG }, \
    { CLCD_RGB565_HELD_FG, CLCD_RGB565_HELD_BG }, \
    { CLCD_RGB565_BAR_FG, CLCD_RGB565_BAR_BG }, \
    { CLCD_RGB565_TRACK_FG, CLCD_RGB565_TRACK_BG }, \
    { CLCD_RGB565_BANNER_ERR_FG, CLCD_RGB565_BANNER_ERR_BG }, \
    { CLCD_RGB565_BANNER_WARN_FG, CLCD_RGB565_BANNER_WARN_BG }, \
    { CLCD_RGB565_BANNER_OK_FG, CLCD_RGB565_BANNER_OK_BG }, \
    { CLCD_RGB565_BANNER_BUSY_FG, CLCD_RGB565_BANNER_BUSY_BG }, \
    { CLCD_RGB565_BANNER_HELD_FG, CLCD_RGB565_BANNER_HELD_BG }, \
}

#endif /* CLCD_PALETTE_H */
